name: Amanda Park
markdown: kramdown
theme: jekyll-theme-midnight

defaults:
- 
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
#permalink: /blog/:year/:month/:day/:title
