project:
  type: website
  output-dir: docs


website:
  title: "Amanda Park"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    tools:
      - icon: linkedin
        url: https://www.linkedin.com/in/parkamanda
      - icon: github
        url: https://www.github.com/amanda-park
  site-url: https://amanda-park.github.io
  description: "Amanda Park's blog"
  
format:
  html:
    theme: cosmo