---
title: 'Evaluating Educational Avenues for Starting and Advancing Your Data Science Career'
author: 'Amanda Park'
date: '2021-11-09'
slug: advancing-data-science-career
categories: ['data-science']
featured_image: ''
description: 'There are many options that exist nowadays to get your foot in the door with data science. Here I will take a look at some common ones that have showed up and used over the past few years (and why you should not go to a data science bootcamp).'
---

There are probably 5 million articles out there encouraging everyone to get into data science and learn about machine learning and AI. As someone who's actually in the field, I figured my perspective on things could offer some clarity on how to best progress in the field.

There's no one clear path towards becoming a data scientist, as much as someone may try to sell you a bootcamp for one. Here are some avenues that I've become familiar with (whether it be through experience or interviewing/knowing other data scientists):

## Academic Education: Getting a Master's Degree (or PhD)

The vast majority of data scientists have a Master's degree in a relevant field. (I can be counted amongst this group, as I have a Master's in Statistics.) Many job postings require a Master's degree for education, so having that listed on your resume will be necessary to get through some companies' applicant tracking systems (also known as their ATS).

However, I want to emphasize that it's not required to succeed. My coworker with the same job title as myself only has a Bachelor's degree, and is as competent in the role as I am. He's a motivated self-starter who was able to pick up on the more challenging nuances due to being talented and smart in his own right.

I'll be honest - a lot of what I learned in my Master's program wasn't directly applicable to what I do day-to-day in my current job. Some classes in my Master's program were invaluable, especially the machine learning and regression classes, but the theoretical and proof-heavy courses have barely been touched upon since graduating.

### The Opportunity Cost of Attending

There was also an opportunity cost to going to graduate school that I don't think is called out enough in these types of articles. 

There's the financial cost, which included tuition and books. For the financial piece, I specifically chose a state school, Binghamton, rather than a school with a higher reputation, like Cornell or RIT, specifically as a cost reduction measure. A semester at Binghamton for an in-state student was around $6000, whereas Cornell or RIT would cost double or more. I also found a scholarship that was eligible for a state school but not for private, which influenced my decision too.

However, beyond the financial cost, I also had to sacrifice holding a full-time job with benefits for those two years I attended, as the course load given by the professors required a full-time commitment from you alone (and then some). After getting my Bachelor's degree, I could have tried to get my foot in the door in a less prestigious job title (such as a Data Analyst) somewhere and learned on the job while getting decent money and experience along the way. 

That was not the right call for me in my situation. However, if you're an experienced professional it's worth considering the income loss taken if you stop working to attend graduate school full-time. It may make more sense to attend part-time after work hours, but stretch it out over 4 years. I know some friends and coworkers who have taken that approach to getting Master's degrees, but that also has its own costs (mainly a loss of free time for the duration you're getting your Master's).

Do I regret going to graduate school? No. It was a great opportunity to forge connections, and I was able to get a great position in my field not long after graduating. Because I was able to minimize the cost of attending (a luxury I know not everyone has), I did not feel the financial consequences of attending as acutely as others would.

## Professional Certifications

The alternatives that have appeared in lieu of traditional education are in the form of certifications. These options vary widely in quality, so it's highly recommended to do your research on which end up being most useful for you in your given situation. Overall, I think the knowledge you'll get from a certification will generally be more practical and specific to your day-to-day work and less focused on the theoretical underpinnings that you would get from a traditional/academic education. 

However, I've found that explaining data science certifications on a resume to be more challenging than listing traditional education, and since the quality varies so much getting certifications that aren't specific/essential to a role (like Epic with their data certifications) they may not be seen as highly valuable beyond having a "self-learner" personality. Therefore, I generally list my certification progress on my LinkedIn page (and not a resume). 

Below I'll give an overview of some companies I've used resources for to upskill in data science:

### DataCamp

This was the first site I used to learn more about data science and R, mostly while I was in grad school (so 2018-2019). Their courses shift between traditional lectures and "fill in the blank" code challenges to test your understanding of the concepts. For reference, I took the course tracks "Data Analyst in R" and "Data Scientist in R" (which at the time had 80%+ course overlap).

It was through DataCamp that I learned how to use the Tidyverse in R, since most of my math professors in grad school were unfamiliar with the framework. The course quality was very high and I felt like I learned something in all of the courses I took. The main reason I withdrew my subscription was due to a [controversy with its CEO](https://www.buzzfeednews.com/article/daveyalba/datacamp-sexual-harassment-metoo-tech-startup), but I had also exhausted most of the material I had wanted to learn about at the time.

I'd highly recommend DataCamp for upskilling in R and learning the basics of SQL. They have improved their catalog of courses for Python since I've last used the service, so it may also be valuable for learning and upskilling in Python as well. The cost of learning is very affordable relative to most (a couple hundred bucks a year).

### LinkedIn Learning

My workplace offered free access to LinkedIn Learning for all employees in September 2020, and I was eager to take advantage of it. I spent (probably way too much) time going through various Learning Paths, which were a collection between 5-12 courses related to developing or enhancing a specific skill. I primarily took Learning Paths to develop my proficiency in Python, NLP, deep learning, and general computer science principles, but I also took a couple of paths to refine my skills in R, SQL, and business communication. (What can I say? I like the low, low cost of free.)

LinkedIn Learning offers video lectures and you complete a course once you've watched everything included. There's quizzes at the end of each chapter to check your understanding of topics, which can sometimes be useful. Courses varied in length from between 30 minutes to hours, so it really depended on the course instructor how in depth you would get on a topic.

The quality of courses available on the sites varies a lot more than something like DataCamp. Some professors were great, while others were average at best. This is just more likely to happen with a site with thousands of courses available, as there's fewer means for quality control.

LinkedIn Learning was incredibly useful in getting me up to speed in the areas I wanted. I'd recommend it for anyone looking to upskill in Python, deep learning, and computer science best practices, as the content was quite strong in those realms. The business communication offerings were also very solid too. However, I would not recommend it as strongly for general data science, R and SQL upskilling, as the content was either more scarce, less detailed/useful, or more convoluted to implement.

### Coursera

Coursera is most akin to a traditional college education experience. There are courses that have their own "week" of content associated, which includes lectures, readings, homework assignments, and/or quizzes.

Coursera falls under the category of massive open online courses (MOOCs). I appreciate the democratization of knowledge that these courses offer, and I regularly audit online courses on sites like Coursera to find interesting readings and learn new topics. 

Whether or not Coursera will work for you depends on your learning style. I have never done well with academic-styled online courses, so I find Coursera more difficult to use for certification purposes than other methods. But some of the best professors from the most prestigious institutions are on the platform, so if that style of learning works well for you, the quality of education is easily available. I recommend researching the platform and other similar competitors like EdX and Udacity if that environment works well for you.

### 365 Data Science

I tried out 365 Data Science over the past month due to them offering all their content for free as a result of a recent rebranding. (If it wasn't free, I would not have, to be completely honest.) I took the courses Data Strategy and Product Management for AI and Data Science, which were a few hours each. They had tracks for Business Analyst, Data Scientist, and Data Analyst, but given the limited time the service was available and my experience in the field already, there was less value in their course offerings for me than I would have gleaned a couple of years ago.

Their offerings are pretty high quality and the courses I took focused clearly on the business needs. Their offerings currently for the theoretical aspects of data science were there, but pretty scant. Their course offerings were focused on BI dashboarding tools (PowerBI, Tableau) and Python/SQL. There was not much love for R at all, so I would not recommend the service for anything beyond a cursory overview of the language.

## Buyer Beware: Bootcamps

Coding and data science bootcamps have been popping up all over the place to meet the demand for data scientists in many industries. These are intensive 13-week long (or more) "live, eat, breathe, and sleep" data science experiences. I've interviewed some candidates who have gone through these bootcamps, and just based on the material I've heard these candidates talk about, they are not a be-all end-all solution to becoming a data scientist. I highly recommend that someone NOT take this avenue for learning to be a data scientist for these reasons:

### They Don't Teach the Right Material

Many of these camps focus exclusively on machine learning and neural networks, which is not the core knowledge needed to succeed in data science. 80% of data science is cleaning your data and understanding business problems, which isn't taught in a bootcamp. It's unglamorous, but you will be using SQL more than you will be using deep learning.

A statistics background is also underemphasized in many of these bootcamps, which leads to a poor return on investment. Sure, it's a great project to put on a resume that you deployed a recurrent neural network model in TensorFlow through AWS, but if you can't describe a p-value properly to someone, any company worth their salt won't hire you as a data scientist. 

### Employers Can't Validate A Bootcamp's Quality

Bootcamps don't carry the prestige that a traditional education path does. Employers barely look at a resume for 30 seconds, and if they did decide to validate an employee's education quality, they could judge it on a site like US News and World (regardless of how flawed that may be). As that doesn't exist for bootcamps, there's no reputation gained from attending a bootcamp.

### They're Expensive and Predatory

In general, the cost of a bootcamp can be upwards of tens of thousands of dollars (basically near the cost of a state-school Master's degree), but without the pedigree of a traditional post-secondary education. Some of these bootcamps can also be predatory with hiding their costs through Income Sharing Agreements, as this [Twitter thread](https://twitter.com/VikParuchuri/status/1184206480762789888) shows.

### What To Do Instead of a Bootcamp

Now, I understand getting a full-time job as a data scientist after graduating can be nightmarish. (Entry-level jobs requiring 3-5 years of experience is its own rant.) I certainly didn't have a full-time job lined up upon graduating after applying for 3 months prior, and instead applied to hundreds of places, hoping to find a place willing to take a chance. It took a lot of luck, a willingness on my part to move 12 hours away to a 'less desirable' location, and having some previous experience to get my foot in the door.

The lousy entry-level job market is what these for-profit bootcamps prey on, and they exploit vulnerable people with the promises of getting them the sexiest job of the 21st century. Bootcamps say they'll help you with finding a job and mentorship, which can be very worth it to a lot of people on paper (and explains their vast popularity).

However, the main value add with a bootcamp is building up a repository of projects to share with prospective employers. These projects can be developed and hosted on a personal Github page through self-learning or created by following a certification curriculum. So, unless you have a lot of disposable income, really believe in the mentorship that a bootcamp could provide, and believe that a bootcamp can get you a job upon finishing, I would not touch one with a 100-foot pole.

## Conclusion

It's really important to know how you best learn in order to determine the best way to start or advance your data science career. Whereas for some advanced education makes sense, for others with an established career doing professional learning and certifications will be easier to swing. There are tradeoffs to every option, but in the age of the internet, you can get pretty far along just with some dedication, research skills, and strategic use of YouTube.