---
title: "2024 Blog Status Update"
author: "Amanda Park"
date: '2024-03-04'
description: 'Why I changed my blog appearance and hosting platform for 2024.'
---

If you're here somehow and saw my previous portfolio/blog site, you might be wondering what's going on. Here's what's happening:

### Where'd amanda-park.com go? Why's it amanda-park.github.io again?

In the past week, I saw a very disturbing [Reddit post](https://www.reddit.com/r/webdev/comments/1b14bty/netlify_just_sent_me_a_104k_bill_for_a_simple/) regarding Netlify and hosting websites. To give a short version of the story, websites hosted by Netlify could rack up thousands of dollars in bills for using excessive bandwidth beyond the free tier, and the Reddit post shows how this can happen (likely through DDoS attacks).

Unsurprisingly, this scared the ever-loving crap out of me, and I promptly deleted my Netlify website and account. Even if it was nice to have a dedicated domain name for my portfolio/blog site, there was no way it outweighed the risk of having a $100k+ bill thrown my way. That's why I'm back on github.io and hosting via Github Pages, and that will be the case going forward. (The domain name I had bought on Netlify and I didn't see any easy way to transfer, so I considered that a sunk cost when I nuked my account.)

### Why's the blog look different?

I could have theoretically used my previous site (built with Hugo and Blogdown in 2021) and just ported that to Github Pages. However, the site was a pain to make changes to in any meaningful manner as a result of its complexity. In the past couple of years, Quarto, my current blog platform of choice, had time to mature and make blogging much simpler than it had been previously.

While it doesn't have all the features I had in my previous platform (RIP Word Counts and Time to Read), it has enough of them and should be easily maintainable in the future. And as I've learned over the years, simple solutions are generally preferred over complex ones.

### What's next?

Right now I'm working on moving my old blog posts into this new site and fixing formatting issues/typos/etc. My blogging cadence has been very inconsistent once peak COVID passed, and I expect that to continue going forward. Blogging was a valuable lifeline for me in the era of social distancing and living alone, and I still want this site around for when I do have interesting things I might want to get out there somehow. However, I won't force it.

Thanks for reading!