---
title: 'Communication & Relationships Wiki'
author: 'Amanda Park'
date: '2024-07-28'
slug: communication
categories: ['wiki']
featured_image: ''
description: 'My synthesized notes of all the communication strategies I have learned and read about in the past few years.'
---

*Currently a WIP*

# Adaptive Communication

1. Know what type of conversation they're having
	a. Practical conversation - problem-solving
	b. Emotional conversation - empathy, not answers
	c. Social conversation - relationships, gossip
2. Proving that they're listening
	a. Ask a question and listen to response
	b. Repeat back in own words what they told you
	c. Ask your conversation partner if you got what they said correct
3. Ask a lot of the right questions
	a. Ask 10 to 20x more questions as everyone else
	b. Ask deep questions about values, beliefs, or experiences
	c. When in doubt, ask "why"
4. Aim to understand
Comprehend someone else's POV and share their own views accordingly

## 🙇 Apologizing

* Actually say you're sorry
* Own your behavior and specify what for
* Observe how your behavior impacted your partner
* Offer an explanation if needed
* Outline your plan to not do the behavior again
* Offer to listen if they need to share anything else about your behavior and to fix what's broken

## ❔ Ask Good Questions

Reflection

* Did you ever try to get away with anything when you were a kid?
* Do you ever feel lonely? If so, when?
* How have you changed as a person since you were 16?
* Do you ever think about your friends from high school? If so, when do they cross your mind?
* Has a book ever changed your life? If yes, what book was it and how did it affect you?
* Favorite book in high school, and favorite book now?
* When was the last time you danced in public?
* If you don’t look at your phone for a few hours, how do you feel? (Sleeping doesn’t count.)
* Share a memory about a place you’ve been to outside of this country. If you haven’t travelled yet, where would you want to go?
* What’s a memory that you really love?
* What’s the last thing that you took a photo of and why?
* What have you been thinking about a lot lately?
* What do you do within the first 15 minutes of being awake?
* What’s the weirdest job you’ve ever had?
* Do remember your dreams? Do you think dreams serve any purpose for you?
* When’s the last time you painted something?
* Tell a story about a time when you felt embarrassed.
* What was your first job?
* What’s a music memory that you have?
* What’s something you were nervous to try eating but really liked?
* What’s something you haven’t eaten in a really long time that you’d like to have again?
* Tell a short story about a time when your first impression was totally wrong.
* What were three songs that you loved as a teenager?
* How do you normally spend Saturday morning?
* Has any band or musician had a significant impact on your life?
* What’s something that worked out really well lately?
* What’s a time when you were really scared?
* What’s a time when you felt full of joy and happiness?
* Has a piece of art (music, art, film) ever brought you to tears?
* Tell a story about a time when you were not completely honest.
* Have you ever surprised yourself?
* Describe the first time you tasted alcohol.
* What’s one of the hardest things you’ve done, that you’re glad you did?
* What was a time during the last year when you felt the most alive?
* What’s something that’s really concerned you lately?
* How much do you know about what was happening in the world the year you were born?
* Have your values ever stopped you from doing something you wanted to do?
* Have you ever been naked in a public place?
* Favorite breakfast cereal as a kid?
* If you could relive any one year of your life, which would you pick and why?
* Describe a time when you felt really connected to or amazed by nature.
* What’s a risk you took that worked out well?
* What’s a hard decision you’ve had to make recently?
* Talk about the first time you remember leaving your hometown.
* Do you think you’ve ever made a bad decision? If so, what was it?
* What sweets did you love as a child?
* Which do you think is more important to have: a sense of purpose or a feeling of belonging?
* What are some of your favorite comfort foods?
* When you were a child, did elders in your life ever say certain sayings or proverbs about life? If so, what are one or two that you remember?
* What was a low point during this year for you? How did you handle it or move past it?
* Have you ever laughed until you cried? What do you think makes this kind of funny different from regular kinds of funny?
* Who’s a person you knew in your childhood that you still think about sometimes?
* What were some of your favorite books or stories from when you were a kid?
* If you could change one thing about today, what would it be?
* What are two things you’re grateful for that happened in the last year?
* As you’ve gotten older, have you outgrown any previously-held beliefs?
* Have you ever spoken in front of a large group of people? If yes, what did you learn from the experience?
* What are some places that you feel connected to?
* Have you ever regretted a purchase? Had something turn out to be a total waste of money?
* Have you ever been really excited to buy something? If yes, what was it?
* How do you feel about holidays?
* What are your physical boundaries?

Imagination

* If you could wake up tomorrow with two new talents or abilities, what would they be?
* What’s the scariest thing you would try if you were guaranteed to survive unscathed?
* What’s something about the natural world that fascinates you?
* If you had to go live in another country for the rest of your life, where would you pick and why?
* If you could press a button and suddenly know how to speak every language in the world OR play every instrument in the world, which would you pick?
* If you had to give up dancing or listening to live music forever, which would you pick and why?
* If you had to pick one of your senses to give up tomorrow, which would you pick, and what about it would you miss the most?
* If you had the power to control your dreams at night, would you?
* Do you think there is life anywhere else in the universe? If yes, what do you think it’s like?
* Where does creativity come from?
* Would you rather have the ability to speak every verbal language in the world, or to communicate telepathically?
* If you could create a second Earth for humans to populate, how would you make it different from this one?
* If you were going to become famous next year for something, what would you want to be famous for?
* Is there anything that you’ve done that you wish more people knew about?
* If you could artificially enhance your brain to stay faster and sharper than the average human brain, would you? This ability would persist until you die.
* If you couldn’t have a passport, would you be ok with never going to another country again, or would you try to go anyway?
* Would you rather live a life of great meaning even if it came with experiences of great sadness, or would you rather life a completely happy life that lacked any real depth?
* If you could spend one week in any future year of your choosing, which would you pick and what would you want to do?
* If you had to give up talking or touch, which would you pick and why?
* If you could choose to perpetually feel 25% less anger, anxiety, or frustration than your average level, which would you pick and why?
* If you could perpetually feel 25% more gratitude, curiosity or silliness than your average level, which would you pick and why?
* What’s a possibility that you dream of making real?
* What do you think your life would be like right now if you were living in one of the cities that interests you but that you’ve never been to?
* Can you think of ten ways to prepare and eat bananas?
* Which do you think are better, the years behind you or the ones yet to come?
* What do you think was happening in your exact location 100 years ago?
* What’s something that you think would be fun to try doing?
* Do you think animals have conscious intentional thoughts?
* What do you think the world will be like in 200 years?
* How do you think you would change if you didn’t watch any movies or read any books for the next year?
* If you found out today that you would get sudden and extreme dementia on your 80th birthday, how would that change your path, if at all?
* Do you think that what we call reality is actually real?
* Describe your dream house
* Describe your ideal neighborhood.
* Do you think there is anything positive about your brain forgetting things?
* What’s one word you want to define the next year of your life?
* If you knew you would be guaranteed success, what is something you would try doing?
* If you woke up tomorrow with the ability to speak every language on Earth, how would it change your life if at all?
* If you could change one decision you’ve made, what would it be?
* What signs can I look for to know when you aren't okay?
* What kinds of things do you wonder about?
* What would the Wikipedia article about you say happened in the next ten years of your life?
* Do you think life was better for humans before we started forming cities?
* Tell the person across from you three jobs you could imagine them doing well.
* Do you think that human existence has been a good thing for the universe?
* If you won the lottery, how do you think your life would change?
* If you had to give up one of the following forever, which would you choose and why: plumbing, motorized vehicles, or electricity
* If you had to eat dinner every night with a new stranger, what sort of conversations would you like to have?
* Imagine that you’ve just reached the top of the bestseller list for a book you’ve written. What is the book about?
* Would you rather walk on the moon, or explore the depths of the ocean?
* If you could go back in time to spend a week with one of your great-grandparents, which would you pick and why?
* How do you think your life would change if you devoted yourself to minimalism for the next ten years?
* What do you wish people knew about you?
* What would be your ideal way to spend a month of free time?
* If you were going to be interviewed on a national media program, what would you want to talk about?
* If you were going to write the lyrics to a song that you knew would become #1 on the charts, what would the topic of the song be?
* What do you think would happen if, for one week only, people were incapable of lying and everyone told the complete truth?

Identity

* What are some of the cultural pressures that people put on you based on gender/race/sexuality status?
* Do you practice self-care? If yes, what are some examples of self-care that really nourish you?
* Do you ever feel happy, content, or peaceful? If yes, when do you feel those emotions?
* If you didn’t have to work to live comfortably, what would you do with your unlimited free time?
* How do you want to be remembered when your life is over?
* What do you do with your selfies?
* Before it was possible to take pictures with a phone, when did you take self portraits?
* In what ways are you a creative person?
* What are some things that annoy the crap out of you?
* Have you ever volunteered before? If yes, what was your most recent volunteer role?
* How do you feel when you’re in a really big crowd?
* What were you like as a 16 year old? How are you similar to that child, and how are you different?
* In what ways are you weird?
* When did you first realize that you have a sense of humor?
* Do you still get excited? If no, why do you think you don’t get excited anymore? If yes, what kinds of things elicit your excitement?
* If you're angry, what do you do?
* What are two things you are really, really good at?
* If you could only do one kind of exercise for the rest of your life, what would it be?
* How comfortable are you with being the center of attention?
* What’s something you think about that other people seem to never think about?
* Are you afraid of vulnerability?
* If you were going to wake up tomorrow as another race or ethnicity than your own, which would you pick and why?
* What are two things you’re afraid of, and what’s something you can do to minimize those fears?
* What are three things that are true about you that someone can’t tell by looking at you?
* When do you feel most anxious? When do you feel most calm?
* Do you consider yourself to be creative? Why or why not?
* Would you ever call yourself an artist? Why or why not?
* Are there any personality traits or qualities that you wish you had more of?
* As you get older, are you getting more cynical or more optimistic?
* Have you ever done something kind for someone else and kept it a secret?
* When do you know that it’s time to quit something?
* Have you ever done something in front of a crowd that you were nervous to do? If yes, what was it?
* How old do you want to live to be?
* What are some of the qualities of people you admire?
* What advice would your 80-year-old self give you today?
* What were you like as a 5-year-old? How are you similar to that child, and how are you different?
* Where do you feel most at home?
* Describe who you are without using your name, job, nationality, or birthplace.
* If you could snap your fingers and get rid of one of your fears immediately, which would you pick and why?
* What is a big lesson you’ve learned in your life and how did you learn it?
* What kinds of things do you find funny?
* Do you have any core values that guide your life and how you live it?
* What are two things you’re really bad at?
* What’s your earliest memory?
* Would you rather be thought of as very charismatic or very reliable?
* Are you more introverted or extroverted? What are the reasons for your answer?
* What’s a lesson that has stuck with you since childhood?
* Has anything happened this year that’s changed you in a significant way?
* What do you think about life coaching?
* If you could have any superpower, what would it be?
* What kinds of stories do you find yourself continually drawn to?
* What are three of your best qualities?
* Is it easy or difficult to change your behaviors? Do you think you can change who you are at your core?
* What’s one thing you would change about yourself?
* What’s a capacity or strength you want to develop by this time next year?
* What are some of the qualities of people you dislike?
* Have you ever had a mentor or been a mentee? If yes, what was the experience like?

Relationships

* Would you rather your parents choose your friends or your spouse?
* How have your parents impacted your view of love and relationships?
* What do you think “falling in love” really is?
* How do you think your experience of friendship would change if you couldn’t use social media anymore?
* Do you think it’s possible to feel love for someone you’ve only ever talked to online?
* What public displays of affection do you think are appropriate?
* Would you hug a stranger? Why or why not?
* If you could pick three people to live in your city, who would you pick and why?
* What do you do when you have a crush on someone?
* If you could pick any two people to have as next door neighbors, who would you pick and why?
* Do you know your neighbors, and does it matter to you to know your neighbors?
* What qualities make you a really good partner?
* Have you ever shared something really personal with someone you didn’t know very well?
* Have you ever been in love? If yes, how did you know you were in love?
* Do you believe that there is something good in everyone?
* Do you miss anyone who is far away? If yes, who is it and why do you miss them so much?
* What is a parent’s job?
* Do you have a sense of community in your life? What’s your experience of community like these days?
* Have you ever had an experience of really feeling like you were part of a team? What was it like?
* Have you ever grown apart from a friend? If yes, how did you handle it?
* If you were hospitalized for a week, who do you think would come to visit you?
* If you were going to trade lives with any of your family members, who would you pick and why?
* What’s a question you ask other people that you wish other people would ask you?
* How do you define love?
* What are the qualities of a real, true, good friend?
* Do you have any enemies?
* If you could change anything about your family, what would it be?
* Who’s someone you have a hard time loving but you keep trying anyway?
* What do you think about online dating apps?
* Do you think you could be happy in an arranged marriage?
* Do you have as many friends as you want?
* What do you think is the best way to deal with bullies?
* What do you think about holidays like Mother's Day, Father's Day, and Valentine's Day?
* If you were going to spend next week living with any friend, who would you pick and why?
* What makes it difficult for people to open up and be genuine with each other?
* Did you have any relationship with your grandparents or great grandparents?
* Describe your ideal romantic partner.
* If you had to spend the rest of your life sharing a home with one person that you do not currently live with, who would you pick and why?
* What’s a compliment you could give to the person you’re talking to right now?
* Have you ever done something kind for a stranger? If yes, what was it?
* What’s something you apologized for recently, and why were you sorry?
* “Describe an apology that you’ve received from someone else and how their apology made you feel.”
* Has anyone ever asked you to change one of your behaviors? If yes, what was it and how did that go?
* Do you think it’s important to be friends outside of work with your coworkers?
* Do you think small talk is an effective way to get to know people?
* What’s one question that you think would make a great addition to the regular set of small talk questions?
* What are the characteristics of friendships in which you feel really connected to the other person?
* Would you rather spend the rest of your life unpartnered or in an unfulfilling partnership?
* When interacting with others, do you think you’re too tough or too soft?
* Who is an acquaintance that you think you’d really like to be better friends with?
* Do you believe in love at first sight?
* What’s something valuable you learned from an ex?
* Are you still close to the people you were friends with in high school?
* Has a teacher ever made a lasting impact on your life? If yes, how?
* If you’re in a relationship, what’s one thing you love about your partner and one thing you would change?
* If you were hospitalized for a week, who do you think would come to visit you?

Learning

* What questions have you wanted to ask me?
* Is there anything you wish that you’d had a chance to learn as a child or teenager?
* Do you actively seek out opportunities to learn new things?
* If you had to be a teacher for the rest of your life, what would you teach?
* Has a teacher ever inspired you?
* Should students have a chance to grade their teachers? If yes, what should happen to teachers based on the grades they get?
* What’s a time you were really out of your comfort zone, and what did you learn from the experience?
* What’s something that you’ve taught to someone else?
* Do you think it’s possible for someone to live a well-informed, educated life if they never read books?
* If you had to give up reading books or social media forever, which would you choose?
* Do you have any tricks to making life better?
* What’s a book that you think everyone should read?
* If you were going to go to university for 4 years starting tomorrow, what would you want to study the most?
* What have you learned from your experiences of sadness and joy?
* Are there any subjects that you wish you knew more about?
* What was your favorite subject in school and why?
* If you could only consume media (books, movies, tv, social media, etc) about one topic for the rest of your life, what topic would you pick and why?
* What are two valuable things you’ve learned this year?
* If you could only keep 3 books in your home for the rest of your life, which books would you choose?
* What was the last class you took and how did you feel about it?
* If you could never read/listen to/or watch the news again, who is the one person you would trust to keep you informed?
* If you could wake up tomorrow as the world’s foremost expert about any topic, what would you pick and why?
* If you were going to devote yourself to any entrepreneurial goal for the next ten years, what would it be?
* If you had to spend one hour a day studying a topic or practicing a skill, what would you pick and why?
* What’s something you’ve learned from observing a friend’s life?
* Who or what do you turn to when you need advice or perspective?
* What’s an adult life skill that you wish you were better at?
* What do you think about the way that children are educated in this country?
* Are you satisfied with the number of languages that you know?
* Do you think everything you learned in school was true? Why or why not?
* Tell a short story about a time you doubted your abilities and how you handled it.
* What’s the longest amount of time you’ve been silent and what did you learn from that experience?
* Describe an ideal educational environment for young children.
* Describe an ideal educational environment for teenagers.
* Describe an ideal educational environment for adults.
* What’s the longest amount of time you’ve been silent?
* If you were going to give a speech to all the teenagers in this country, what would you talk about?
* Did you learn anything in school that has proven to be useless knowledge?
* What learning styles do you identify with most:
  * Visual / Spatial
  * Aural / Auditory-Musical
  * Verbal / Linguistic
  * Physical / Kinesthetic
  * Logical / Mathematical
  * Social / Interpersonal
  * Solitary / Intrapersonal
* Have you ever quit learning something because it was too hard? If so, what was it?
* Would you rather become an expert in the topics you’re already well-versed in, or trade everything you know for set of new topics that you’d be equally well-versed in?
* Do you think that the schools you went to cared about the kids?
* What’s a lesson that life keeps trying to teach you?
* What was one of the last things you researched about on the internet or in a book?
* What are two topics you know a lot about?
* Do you prefer being a student or a teacher?
* Is there any topic that you’re glad you don’t know about, because your ignorance about that topic gives you some positive benefit?
* What’s something that you’ve put off learning about, that you intend to start learning about sometime soon?
* As you’ve gotten older, have you outgrown any previously-held beliefs?
* How do you intend to keep your brain functioning at a high level as you age?
* What’s something that you know how to cook really well? How did you learn to make it?
* If you could improve your memory for any one type of information, what would you pick and why?
* Have you learned anything in the last year that shocked you?
* What’s something that you think people would be surprised to learn about you?
* Do you have street smarts? If yes, how did you learn them?
* How well can you navigate your city without the use of maps or GPS?
	
Society

* Do you say hello and look people in the eye when you pass them on the street? Why or why not?
* Does using technology make you feel more connected or more disconnected?
* How important is it to keep up with world affairs?
* What do you think is the ultimate waste of money?
* How do you decide what parts of the news you’ll pay attention to?
* How does the society you live in reflect your personal values? How does it not?
* What do you think are over-valued and under-valued in society?
* Would you rather live in a country with no ethnic diversity or no music?
* What do you like about small talk? What do you dislike about it?
* When’s the last time you talked to a stranger about something that wasn’t small talk?
* When you’re at a party and feel kind of bored, what do you do?
* If you were going to be the leader of your country for the next five years, what would be your top priorities? (Try to focus on answering the question versus venting about the current political climate).
* If you could change anything about your neighborhood, what would you change?
* What are three things that you wish the people in your city would all start doing?
* What do you think is the biggest problem facing the planet in the future? What do you think is also our biggest hope or opportunity?
* Describe your ideal neighborhood.
* Do you think people are more connected or more isolated from each other than they were in the past?
* What do you think is overvalued in pop culture?
* What do you enjoy or appreciate from popular culture?
* What’s one practice, habit, law, or rule you think our country should adopt from another country?
* If you could make one major problem in this country vanish forever, what would you pick and why?
* What is one thing that you think should be free for all people?
* Do you think the internet has made the world a better place?
* What would it take for you to give up using the internet forever?
* Which do you think is more important to have in a society: individual self-expression or group harmony?
* Do you think our society is smarter and kinder than it was twenty years ago? Fifty years ago?
* Describe what your ideal environment for growing old would look like.
* How do you show the world what you care about?
* Does it matter to you if your clothes are made in sweatshops overseas? Why or why not?
* How do you think elections would change if candidates weren’t allowed to give speeches when they were running for office?
* What value, if any, do celebrities bring to society?
* What are three of your favorite things about the city you live in?
* Do you see more people expressing dissatisfaction or gratitude in your day to day life?
* What, if any, lies do you think are acceptable for people to tell each other?
* Do you feel free? Why or why not?
* If all your basic needs and spending money would be provided as long as you devoted your life to service, what cause would you pick and why?
* Do you think people in our society will ever be truly equal? If yes, what would it take to make that happen?
* Do you think that people should be required to give back to society in some way?
* How comfortable do you feel talking to a total stranger?
* Do you think social media has made the world better or worse?
* How would you describe the personality of your city: positive and negative?
* How a scale of 1-10 how grateful are you for the invention of the internet? Why did you choose your answer?
* What do you think are the qualities of a good leader?
* Do you think that pop music affects how people treat each other?
* Do you think that movies and TV shows make a meaningful contribution to society or not?
* What do you think is the difference between a first impression and a snap judgment? Or do you think these are the same thing?
* Do you think holidays are important for a society to have? Why or why not?
* Have you ever thrown a party and invited a bunch of your neighbors that you barely knew? Would you?
* What is one app or website that you can’t live without? What’s one that you wish would disappear forever?
* Imagine that you’re in charge of coming up with an alternative to modern-day capitalism. What would it look like?
* Do you think that being exposed to movies, TV, apps and popular music is good for children? Why or why not?
* What are three headlines you would love to see on the front page of the newspaper?
* What’s something you love about this country, and something you would change if you could?
* Do you prefer to be friends with your neighbors or not?
* If you were going to have a neighbor over for dinner, who would you pick and why?

**36 Questions that Lead to Love**

Set I

1. Given the choice of anyone in the world, whom would you want as a dinner guest?
2. Would you like to be famous? In what way?
3. Before making a telephone call, do you ever rehearse what you are going to say? Why?
4. What would constitute a “perfect” day for you?
5. When did you last sing to yourself? To someone else?
6. If you were able to live to the age of 90 and retain either the mind or body of a 30-year-old for the last 60 years of your life, which would you want?
7. Do you have a secret hunch about how you will die?
8. Name three things you and your partner appear to have in common.
9. For what in your life do you feel most grateful?
10. If you could change anything about the way you were raised, what would it be?
11. Take four minutes and tell your partner your life story in as much detail as possible.
12. If you could wake up tomorrow having gained any one quality or ability, what would it be?

Set II

13. If a crystal ball could tell you the truth about yourself, your life, the future or anything else, what would you want to know?
14. Is there something that you’ve dreamed of doing for a long time? Why haven’t you done it?
15. What is the greatest accomplishment of your life?
16. What do you value most in a friendship?
17. What is your most treasured memory?
18. What is your most terrible memory?
19. If you knew that in one year you would die suddenly, would you change anything about the way you are now living? Why?
20. What does friendship mean to you?
21. What roles do love and affection play in your life?
22. Alternate sharing something you consider a positive characteristic of your partner. Share a total of five items.
23. How close and warm is your family? Do you feel your childhood was happier than most other people’s?
24. How do you feel about your relationship with your mother?

Set III

25. Make three true “we” statements each. For instance, “We are both in this room feeling ... “
26. Complete this sentence: “I wish I had someone with whom I could share ... “
27. If you were going to become a close friend with your partner, please share what would be important for him or her to know.
28. Tell your partner what you like about them; be very honest this time, saying things that you might not say to someone you’ve just met.
29. Share with your partner an embarrassing moment in your life.
30. When did you last cry in front of another person? By yourself?
31. Tell your partner something that you like about them already.
32. What, if anything, is too serious to be joked about?
33. If you were to die this evening with no opportunity to communicate with anyone, what would you most regret not having told someone? Why haven’t you told them yet?
34. Your house, containing everything you own, catches fire. After saving your loved ones and pets, you have time to safely make a final dash to save any one item. What would it be? Why?
35. Of all the people in your family, whose death would you find most disturbing? Why?
36. Share a personal problem and ask your partner’s advice on how he or she might handle it. Also, ask your partner to reflect back to you how you seem to be feeling about the problem you have chosen.

**Chuck Klosterman's 23 Questions**

1. Let us assume you met a rudimentary magician. Let us assume he can do five simple tricks—he can pull a rabbit out of his hat, he can make a coin disappear, he can turn the ace of spades into the Joker card, and two others in a similar vein. These are his only tricks and he can't learn any more; he can only do these five. HOWEVER, it turns out he's doing these five tricks with real magic. It's not an illusion; he can actually conjure the bunny out of the ether and he can move the coin through space. He's legitimately magical, but extremely limited in scope and influence.
Would this person be more impressive than Albert Einstein?
2. Let us assume a fully grown, completely healthy Clydesdale horse has his hooves shackled to the ground while his head is held in place with thick rope. He is conscious and standing upright, but completely immobile. And let us assume that—for some reason—every political prisoner on earth (as cited by Amnesty International) will be released from captivity if you can kick this horse to death in less than twenty minutes. You are allowed to wear steel-toed boots.
Would you attempt to do this?
3. Let us assume there are two boxes on a table. In one box, there is a relatively normal turtle; in the other, Adolf Hitler's skull. You have to select one of these items for your home. If you select the turtle, you can't give it away and you have to keep it alive for two years; if either of these parameters are not met, you will be fined 999 dollars by the state. If you select Hitler's skull, you are required to display it in a semi-prominent location in your living room for the same amount of time, although you will be paid a stipend of 120 per month for doing so. Display of the skull must be apolitical.
Which option do you select?
4. Genetic engineers at Johns Hopkins University announce that they have developed a so-called "super gorilla." Though the animal cannot speak, it has a sign language lexicon of over twelve thousand words, an I.Q. of almost 85, and—most notably—a vague sense of self-awareness. Oddly, the creature (who weighs seven hundred pounds) becomes fascinated by football. The gorilla aspires to play the game at its highest level and quickly develops the rudimentary skills of a defensive end. ESPN analyst Tom Jackson speculates that this gorilla would be "borderline unblockable" and would likely average six sacks a game (although Jackson concedes the beast might be susceptible to counters and misdirection plays). Meanwhile, the gorilla has made it clear he would never intentionally injure any opponent.
You are commissioner of the NFL: Would you allow this gorilla to sign with the Oakland Raiders?
5. You meet your soul mate. However, there is a catch: Every three years, someone will break both of your soul mate's collarbones with a Crescent wrench, and there is only one way you can stop this from happening: You must swallow a pill that will make every song you hear—for the rest of your life—sound as if it's being performed by the band Alice in Chains. When you hear Creedence Clearwater Revival on the radio, it will sound (to your ears) like it's being played by Alice in Chains. If you see Radiohead live, every one of their tunes will sound like it's being covered by Alice in Chains. When you hear a commercial jingle on TV, it will sound like Alice in Chains; if you sing to yourself in the shower, your voice will sound like deceased Alice vocalist Layne Staley performing a capella (but it will only sound this way to you).
Would you swallow the pill?
6. At long last, someone invents "the dream VCR." This machine allows you to tape an entire evening's worth of your own dreams, which you can then watch at your leisure. However, the inventor of the dream VCR will only allow you to use this device of you agree to a strange caveat: When you watch your dreams, you must do so with your family and your closest friends in the same room. They get to watch your dreams along with you. And if you don't agree to this, you can't use the dream VCR.
Would you still do this?
7. Defying all expectation, a group of Scottish marine biologists capture a live Loch Ness Monster. In an almost unbelievable coincidence, a bear hunter in the Pacific Northwest shoots a Sasquatch in the thigh, thereby allowing zoologists to take the furry monster into captivity. These events happen on the same afternoon. That evening, the president announces he may have thyroid cancer and will undergo a biopsy later that week.
You are the front page editor of The New York Times: What do you play as the biggest story?
8. You meet the perfect person. Romantically, this person is ideal: You find them physically attractive, intellectually stimulating, consistently funny, and deeply compassionate. However, they have one quirk: This individual is obsessed with Jim Henson's gothic puppet fantasy The Dark Crystal. Beyond watching it on DVD at least once a month, he/she peppers casual conversation with Dark Crystal references, uses Dark Crystal analogies to explain everyday events, and occasionally likes to talk intensely about the film's "deeper philosophy."
Would this be enough to stop you from marrying this individual?
9. A novel titled Interior Mirror is released to mammoth commerical success (despite middling reviews). However, a curious social trend emerges: Though no one can prove a direct scientific link, it appears that almost 30 percent of the people who read this book immediately become homosexual. Many of these newfound homosexuals credit the book for helping them reach this conclusion about their orientation, despite the fact that Interior Mirror is ostensibly a crime novel with no homoerotic content (and was written by a straight man).
Would this phenomenon increase (or decrease) the likliehood of you reading this book?
10. This is the opening line of Jay McInerney's Bright Lights, Big City: "You are not the kind of guy who would be in a place like this at this time of the morning." Think about that line in the context of the novel (assuming you've read it). Now go to your CD collection and find Heart's Little Queen album (assuming you own it). Listen to the opening riff to "Barracuda."
Which of these two introductions is a higher form of art?
11. You are watching a movie in a crowded theater. Though the plot is mediocre, you find yourself dazzled by the special effects. But with twenty minutes left in the film, you are struck with an undeniable feeling of doom: You are suddenly certain your mother has just died. There is no logical reason for this to be true, but you are certain of it. You are overtaken with the irrational metaphysical sense that—somewhere—your mom has just perished. But this is only an intuitive, amorphous feeling; there is no evidence for this, and your mother has not been ill.
Would you immediately exit the theater, or would you finish watching the movie?
12. You meet a wizard in downtown Chicago. The wizard tells you he can make you more attractive if you pay him money. When you ask how this process works, the wizard points to a random person on the street. You look at this random stranger. The wizard says, "I will now make them a dollar more attractive." He waves his magic wand. Ostensibly, this person does not change at all; as far as you can tell, nothing is different. But—somehow—this person is suddenly a little more appealing. The tangible difference is invisible to the naked eye, but you can't deny that this person is vaguely sexier. This wizard has a weird rule, though—you can only pay him once. You can't keep giving him money until you're satisfied. You can only pay him one lump sum up front.
How much cash do you give the wizard?
13. Every person you have ever slept with is invited to a banquet where you are the guest of honor. No one will be in attendance except you, the collection of your former lovers, and the catering service. After the meal, you are asked to give a fifteen-minute speech to the assembly.
What do you talk about?
14. For reasons that cannot be explained, cats can suddenly read at a twelfth-grade level. They can't talk and they can't write, but they can read silently and understand the text. Many cats love this new skill, because they now have something to do all day while they lay around the house; however, a few cats become depressed, because reading forces them to realize the limitations of their existence (not to mention the utter frustration of being unable to express themselves).
This being the case, do you think the average cat would enjoy Garfield, or would cats find this cartoon to be an insulting caricature?
15.You have a brain tumor. Though there is no discomfort at the moment, this tumor would unquestionably kill you in six months. However, your life can (and will) be saved by an operation; the only downside is that there will be a brutal incision to your frontal lobe. After the surgery, you will be significantly less intelligent. You will still be a fully functioning adult, but you will be less logical, you will have a terrible memory, and you will have little ability to understand complex concepts or difficult ideas. The surgery is in two weeks.
How do you spend the next fourteen days?
16. Someone builds and optical portal that allows you to see a vision of your own life in the future (it's essentially a crystal ball that shows a randomly selected image of what your life will be like in twenty years). You can only see into this portal for thirty seconds. When you finally peer into the crystal, you see yourself in a living room, two decades older than you are today. You are watching a Canadian football game, and you are extremely happy. You are wearing a CFL jersey. Your chair is surrounded by books and magazines that promote the Canadian Football League, and there are CFL pennants covering your walls. You are alone in the room, but you are gleefully muttering about historical moments in Canadian football history. It becomes clear that—for some unknown reason—you have become obsessed with Canadian football. And this future is static and absolute; no matter what you do, this future will happen. The optical portal is never wrong. This destiny cannot be changed.
The next day, you are flipping through television channels and randomly come across a pre-season CFL game between the Toronto Argonauts and the Saskatchewan Roughriders. Knowing your inevitable future, do you now watch it?
17. You are sitting in an empty bar (in a town you've never before visited), drinking Bacardi with a soft-spoken acquaintance you barely know. After an hour, a third individual walks into the tavern and sits by himself, and you ask your acquaintance who the new man is. "Be careful of that guy," you are told. "He is a man with a past." A few minutes later, a fourth person enters the bar; he also sits alone. You ask your acquaintance who this new individual is. "Be careful of that guy, too," he says. "He is a man with no past."
Which of these two people do you trust less?
18. You have won a prize. The prize has two options, and you can choose either (but not both). The first option is a year in Europe with a monthly stipend of $2,000. The second option is ten minutes on the moon.
Which option do you select?
19. Your best friend is taking a nap on the floor of your living room. Suddenly, you are faced with a bizarre existential problem: This friend is going to die unless you kick them (as hard as you can) in the rib cage. If you don't kick them while they slumber, they will never wake up. However, you can never explain this to your friend; if you later inform them that you did this to save their life, they will also die from that. So you have to kick a sleeping friend in the ribs, and you can't tell them why.
Since you cannot tell your friend the truth, what excuse will you fabricate to explain this (seemingly inexplicable) attack?
20. For whatever the reason, two unauthorized movies are made about your life. The first is an independently released documentary, primarily comprised of interviews with people who know you and bootleg footage from your actual life. Critics are describing the documentary as "brutally honest and relentlessly fair." Meanwhile, Columbia Tri-Star has produced a big-budget biopic of your life, casting major Hollywood stars as you and all your acquaintances; though the movie is based on actual events, screenwriters have taken some liberties with the facts. Critics are split on the artistic merits of this fictionalized account, but audiences love it.
Which film would you be most interested in seeing?
21. Imagine you could go back to the age of five and relive the rest of your life, knowing everything that you know now. You will reexperience your entire adolescence with both the cognitive ability of an adult and the memories of everything you've learned form having lived your life previously.
Would you lose your virginity earlier or later than you did the first time around (and by how many years)?
22. You work in an office. Generally, you are popular with your coworkers. However, you discover that there are currently two rumors circulating the office gossip mill, and both involve you. The first rumor is that you got drunk at the office holiday party and had sex with one of your married coworkers. This rumor is completely true, but most people don't believe it. The second rumor is that you have been stealing hundreds of dollars of office supplies (and then selling them to cover a gambling debt). This rumor is completely false, but virtually everyone assumes it is factual.
Which of these two rumors is most troubling to you?
23. Consider this possibility:
  a. Think about deceased TV star John Ritter.
  b. Now, pretend Ritter had never become famous. Pretend he was never affected by the trappings of fame, and try to imagine what his personality would have been like.
  c. Now, imagine that this person—the unfamous John Ritter—is a character in a situation comedy.
  d. Now, you are also a character in this sitcom, and the unfamous John Ritter character is your sitcom father.
  e. However, this sitcom is actually your real life. In other words, you are living inside a sitcom: Everything about our life is a construction, featuring the unfamous John Ritter playing himself (in the role of your TV father). But this is not a sitcom. This is your real life. How would you feel about this?

## 😎 Assertiveness

Assertiveness is communicating and expressing your thoughts, feelings, and opinions in a way that makes your views and needs clearly understood by others, without putting down their thoughts, feelings, or opinions. Assertiveness is the ability to express our thoughts and feelings openly in an Honest, Appropriate, Respectful and Direct way. It can be HARD to do, but it gets easier with practice. In assertive communication both individuals are considered to be equally important.

Signs of assertiveness:

* Having dignity and self-respect
* Saying NO when justified without feeling guilty
* Expressing your feelings
* Asking for what you want directly
* Feeling good about yourself
* Being able to change your mind
* Negotiating and reaching compromises when conflict exists
* Being able to make mistakes
* Ability to ask for help
  * 1 to 2 sentence summary of the situation
  * Show how you've taken responsibility for the situation
  * Be very specific with your ask for help (one or two things at most)
  * Can do it this way: I’m new at X, can you help me?

## ⭐ Charisma

Charisma involved projecting 3 highly desirable qualities:

* Mindfulness shows they are regarding you with their full attention.
* Authority shows they have the ability to influence others and make your life better.
* Goodwill shows they’re likely to treat you well.

Charisma is a combination of conviction, energy, and presentation, and they generally believe:

1. I'm okay. I will be okay. 
2. I care more about my character than the opinion of others.
3. I have impeccable integrity.
4. I don't need to convince people.
5. I have a purpose and I share it
6. I break solemnity and has fun
7. I broach taboo topics
8. I demonstrate clear boundaries
9. I break down physical barriers
10. I praise liberally
11. I show when I'm nervous, pissed, or hurt
12. I reveal my flaws

How to be more charismatic:

1. Take control of your interactions and play by your social rules
	a. Don't socialize in ways that drain you
	b. Go where you thrive, avoid where you survive
	c. Say no so that you have energy to say yes
2. Make powerful first impression by nonverbally hacking all three levels of trust
	a. Use your hands
	b. Use confident body language
	c. Make eye contact
3. Use unique talking points, don't fall into basic small talk
	a. Abandon social scripts
	b. Find good topics that get people talking
	c. Use people's names, ask unique questions, and bring up novel topics
4. Bring out best in people by highlighting their strengths
	a. Listen with purpose and search for the good
	b. Give people reason to remember you
	c. Expecting the worst will bring the worst
5. Find and follow threads of similarity to be more socially attractive
	a. Threads include
		i. Mutual contacts
		ii. Context of hangout
		iii. Interests
	b. Go deeper by asking 5 whys
6. Read body language and microexpressions on people's faces
7. Understand people's personalities in terms of the Big 5
8. Understand 5 love languages and how they apply to making another person feel valued
9. Think in terms of primary values 
	a. Values include:
		i. Love
		ii. Service
		iii. Status
		iv. Money
		v. Goods
		vi. Information
10. Tell good stories
	a. Have a hook, struggle, and vivid words
		1. Storytelling
		a. Lay out the emotional path of the story
		b. Determine the climax
		c. The development to set up the climax
		d. What is the hook to the story?
	b. Voice
		a. Use of filler words and/or silence
		b. Control of cadence (talking quickly/slowly)
		c. Loudness
		d. Range of tonality (monotone?)
		e. Effusiveness and energy
		f. Timbre (high pitched or deep)
	c. Energy - In terms of inspiring people, your energy is more essential than your message; make it
		a. High
		b. Positive
		c. Supportive
		d. Excited and passionate
	d. How you feel, what you want to feel, when you want to feel it
	e. Encourage others to tell their stories by being curious
11. Empower people by giving them buy-in, control, and ownership
	a. Share mission and tie to mutual interests as much as possible
	b. Figure out how to use each person's unique skillset
	c. Step back and let others take control of the process
12. Be vulnerable in your relationships
	a. Ask for advice to harness the power of the Franklin Effect
	b. People don't notice weaknesses as much as you think, and even if they do, they humanize and offer a point of connection
13. When dealing with difficult people, name the emotion, understand the feeling, and transform the fear
14. Make people feel wanted, liked, and known
	a. Curiosity
	b. Foster a sense of belonging
	c. Reciprocate and show you enjoy being with others

## 🎬 Improv

Improv principles:

* **Yes, and** - follow along with suggestions people give to build a shared reality; don't be a buzzkill. People tend to say no out of uncertainty, but "yes, and" gives a moment to pause, listen, and create something new.
* **Embrace mistakes** - find humor in the situation and run with it; don't get caught up in shame and embarrassment. Ask "is this really the end of the world?", and typically, it's not.
* **Don't shy away from yourself** - don't feel pressured to act a certain way and be more "generic"; just be yourself and trust people will connect to specific parts of your identity.
* **Be present in your body** - Be aware of your body and stay in the present moment (clenched jaw, tensed shoulders).
* **Make room for play** - Embrace silliness, even if it feels selfish and unproductive to do so

Improv games:

* **Red ball** - people start throwing invisible balls around via eye contact and then chaos ensues
* **Ancient proverb** - everyone says one word around in a circle and tries to make it a hokey spiritual saying, when complete everyone says "om" and prays.
* **I Need 3 Things** - turn to person on right, say three things you need, next person must start first thing with your last thing you said
* **Hitchhiker** - driver is in a car in specific persona. Hitchhiker shows up with thumb up and joins car with new persona, and rest of the car adapts. Car fills up to 4 and then when the 5th hitchhiker shows up the driver makes an excuse to leave and everyone shifts
* **A-B-A** - person A says line to start scene, person B reacts, person A finishes scene
* **Sync** - think of a word and two words that can be used to describe that word (can't have part of the word in it, hyphens, or other obvious tells)
* **Gibberish** - two people act out a scene in a non-specific location (ex: on a boat) talking in gibberish, and two other people translate what is happening in the scene
* **Hero/Villain** - in a larger group of people, choose one person to be a hero and another to be the villain. Your goal is to protect the hero from the villain by staying in between them. Variation on this game is to stay equidistant from both
* **Freeze** - everyone in a group walks around at random, freezing when one person stops moving, and only restarting once everyone has stopped. Variation includes jumping when another person jumps.

## 👂 Listening

Do:

* Be attentive and tune into what the other person is saying; use short verbal affirmations and nonverbal cues (nod, smile, maintain eye contact, avoiding distractions) to do this
* Stay curious
* Make understanding a goal
* Confirm what you heard with the speaker to see if you got it right; paraphrasing is a good way to do this
* Repair if you interrupt, get distracted, become defensive, or misunderstand
* Ask clarifying, specific, and/or open ended questions
* Be aware of how much time you spend talking in the conversation
* Inhabit the role of a passenger on the speaker's train of thought
* Recall previously shared information and share similar experiences when appropriate
* Practice 2Q1U - Ask two questions of a person, and then give one detail about yourself
* Focus on active-constructive responses, not passive or destructive responses

Don't:

* Plan what you're going to say next
* Offer unsolicited advice or "fix" things
* Split focus between speaker and something else
* Try to finish or anticipate what the speaker is saying
* Take what the other person is saying personally and become defensive
* Completely shut down your own reaction
* Mind-reading
* Filtering and ignoring what's not relevant
* Judging other person's actions
* Daydreaming
* Debating and Arguing
* Insistence on being right
* Derailing when the topic is uncomfortable
* Placating immediately to other person's needs


## 🤝 Negotiation

* "Stop trying to get everyone to agree - when you need everyone to agree the least agreeable person has all the power"

### Ackerman Negotiation Technique

* Set your target price (your goal).
* Set your first offer at 65 percent of your target price.
* Calculate three raises of decreasing increments (to 85, 95, and 100 percent).
* Use lots of empathy and different ways of saying “No” to get the other side to counter before you increase your offer.
* When calculating the final amount, use precise, nonround numbers like, say, 37,893 rather than 38,000. It gives the number credibility and weight.
* On your final number, throw in a nonmonetary item (that they probably don’t want) to show you’re at your limit.

## 🪄 Persuasion

* Reciprocity
  * Present a small gift before asking a request
	* Offer ludicrous request, then offer a more reasonable one (rejection-then-retreat tactic)
* Commitment/Consistency
	* Make decisions for a reason; not reasons for a decision
* Social proof
	* Deciding what's correct based on what others think is correct
	* Why do you do something regardless of everyone else doing it?
* Liking
	* More likely to comply with requests from people we like than those we don't know/dislike
* Authority 
	* Comply with requests from authority
	* Assess authority figure's credentials and relevance of credentials
* Scarcity
	* Finding things more appealing with limited availability - loss aversion
  * Want things because of their intrinsic value, not because of their rarity or status

### Changing Minds

Three approaches; here is approach 1:

1) Ask if someone is interested in discussing the issue, and establish rapport.
2) Ask how strongly they feel about the issue on a scale of 1-10.
3) Share a story about someone affected by the issue (whether it’s you or a third party doesn’t seem to matter).
4) Ask for a number rating again.
5) Ask why the number feels right to them.
6) Repeat their reasoning back in their own words, ask if that sounds right, repeat until they are satisfied.
7) Ask if there was a time before they felt that way, and if so, how did they arrive at their current position?
8) Listen, summarize, repeat.
9) Briefly share your personal story about how you reached your position, without arguing.
10) Ask for a final rating and wrap up.

Approach 2 (street epistemology):

1) Establish rapport, ask for consent to explore the person’s reasoning.
2) Ask them for a factual claim.
3) Repeat back in your own words until they’re satisfied with your summary.
4) Clarify their definitions, and use their definitions, not yours.
5) Ask for a numerical rating of their confidence in the claim.
6) Ask why they hold that level of confidence.
7) Ask what method they’ve used to judge the quality of their reasons, and focus the conversation on exploring their method.
8) Listen, summarize, repeat.
9) Wrap up.

Approach 3:

1) Build rapport, ask for consent to explore the person’s reasoning.
2) Ask where the person is on the issue on a scale of 1-10.
3) If they’re at 1, ask: why would other people be higher on the scale? If above 1, ask: why not lower?
4) Summarize the person’s reasons in your own words until they’re satisfied that you’ve gotten it.

# Maladaptive Communication

## 💭 Co-Rumination

When people talk together about their problems, how bad those problems are, why they’re occurring, and how terrible it’s making them feel.
* people sometimes overestimate how much their friends want to be dwelling on the negative
* Co-rumination is so socially reinforcing, but may actually weaken our emotion regulation capacity
* Is unusual for its apparent positive features, such as boosting intimacy with others

If you find yourself ruminating a lot on your own after seeing a certain person, that could be another sign that the relationship is getting co-rumination heavy

## 🤔 Poor Expectations

* "In relationships we often find ourselves failing tests we didn't even know we were taking"
* “unexpressed expectation is premeditated resentment”
* “Stop going to the hardware store for bread.”
* ‘You can’t expect everyone to get it when you have been doing it for 25 years and they have been doing it for a month. Expect less from them’

# Maladaptive Relationship Strategies

## 🐺 Avoidance / Counterdependency

Can also be known as fear of intimacy or an avoidant attachment style. A counterdependent person keeps people at an emotional distance. They require a lot of time and space to themselves and are extremely independent. Can inadvertently push people away when they become close to someone else as vulnerability terrifies them.

Types of avoidance:

* **Overt avoidance** - people don’t show up to events because they are too uncomfortable.    
  * When people invite you out, and you don’t show up, they’re less likely to invite you out again; they don’t know you might be anxious and instead will take your actions to mean that you’re not interested in them (people assume rejection easily, we’ve found). 
* **Covert avoidance** - showing up physically but checking out mentally. It is getting to the event but failing to engage with others, not making eye contact, talking really fast, and/or messing with your phone. 

Signs of avoidance:

* **Over-intellectualization**
  * Left-brain oriented (very logical)
  * Lack of interoception, chronic muscle tension
  * Over-rely on self-regulation (routines, things, or activities) and under-rely on co-regulation
  * Processing emotions is less important than understanding why things happen the way they did
  * Difficulty recognizing personal needs and self-regulating emotions
  * Push away feeling with humor and disguise self-hatred with self-deprecating humor
* **Social difficulties**
  * Constant feelings of loneliness; isolated sense of self
  * Might have different personalities for different people to avoid being "seen"
  * Difficulty with eye contact
  * Perfectionistic tendencies, high standards, hard on themselves
  * Overwhelming need to be "seen"
* **Emotionally distant**
  * Difficulty being vulnerable, and quickly feeling overwhelmed when people are vulnerable
  * Inability to ask for help, and discomfort accepting help from others
  * Disinterest in the lives of others 
  * Preference for doing things yourself
  * Get low rewards from and expect very little from relationships
  * Emotionally regulate by themselves and not with others; tends to be autoregulating (more zoning/tuning out to dissociate from internal state than tuning into and working with internal state)
  * Fearful of being close to others; pushing people away when things become too serious
  * Deactivation - strong emotional charge causes a person to withdraw or shutdown from relationships. Done as a way to stay safe and avoid further hurt. Triggers thoughts like "I shouldn't be here" or "This person doesn't care for me".
  * Faux vulnerability - sharing facts of a situation but not their thoughts or feelings. 

Causes of avoidance:

* Isolation - being left alone a lot in childhood, limited face to face time with caregivers
* Lack of Presence - caregivers aren't present enough; even if physically present they may not be emotionally and psychologically present
* Task-Based Presence - caregivers present only when teaching them something. Kids inherit belief of "I’m here for you, but only if you’re practical or functional."
* Absence of Touch - lack of touch in childhood from caregivers leads to "skin hunger" and avoidant tendencies 
* Emotional Neglect - consistent nonresponsiveness to emotional needs from caregivers; see Jonice Webb's work for more
* Expressive Dissonance - caregiver's body language doesn't match emotions, causing kids to have difficulty understanding and sending appropriate social cues
* Disrupted Engagement - either child or caregiver do not have secure attachment stimulated
* Rejection - being outright rejected by caregivers in some form

Needs of an avoidant:

* Lower emotional demand; fear of being emotionally smothered
  * Consistency, safety, kindness, support, freedom
* Analytical stimulation
* Constant learning
* Validation and feedback

Manage:

* Social Growth
  * Relax boundaries with people that are safe
  * Practice sharing details of your life with others
  * Tell people how they made you feel, articulate feelings and needs
  * Ask for help, and accept help if someone offers
  * Become more dependent and let people in more
  * Focus on others
* Strategies
  * Create a daily ritual of checking in on your feelings, whether it be through journaling, meditation, or socializing.
  * Explore body-based movements like yoga
  * Remember emotions are temporary; be with your breath when they are intense
  * Practice compassion for childhood self and accept flaws as an adult
  * Create meaningful self-narrative
    * Release from self-imposed prison - what do you need to do to earn self-respect so you can stop tormenting yourself?

## 🧩 Codependency

Codependency is the inverse of counterdependency, and related to an an anxious-preoccupied attachment style. They often have meaningful relationships but struggle to be independent. They have strong needs for connection, emotional support, community, and human interaction.

Signs of codependency:

* Struggling to self-soothe
  * Needing lots of reassurance
  * Craving closeness
  * Sensitive and hyper-vigilant to emotional unavailability
* Poor boundaries and enmeshment
  * Overextending yourself
  * Feeling as if when something happens to other people, it's happening to you
  * Describing others' problems as if they're your own
  * Having difficulty in existing relationships without being the "rescuer"
  * Avoiding discussions about real issues or problems
  * Letting people rely on you in an unhealthy way
  * Troubleshooting problems for others before thinking of your own issues
* Tending to other people's needs and neglecting your own
  * Cleaning up other people's messes
  * Doing things for people instead of helping them do things themselves
  * Making excuses for poor behavior of others
  * Taking care of people with toxic behaviors

Fears:

* Becoming selfish
* Saying no due to belief it will jeopardize the relationship
* Being alone or abandoned
* Relationships changing
* You will see people suffering if you don't over-support them
* Needing love and approval to be safe and happy
* Feeling responsible for how other people feel and needing to solve their problems
* Needing to be perfect for others in order to gain their love and respect

Managing:

* Strengthen your sense of self (values, needs, likes, and dislikes)
* Learn grounding techniques and coming back to your body when you abandon yourself
* Set clear expectations with how you can help without doing things for them
* Co-regulate with partners in reciprocal manner and receive love from others
* Wait for others to ask for help instead of offering before they ask
* Honor commitment about what you will or will not tolerate in relationships
* Provide feedback about how other person's behaviors affect you, and be vocal about toxic behaviors you observe.
* "It sounds to me like you are trying to convince yourself to stay with your girlfriend. I'm not so sure it should be so difficult." (You shouldn't change yourself to be a better fit with someone you think is "superior")
* Therapist tips
  * “Don’t think of the relationship as over. Think of it as complete.”
  * “Your partner should enhance what you like most about yourself”
  * "Your relationship should make your life better."

## 📭 Enabling

Signs of enabling:

* Excusing the negative choices of others 
* Ignoring that someone has a problem 
* Doing things for people that they can do for themselves 
* Finding solutions for people instead of allowing them to find answers on their own 
* Offering money and resources when you can’t do so comfortably 
* Preventing people from enduring the consequences of their actions 
* Not setting boundaries around how to help others

## 😭 Victimization

* Don’t make excuses for things that you can control. 
* Decide to move forward despite what happened. 
* Let go of grudges. 
* Acknowledge that you aren’t perfect. 
* Explore what you’ve learned. 
* Practice assertiveness. 
* Stop comparing yourself with others. 
* Identify ways that you can better care for yourself. 
* Understand your feelings, and learn to express them. 
* Minimize or eliminate self-pity (it will keep you stuck). 
* Identify what you can control (own your power).


# Adaptive Relationship Strategies

## 🧱 Boundaries

A boundary is an imaginary line that separates me from you. It separates your physical space, your feelings, needs, and responsibilities from others. Your boundaries also tell other people how they can treat you – what’s acceptable and what isn’t. Without boundaries, people may take advantage of you because you haven’t set limits about how you expect to be treated.  

Boundaries can be overly rigid or overly porous; additionally, they can be rigid in one area while porous in another. Either way, when you ignore boundaries you set with others, others think they can safely ignore your boundaries. Even though there are consequences to setting boundaries they are critical for maintaining self-respect.

Types of boundaries:

* Physical boundaries
* Mental boundaries
* Resource boundaries
* Individualistic boundaries
* Communal boundaries

Good boundaries to set:

* Prioritize what keeps you happy, healthy, and sane.
* Say no to stuff that doesn't interest you
* Let calls go to voicemail
* Wait before responding to a call, text, or email
* Inform people of a decision rather than ask for permission
* Take mental health days as needed
* Have time-boxed hangouts for people that are good in small doses only, and limit settings for hanging out otherwise
* Block people that really bother you
* Point out when people do things you like and also things that hurt you
* Don't engage in topics you don't like
* Ask for help setting boundaries, and discuss boundaries and expectations otherwise
* Don't share parts of your life with people you don't want to be close to
* You are not required to say yes to every social opportunity, especially if you are dreading it.

How to better set boundaries:

* Set boundaries earlier in a relationship rather than later, and stringent boundaries are easier to loosen than looser boundaries are to tighten
* Use the emotional bandwidth (scale of 1-10) to indicate what level of communication you can handle (mindless to heavy in terms of content)
* You are not responsible for your parents' emotional wellbeing. They are independent adults who have been on this earth for many more years than you.
* “You don’t attract the wrong people, you’re just not good at filtering out the people who aren’t good for you. It’s ok to say no.”
* “Why do you make people more comfortable when you are uncomfortable” (people pleasing and fawning)
  * Related - "don't set yourself on fire to keep others warm"
* "why are you giving your power away?"
* People pleasing should be thought of as self-abandonment
* "There is a difference between being kind and being a doormat."
* Translate negative self-talk to understand what it's really trying to tell you
* "When you let someone break your boundaries over and over again, it wasn’t them breaking your boundaries anymore. It was you breaking your boundaries."
* Having beliefs about relationships like:
  * Feeling safe saying no to others
  * Meeting your own needs if others say no to you
  * Having a strong sense of self/identity
  * Respecting yourself
  * Treating others with respect
  * Not compromising who you are to avoid rejection
  * Feeling safe asking for help and space when needed
  * Being in charge of your emotions and happiness, and letting others be responsible for theirs
  * Taking responsibility for your failures and mistakes
  * Knowing feelings and needs, and feeling safe communicating feelings and needs to others

## 💥 Conflict Management

Strategies:

* Have a clear goal for the conversation, so everyone knows what success looks like
* Maintain a neutral voice. Do not get angry or full of contempt; try to stay relaxed
* Complicate the narrative; in this society the issue is rarely simple or black and white
* Conflicts should be addressed thoughtfully, seeking mutual understanding and resolution (don't just avoid the issue).
* Watch out for anger of hope (constructive, helps resolving conflicts) vs anger of despair (destructive and harms relationships)
* “If you don’t have these problems with any other person in your life, why do you think you’re the problematic person in this one?”
* Some of my long lasting behaviors that tend to pop up when I'm under extreme distress that I feel ashamed of were once the only ways to protect myself.  My therapist suggested when I feel those patterns kick in to thank myself for trying to protect myself. Almost instantly reduces a lot of the shame. Then I'm able to think more clearly and actually use other techniques I've learned.

## 🥰 Effective Dating

**Traits to Look For**

* No active addictions to alcohol, gambling, drugs, etc.
* No unstable and untreated mental illness
* Don’t optimize for prom date, but life partner
* Look for those who are kind, loyal, reliable, growth mindset, good communicator, emotionally stable, and respectful of others, including
  * Strangers
  * Acquaintances
  * Friends
  * Family
  * Previous romantic partners
* Similar needs with autonomy-intimacy and shared values
* Secure attachment style (or at least someone working on it) - want to avoid anxious/avoidant pull
* Traits to watch out for in "jerks"
  * Breaks boundaries
  * Can't see things from other people's perspectives
  * Dangerous lack of emotional controls and presence (too intense or too detached)
* Big 5 Personality Traits (don't make these dealbreakers, but keep them in mind...)
  * Low to average neuroticism - high neuroticism leads to conflict
  * Low to average openness to experience - Novelty-seeking is associated with cheaters and less stability long-term
  * High agreeableness - low agreeableness means unwilling to compromise
    

**Using Dating Apps** 

* Our brains focus on what's measurable and easily comparable. Apps display superficial traits, making us value those traits even more.
* We think we know what we want, but we're wrong. Apps will allow filtering great matches
* Apps promote "relationshopping", searching for relationships like online shopping
* Apps make us more indecisive about whom to date
*  When we see only a rough sketch of someone, we fill in the gaps with flattering details, leading to disappointment as the person is not the fantasy

*Dating Smarter on Apps*

* Change filters
* Change swiping
* Don't go out with too many people at the same time
* Select great photos
* Smiling with teeth, standing alone, looking away from camera
* Write a thoughtful profile
* Present self accurately
* Spark conversations by being specific
* Focus on what you like, not what you don't
* Craft an opening line
* Stay in touch (set aside some time every day)
* Get to the date as quickly as possible

### First Dates

* Shift your mindset with a pre-date ritual
  * "Whether you believe you can do a thing or not, you are right"
* Choose the time and place of the date thoughtfully
  * Try sitting side by side, not with direct eye contact
  * Coffee shops feel more like networking or a job interview, try something more romantic or fun
* Opt for a creative activity
  * Find a "third object" to comment on, such as a board game, class, books, or an arcade
* Show your work
  * Plan the date near the other person's work
* Make the date playful and include humor
* Skip the small talk
* Be interested, not interesting
  * Support responses (encourage speaker to tell story) rather than shift responses (bringing it in some way back to yourself)
* Limit phone use
* End on a high note
  * Peak end rule: compliment before ending
* Use Post-Date Eight to shift to experiential mindset (and offer a second date unless the answers to these questions are consistently negative)
  * What side of me did they bring out?
  * How did my body feel during the date? Stiff, relaxed, or in-between?
  * Do I feel energized or de-energized compared to before the date?
  * Is there something about them I'm curious about?
  * Did they make me laugh?
  * Did I feel heard?
  * Did I feel attractive in their presence?
  * Did I feel captivated, bored, or something in between?

## 👋 Meeting and Befriending New People

In general, to develop fulfilling relationships, you will want the following components:

* Genuine positive regard - the other person likes you for who you are
* Self-disclosure - feeling freedom to discuss personal topics
* Instrumental aid - willingness to provide tangible support
* Similarity - seeing the world in a like-minded way
* Enjoyment - having fun in each other's company
* Agency - friends that can help you find a job or offer a summer home to stay in

Women tend to expect more of their friends in the realms of positive regard and self-disclosure, whereas men tend to expect slightly more by way of agency. However, people generally don't explain what they expect in their friendships.

Things you'll want to look for:

* Someone you don't have to pretend or fawn for; related, the ability to disagree
* A willingness to stick around when things aren't perfect
* Respect
* Feeling energized after hanging out
* Bring out the fun side and doing so because you want to, not out of fear

### Identify Limiting Beliefs

  * Some variation of "My situation won't allow this":
    * "I live in a rural town and there is no way that I can ever get social support, and I’m doomed to feel alone forever."
    * "This community won't accept me because I'm not X enough"
    * "I missed my chance to find my people since I'm no longer in college/working in an office/etc"
  * Some variation of "I'm not needed/a priority":
    * "They already have enough friends"
	* "I'm just a friendship of convenience"
	* "Online friends aren't real friends."
  * Some variation of "I'm not good enough":
    * "I don't belong here."
    * "I don't deserve friendships, I deserve abuse"
    * “If I’m not one hundred percent certain this person will accept and love me, I can’t take the risk to build trust with them.”
    
### Take Initiative and Reach Out to Others

* Go through list of contacts, determine when last in touch and reach out to:
  * Those you haven't talked to in a long time but used to get along well with
  * Who you'd like to be closer with but are afraid they wouldn't be interested
  * Who has high upside to be a good friend if the effort is put in
* Message someone you regularly interact with online
* Message people online (90% of such is just reaching out in like-minded spaces where you can send DMs) with cold messages:
  * “Hi, I think the work you’re doing is really cool. [Here’s what resonates with me and how it’s connected to my experience.] Also, I’d love to have a quick coffee date if you ever have time and would like to connect. No worries either way. Keep it up and let me know if there’s ever any way I can support you.”
* Write to a mutual friend you've always thought you'd get along with
* Put more effort into current friendships, or reconnect with decayed friendships
* Invite friends' significant others to events or ask them to invite a friend of a friend along
* Encourage yourself to make/keep friends even when being alone feels like a better plan
* After you have a chance to get to know someone a little, saying something like, “I’ve really enjoyed talking to you. I’m trying to build my friend network and I think you’re great and would love to hang out sometime. Would you be into that?” 

### Join Groups and Attend Events

* Join groups
  * Meetup
  * Classes
  * Local church
  * Identify new activities or topics you want to pursue
    * If it's a hobby you're tangentially interested in, go once or twice to see if you like it, but don't make yourself go if you hate it (ie, golf)
    * If it's a hobby you know you like, put in a lot of effort to get involved
    * If a group isn't around, start a group
    * Host group gatherings with new friends
* Go to events
  * How likely is it that I'll interact with a person at an event?
  * How likely is it that I'll enjoy myself at this event?
  * Ex: go to shows or restaurants alone
* Find a third place, which:
  * Is separate from the workplace and the home
  * Is on neutral ground (no incentive to stay)
  * Leveling place (anyone is welcome, accessible and accommodating)
  * Conversation that is lighthearted is the main activity
  * Has to be low-profile / not require spending lots of money
  * Examples:
    * Bars/pubs/taverns
    * Cafes/coffee shops
    * Parks
    * Bookshops
    * Friendly Local Game Stores (FLGS)
    * Churches
    * Libraries
    * Community centers
    * Malls
    * Recreation centers
* Focus on yourself first (fill your life with play and pursue your own goals and interests)
* Seek more rejection, not less
* Be more selective in friendships
  * “There’s nothing wrong with you, you are just picking the wrong people to be friends with”
  * "Conversations aren't all dependent on you. There's at least one other person participating."
  * Maintaining a relationship with certain people would be a service project. That I could do it if I wanted, but with the knowledge that it would be work and I wouldn’t be able to expect reciprocity. And not to take on too many service projects.
* Drop expectations of others, focus on giving to others without reciprocity
  * Related: Act on values, not perception of closeness; thinking "sometimes people are just not being good friends to me and don't care about me as much as I care about them" helps nothing

### Express Vulnerability and Authenticity

* Be vulnerable first; don't wait for the other person
* Be vulnerable first even if it's scary. Remember you're not practicing it because it's comfortable; you're doing it because it aligns with your values and highest self
  * Others won't judge you for your vulnerability as much as you think, and you might be perceived positively for doing so
* Tell others when you want to be friends with them
* Avoid oversharing/emotional dumping, as that can push others away and cause you harm. Similarly, don't keep being authentic with those that treat you poorly for doing so
* Don't feel like you need to become someone else to be liked; faking it is draining, and at its core it's a manipulative and inauthentic approach
* Offer emotional bids to signal that you want attention and connection; central to all types of relationships

### Be Generous

* Don't be generous to get someone's love, do it because you want to show your love
* Look for win-wins in generosity
* Understand the level of reciprocity in the relationship, and do not engage in mutuality where there is a major imbalance (ie, if you're always reaching out, asking for support, or the only one being vulnerable)
* What you give and expect to receive should be proportional to the depth of the friendship
* Examples:
  * Give gifts (baking, cards, money, gifts, etc)
  * Offer to do errands (chores, drive to airport, exercise, etc) or borrow objects
  * Share information that is relevant or helpful
  
### Showcase Affection

Affection involves the following:

* You feel love, appreciation, or fondness (so flattery and manipulation don’t count!)
* You act to express those feelings
* The other person interprets and welcomes your behavior as reflecting those warm feelings

Examples:

* Tell them how much they mean to you
* Compliment them
* Be happy for them
* Praise their hard work
* Develop rituals to showcase affection
* Ask how others would best like to receive affection
  
## 🛟 Psychological Safety

Psychological safety is the shared belief that a team is safe for interpersonal risk-taking. It’s about creating an environment where people feel comfortable expressing themselves, asking questions, and making mistakes without fear of punishment or humiliation.

A related concept is creative interchange, which is a process where individuals or groups share ideas, perspectives, and experiences to foster innovation, understanding, and growth. It’s like a brainstorming session where everyone’s input is valued and can lead to new insights or solutions.

## 🗣️ Regular Socializing

5-3-1 Method:

* Spending time with five different people a week. This could be anyone from your gym buddy or book club bestie to the person the next pew over at your church. 
* Nurturing three close relationships. Here, Killam is talking about maintaining the tightest bonds in your life, usually with family and dear friends. 
* Aiming for one hour of social interaction a day. "That doesn't have to be all at once. It could be 10 minutes here, 10 minutes there," Killam clarifies to BI. And feel free to combine your hanging out time with errands or other activities if you're busy. 

## 🧷 Secure Attachment

Attachment theory is an imperfect measure of relationship quality (see [here](https://www.fatherly.com/health/attachment-theory-wrong-attachment-styles-dont-matter)), but can be useful as a general framework. 

People with secure attachment tend to be consistent, available, reliable, responsive, and predictable. They generally have high self-esteem, good emotional regulation skills, and good self-development capabilities.

Experiences they generally had as a child involve consistency and reliability, but specifically:

* A sense of felt safety, promoted by parents’ consistent and reliable protection of the child from danger and threat
* A sense of being seen and known, promoted by parents’ consistent, reliable, and accurate attunement to the child
* Experience of felt comfort, promoted by consistent, reliable, and timely soothing and reassurance
* Being valued, promoted by parents’ consistent, reliable, and clear expressed delight in the child
* Support for being and becoming one's unique, best self, promoted by parents’ consistent, reliable, unconditional support and encouragement for exploration

Those of us who did not experience a securely attached childhood or who have had significant attachment insecurity from our adult relationships can still develop earned secure attachment. This can be done by making sense of your story and understanding why you did what you did to survive growing up.

Secure attachment with others:

* Being present with others
  * Put smartphone down when together
  * Prioritize regular time with partners
  * Communicate availability
* Express why someone is special and valuable
  * Flash partner the eyes
  * Practice gratitude with partner and how they are special in spoken and/or written word
  * Do activities together
* Emotionally attune to them
  * Active listening, reflect back what you've heard
  * Bring bodies into attunement
  * Ask genuinely how they're doing with genuine curiosity and a desire to truly understand, not to confirm existing beliefs
* Have rituals and routines to support the relationship
  * Have bedtime or waking rituals
  * Create standing dates and dedicate time to regular activities together
  * Celebrate birthdays, holidays, and anniversaries together
* Involves handling conflict and being able to rupture/repair well
  * Take a time-out if things get too heated
  * Don't fight over text and wait until it can be done in-person or through voice
  * Keep desire to be right in check