---
title: 'Game Design Wiki'
author: 'Amanda Park'
date: '2024-07-17'
slug: game-design
categories: ['wiki']
featured_image: ''
description: 'My synthesized notes of all the game design knowledge I have accummulated over the past few years.'
editor: 
  markdown: 
    wrap: sentence
---

*Work in progress...*

# Audiovisual

## Art

## Music

# Game Design

## Lenses

1.  Emotion
    a.  What emotions would I like my player to experience? Why?
    b.  What emotions are players (including me) having when they play now? Why?
    c.  How can I bridge the gap between the emotions players are having and the emotions I’d like them to have?
2.  Essential Experience
    a.  What experience do I want the player to have?
    b.  What is essential to that experience?
    c.  How can my game capture that essence?
3.  Venue
    a.  What type of venue best suits the game I’m trying to create?
    b.  Does my venue have special properties that will influence my game?
    c.  What elements of my game are in harmony with my venue? What elements are not?
4.  Surprise
    a.  What will surprise players when they play my game?
    b.  Does the story in my game have surprises? Do the game rules? Does the artwork? The technology?
    c.  Do your rules give players ways to surprise each other?
    d.  Do your rules give players ways to surprise themselves?
5.  Fun
    a.  What parts of my game are fun? Why?
    b.  What parts need to be more fun?
6.  Curiosity
    a.  What questions does my game put into the player’s mind?
    b.  What am I doing to make them care about these questions?
    c.  What can I do to make them invent even more questions?
7.  Endogenous Value
    a.  What is valuable to the players in my game?
    b.  How can I make it more valuable to them?
    c.  What is the relationship between value in the game and the players’ motivations?
8.  Problem-Solving
    a.  What problems does my game ask the player to solve?
    b.  Are there hidden problems to solve that arise as part of gameplay?
    c.  How can my game generate new problems so that players keep coming back?
9.  Elemental Tetrad (Mechanics, Aesthetics, Story, Technology)
    a.  Is my game design using elements of all four types?
    b.  Could my design be improved by enhancing elements in one or more of the categories?
    c.  Are the four elements in harmony, reinforcing each other and working together toward a common theme?
10. Holographic Design
    a.  What elements of the game make the experience enjoyable?
    b.  What elements of the game detract from the experience?
    c.  How can I change game elements to improve the experience?
11. Unification
    a.  What is my theme?
    b.  Am I using every means possible to reinforce that theme?
12. Resonance
    a.  What is it about my game that feels powerful and special?
    b.  When I describe my game to people, what ideas get them really excited?
    c.  If I had no constraints of any kind, what would this game be like?
    d.  I have certain instincts about how this game should be. What is driving those instincts?
13. Infinite Inspiration
    a.  What is an experience I have had in my life that I would want to share with others?
    b.  In what small way can I capture the essence of that experience and put it into my game?
14. Problem Statement
    a.  What problem, or problems, am I really trying to solve?
    b.  Have I been making assumptions about this game that really have nothing to do with its true purpose?
    c.  Is a game really the best solution? Why?
    d.  How will I be able to tell if the problem is solved?
15. 8 Filters
    a.  Artistic Impulse: Does the game feel right (to you)?
    b.  Demographics: Consider audience intended for game
    c.  Experience Design: Consider aesthetics, game balance, theme, and interest curves.
    d.  Innovation: Is the game novel?
    e.  Business and Marketing: Is this game going to be profitable?
    f.  Engineering: Is it possible to build this game?
    g.  Social/Community: Does this meet our social and community goals?
    h.  Playtesting: Do playtesters enjoy the game enough?
16. Risk Mitigation
    a.  What could keep this game from being great?
    b.  How can we stop that from happening?
17. Toy
    a.  If my game had no goal, would it be fun at all? If not, how can I change that?
    b.  When people see my game, do they want to start interacting with it, even before they know what to do? If not, how can I change that?
18. Passion
    a.  Am I filled with blinding passion about how great this game will be?
    b.  If I’ve lost the passion, can I find it again?
    c.  If the passion isn’t coming back, shouldn’t I be doing something else?
19. Player
    a.  In general, what do they like?
    b.  What don’t they like? Why?
    c.  What do they expect to see in a game?
    d.  If I were in their place, what would I want to see in a game?
    e.  What would they like or dislike about my game in particular?
20. Pleasure
    a.  What pleasures does your game give to players? Can these be improved?
    b.  What pleasures are missing from your experience? Why? Can they be added?
    c.  List of Pleasures: Anticipation, Completion, Delight in another's misfortune, Gift giving, Humor, Possibility, Pride in accomplishment, Surprise, Thrill, Triumph over adversity, Wonder
21. Flow
    a.  Does my game have clear goals? If not, how can I fix that?
    b.  Are the goals of the player the same goals I intended?
    c.  Are there parts of the game that distract players to the point they forget their goal? If so, can these distractions be reduced or tied into the game goals?
    d.  Does my game provide a steady stream of not-too-easy, not-too-hard challenges, taking into account the fact that the player’s skills may be gradually improving?
    e.  Are the player’s skills improving at the rate I had hoped? If not, how can I change that?
22. Needs
    a.  On which levels of Maslow’s hierarchy is my game operating?
    b.  Does it fill the needs of competence, autonomy, and relatedness?
    c.  How can I make my game fill more basic needs than it already does?
    d.  For the needs my game is already filling, how can it fill those needs even better?
23. Motivation
    a.  What motivations do players have to play my game?
    b.  Which motivations are most internal? Which are most external?
    c.  Which are pleasure seeking? Which are pain avoiding?
    d.  Which motivations support each other?
    e.  Which motivations are in conflict?
24. Novelty
    a.  What is novel about my game?
    b.  Does my game have novelties throughout or just at the beginning?
    c.  Do I have the right mix of the novel and the familiar?
    d.  When the novelty wears off, will players still enjoy my game?
25. Judgment
    a.  What does your game judge about the players?
    b.  How does it communicate this judgment?
    c.  Do players feel the judgment is fair?
    d.  Do they care about the judgment?
    e.  Does the judgment make them want to improve?
26. Functional Spaces
    a.  Is the space of this game discrete or continuous?
    b.  How many dimensions does it have?
    c.  What are the boundaries of the space?
    d.  Are there subspaces? How are they connected?
    e.  Is there more than one useful way to abstractly model the space of this game?
27. Time
    a.  What is it that determines the length of my gameplay activities?
    b.  Are my players frustrated because the game ends too early? How can I change that?
    c.  Are my players bored because the game goes on too long? How can I change that?
    d.  Would clocks or races make my gameplay more exciting?
    e.  Time limits can irritate players. Would I better off without time limits?
    f.  Would a hierarchy of time structures help my game? That is, several short rounds that together comprise a larger round?
28. State Machine
    a.  What are the objects in my game?
    b.  What are the attributes of the objects?
    c.  What are the possible states for each attribute?
    d.  What triggers the state changes for each attribute?
29. Secrets
    a.  What is known by the game only?
    b.  What is known by all players?
    c.  What is known by some or only one player?
    d.  Would changing who knows what information improve my game in some way?
30. Emergence
    a.  How many verbs (ie, actions) do my players have?
    b.  How many objects can each verb act on?
    c.  How many ways can players achieve their goals?
    d.  How many subjects do the players control?
    e.  How do side effects change constraints?
31. Actions
    a.  What are the basic actions in my game?
    b.  What are the strategic actions?
    c.  What strategic actions would I like to see? How can I change my game in order to make those possible?
    d.  Am I happy with the ratio of strategic to basic actions?
    e.  What actions do players wish they could do in my game that they cannot? Can I somehow enable these, either as basic or strategic actions?
32. Goals
    a.  What is the ultimate goal of my game?
    b.  Is that goal clear to players?
    c.  If there is a series of goals, do the players understand that?
    d.  Are the different goals related to each other in a meaningful way?
    e.  Are my goals concrete, achievable, and rewarding?
    f.  Do I have a good balance of short- and long-term goals?
    g.  Do players have a chance to decide on their own goals?
33. Rules
    a.  What are the foundational rules of my game? How do these differ from the operational rules?
    b.  Are there “laws” or “house rules” that are forming as the game develops? Should these be incorporated into my game directly?
    c.  Are there different modes in my game? Do these modes make things simpler, or more complex? Would the game be better with fewer modes? More modes?
    d.  Who enforces the rules?
    e.  Are the rules easy to understand, or is there confusion about them? If there is confusion, should I fix it by changing the rules or by explaining them more clearly?
34. Skill
    a.  What skills does my game require from the player?
    b.  Are there categories of skill that this game is missing?
    c.  Which skills are dominant?
    d.  Are these skills creating the experience I want?
    e.  Are some players much better at these skills than others? Does this make the game feel unfair?
    f.  Can players improve their skills with practice, leading to a feeling of mastery?
    g.  Does this game demand the right level of skill?
35. Expected Value
    a.  What is the actual chance of a certain event occurring?
    b.  What is the perceived chance?
    c.  What value does the outcome of that event have? Can the value be quantified? Are there intangible aspects of value that I am not considering?
    d.  Each action a player can take has a different expected value when I add up all the possible outcomes. Am I happy with these values? Do they give the player interesting choices? Are they too rewarding, or too punishing?
36. Randomness
    a.  What in my game is truly random? What parts just feel random?
    b.  Does the randomness give the players positive feelings of excitement and challenge, or does it give them negative feelings of hopelessness and lack of control?
    c.  Would changing my probability distribution curves improve my game?
    d.  Do players have the opportunity to take interesting risks in the game?
    e.  What is the relationship between chance and skill in my game? Are there ways I can make random elements feel more like the exercise of a skill? Are there ways I can make exercising skills feel more like risk taking?
37. Fairness
    a.  Should my game be symmetrical? Why?
    b.  Should my game be asymmetrical? Why?
    c.  Which is more important: that my game is a reliable measure of who has the most skill or that it provide an interesting challenge to all players?
    d.  If I want players of different skill levels to play together, what means will I use to make the game interesting and challenging for everyone?
38. Challenge
    a.  What are the challenges in my game?
    b.  Are they too easy, too hard, or just right?
    c.  Can my challenges accommodate a wide variety of skill levels?
    d.  How does the level of challenge increase as the player succeeds?
    e.  Is there enough variety in the challenges?
    f.  What is the maximum level of challenge in my game?
39. Meaningful choices
    a.  What choices am I asking the player to make?
    b.  Are they meaningful? How?
    c.  Am I giving the player the right number of choices? Would more make them feel more powerful? Would less make the game clearer?
    d.  Are there any dominant strategies in my game?
40. Triangularity
    a.  Do I have triangularity now? If not, how can I get it?
    b.  Is my attempt at triangularity balanced? That is, are the rewards commensurate with the risks?
41. Skill vs Chance
    a.  Are my players here to be judged (skill) or to take risks (chance)?
    b.  Skill tends to be more serious than chance: is my game serious or casual?
    c.  Are parts of my game tedious? If so, will adding elements of chance enliven them?
    d.  Do parts of my game feel too random? If so, will replacing elements of chance with elements of skill or strategy make the players feel more in control?
42. Head and Hands
    a.  Are my players looking for mindless action or an intellectual challenge?
    b.  Would adding more places that involve puzzle solving in my game make it more interesting?
    c.  Are there places where the player can relax their brain and just play the game without thinking?
    d.  Can I give the player a choice—succeed either by exercising a high level of dexterity or by finding a clever strategy that works with a minimum of physical skill?
    e.  If “1” means all physical and “10” means all mental, what number would my game get?
43. Competition
    a.  Does my game give a fair measurement of player skill?
    b.  Do people want to win my game? Why?
    c.  Is winning this game something people can be proud of? Why?
    d.  Can novices meaningfully compete at my game?
    e.  Can experts meaningfully compete at my game?
    f.  Can experts generally be sure they will defeat novices?
44. Cooperation
    a.  Cooperation requires communication. Do my players have enough opportunity to communicate? How could communication be enhanced?
    b.  Are my players friends already, or are they strangers? If they are strangers, can I help them break the ice?
    c.  Is there synergy (2 + 2 = 5) or antergy (2 + 2 = 3) when the players work together? Why?
    d.  Do all the players have the same role, or do they have special jobs?
    e.  Cooperation is greatly enhanced when there is no way an individual can do a task alone. Does my game have tasks like that?
    f.  Tasks that force communication inspire cooperation. Do any of my tasks force communication?
45. Competition vs Cooperation
    a.  If “1” is competition and “10” is cooperation, what number should my game get?
    b.  Can I give players a choice whether to play cooperatively or competitively?
    c.  Does my audience prefer competition, cooperation, or a mix?
    d.  Is team competition something that makes sense for my game? Is my game more fun with team competition or with solo competition?
46. Reward
    a.  What rewards is my game giving out now? Can it give out others as well?
    b.  Are players excited when they get rewards in my game, or are they bored by them? Why?
    c.  Getting a reward you don’t understand is like getting no reward at all. Do my players understand the rewards they are getting?
    d.  Are the rewards my game gives out too regular? Can they be given out in a more variable way?
    e.  How are my rewards related to one another? Is there a way that they could be better connected?
    f.  How are my rewards building? Too fast, too slow, or just right?
47. Punishment
    a.  What are the punishments in my game?
    b.  Why am I punishing the players? What do I hope to achieve by it?
    c.  Do my punishments seem fair to the players? Why or why not?
    d.  Is there a way to turn these punishments into rewards and get the same or a better effect?
    e.  Are my strong punishments balanced against commensurately strong rewards?
48. Simplicity vs Complexity
    a.  What elements of innate complexity do I have in my game?
    b.  Is there a way this innate complexity could be turned into emergent complexity?
    c.  Do elements of emergent complexity arise from my game? If not, why not?
    d.  Are there elements of my game that are too simple?
49. Elegance
    a.  What are the elements of my game?
    b.  What are the purposes of each element? Count these up to give the element an “elegance rating.”
    c.  For elements with only one or two purposes, can some of these be combined into each other or removed altogether?
    d.  For elements with several purposes, is it possible for them to take on even more?
50. Character
    a.  Is there anything strange in my game that players talk about excitedly?
    b.  Does my game have funny qualities that make it unique?
    c.  Does my game have flaws that players like?
51. Imagination
    a.  What must the player understand to play my game?
    b.  Can some element of imagination help them understand that better?
    c.  What high-quality, realistic details can we provide in this game?
    d.  What details would be low quality if we provided them? Can imagination fill the gap instead?
    e.  Can I give details that the imagination will be able to reuse again and again?
    f.  What details I provide inspire imagination?
    g.  What details I provide stifle imagination?
52. Economy
    a.  How can my players earn money? Should there be other ways?
    b.  What can my players buy? Why?
    c.  Is money too easy to get? Too hard? How can I change this?
    d.  Are choices about earning and spending meaningful ones?
    e.  Is a universal currency a good idea in my game, or should there be specialized currencies?
53. Balance
    a.  Does my game feel right? Why or why not?
54. Accessibility
    a.  How will players know how to begin solving my puzzle or playing my game? Do I need to explain it, or is it self-evident?
    b.  Does my puzzle or game act like something they have seen before? If it does, how can I draw attention to that similarity. If it does not, how can I make them understand how it does behave?
    c.  Does my puzzle or game draw people in and make them want to touch it and manipulate it? If not, how I can I change it so that it does?
55. Visible Progress
    a.  What does it mean to make progress in my game or puzzle?
    b.  Is there enough progress in my game? Is there a way I can add more interim steps of progressive success?
    c.  What progress is visible, and what progress is hidden? Can I find a way to reveal what is hidden?
56. Parallelism
    a.  Are there bottlenecks in my design where players are unable to proceed if they cannot solve a particular challenge? If so, can I add parallel challenges for a player to work on when this challenge stumps them?
    b.  If parallel challenges are too similar, the parallelism offers little benefit. Are my parallel challenges different enough from each other to give players the benefit of variety?
    c.  Can my parallel challenges be connected somehow? Is there a way that making progress on one can make it easier to solve the others?
57. Pyramid
    a.  Is there a way all the pieces of my puzzle can feed into a singular challenge at the end?
    b.  Big pyramids are often made of little pyramids—can I have a hierarchy of ever more challenging puzzle elements, gradually leading to a final challenge?
    c.  Is the challenge at the top of my pyramid interesting, compelling, and clear? Does it make people want to work in order to get to it?
58. Puzzle
    a.  What are the puzzles in my game?
    b.  Should I have more puzzles, or less? Why?
    c.  Do I have any incongruous puzzles? How can I better integrate them into the game? (Use Lens #49, Elegance, to help do this).
59. Control
    a.  When players use the interface, does it do what is expected? If not, why not?
    b.  Intuitive interfaces give a feeling of control. Is your interface easy to master or hard to master?
    c.  Do your players feel they have a strong influence over the outcome of the game? If not, how can you change that?
    d.  Feeling powerful = feeling in control. Do your players feel powerful? Can you make them feel more powerful somehow?
60. Physical Interface
    a.  What does the player pick up and touch? Can this be made more pleasing?
    b.  How does this map to the actions in the game world? Can the mapping be more direct?
    c.  If you can’t create a custom physical interface, what metaphor are you using when you map the inputs to the game world?
    d.  How does the physical interface look under the Lens of the Toy?
    e.  How does the player see, hear, and touch the world of the game? Is there a way to include a physical output device that will make the world become more real in the player’s imagination?
61. Virtual Interface
    a.  What information does a player need to receive that isn’t obvious just by looking at the game world?
    b.  When does the player need this information? All the time? Only occasionally? Only at the end of a level?
    c.  How can this information be delivered to the player in a way that won’t interfere with the player’s interactions with the game world?
    d.  Are there elements of the game world that are easier to interact with using a virtual interface (like a pop-up menu, for instance) than they are to interact with directly?
62. Transparency
    a.  What are the player’s desires? Does the interface let the players do what they want?
    b.  Is the interface simple enough that with practice, players will be able to use it without thinking?
    c.  Do new players find the interface intuitive? If not, can it be made more intuitive, somehow? Would allowing players to customize the controls help or hurt?
    d.  Does the interface work well in all situations, or are there cases (near a corner, going very fast, etc.) when it behaves in ways that will confuse the player?
    e.  Can players continue to use the interface well in stressful situations, or do they start fumbling with the controls or missing crucial information? If so, how can this be improved?
    f.  Does anything confuse players about the interface? On which of the six interface arrows is it happening?
    g.  Do players feel a sense of immersion when using the interface?
    h.  What kind of virtual interface is best suited to my physical interface? Pop-up menus, for example, are a poor match for a gamepad controller.
63. Feedback
    a.  What do players need to know at this moment?
    b.  What do players want to know at this moment?
    c.  What do you want players to feel at this moment? How can you give feedback that creates that feeling?
    d.  What do the players want to feel at this moment? Is there an opportunity for them to create a situation where they will feel that?
    e.  What is the player’s goal at this moment? What feedback will help them toward that goal?
64. Juiciness
    a.  Is my interface giving the player continuous feedback for their actions? If not, why not?
    b.  Is second-order motion created by the actions of the player? Is this motion powerful and interesting?
    c.  Juicy systems reward the player many ways at once. When I give the player a reward, how many ways am I simultaneously rewarding them? Can I find more ways?
65. Primality
    a.  What parts of my game are so primal an animal could play? Why?
    b.  What parts of my game could be more primal?
66. Channels and Dimensions
    a.  What data need to travel to and from the player?
    b.  Which data are most important?
    c.  What channels do I have available to transmit these data?
    d.  Which channels are most appropriate for which data? Why?
    e.  Which dimensions are available on the different channels?
    f.  How should I use those dimensions?
67. Modes
    a.  What modes do I need in my game? Why?
    b.  Can any modes be collapsed or combined?
    c.  Are any of the modes overlapping? If so, can I put them on different input channels?
    d.  When the game changes modes, how does the player know that? Can the game communicate the mode change in more than one way?
68. Moments
    a.  What are the key moments in my game?
    b.  How can I make each moment as powerful as possible?
69. Interest Curve
    a.  If I draw an interest curve of my experience, how is it generally shaped?
    b.  Does it have a hook?
    c.  Does it have gradually rising interest, punctuated by periods of rest?
    d.  Is there a grand finale, more interesting than everything else?
    e.  What changes would give me a better interest curve?
    f.  Is there a fractal structure to my interest curve? Should there be?
    g.  Do my intuitions about the interest curve match the observed interest of the players? If I ask playtesters to draw an interest curve, what does it look like?
70. Inherent Interest
    a.  What aspects of my game will capture the interest of a player immediately?
    b.  Does my game let the player see or do something they have never seen or done before?
    c.  What base instincts does my game appeal to? Can it appeal to more of them?
    d.  What higher instincts does my game appeal to? Can it appeal to more of those?
    e.  Does dramatic change and anticipation of dramatic change happen in my game? How can it be more dramatic?
71. Beauty
    a.  What elements make up my game? How can each one be more beautiful?
    b.  Some things are not beautiful in themselves, but are beautiful in combination. How can the elements of my game be composed in a way that is poetic and beautiful?
    c.  What does beauty mean within the context of my game?
72. Projection
    a.  What is there in my game that players can relate to? What else can I add?
    b.  What is there in my game that will capture a player’s imagination? What else can I add?
    c.  Are there places in the game that players have always wanted to visit?
    d.  Does the player get to be a character they could imagine themselves to be?
    e.  Are there other characters in the game that the players would be interested to meet (or to spy on)?
    f.  Do the players get to do things that they would like to do in real life, but can’t?
    g.  Is there an activity in the game that once a player starts doing, it is hard to stop?
73. Story Machine
    a.  When players have different choices about how to achieve goals, new and different stories can arise. How can I add more of these choices?
    b.  Different conflicts lead to different stories. How can I allow more types of conflict to arise from my game?
    c.  When players can personalize the characters and setting, they will care more about story outcomes, and similar stories can start to feel very different. How can I let players personalize the story?
    d.  Good stories have good interest curves. Do my rules lead to stories with good interest curves?
    e.  A story is only good if you can tell it. Who can your players tell the story to that will actually care?
74. Obstacle
    a.  What is the relationship between the main character and the goal? Why does the character care about it?
    b.  What are the obstacles between the character and the goal?
    c.  Is there an antagonist who is behind the obstacles? What is the relationship between the protagonist and the antagonist?
    d.  Do the obstacles gradually increase in difficulty?
    e.  Some say “the bigger the obstacle, the better the story.” Are your obstacles big enough? Can they be bigger?
    f.  Great stories often involve the protagonist transforming in order to overcome the obstacle. How does your protagonist transform?
75. Simplicity and Transcendence
    a.  How is my world simpler than the real world? Can it be simpler in other ways?
    b.  What kind of transcendent power do I give to the player? How can I give even more without removing challenge from the game?
    c.  Is my combination of simplicity and transcendence contrived, or does it provide my players with a special kind of wish fulfillment?
76. Hero's Journey
    a.  Does my story have elements that qualify it as a heroic story?
    b.  If so, how does it match up with the structure of the hero’s journey?
    c.  Would my story be improved by including more archetypical elements?
    d.  Does my story match this form so closely that it feels hackneyed?
77. Weirdest Thing
    a.  What’s the weirdest thing in my story?
    b.  How can I make sure that the weirdest thing doesn’t confuse or alienate the player?
    c.  If there are multiple weird things, should I maybe get rid of, or coalesce, some of them?
    d.  If there is nothing weird in my story, is the story still interesting?
78. Story
    a.  Does my game really need a story? Why?
    b.  Why will players be interested in this story?
    c.  How does the story support the other parts of the tetrad (aesthetics, technology, gameplay)? Can it do a better job?
    d.  How do the other parts of the tetrad support the story? Can they do a better job?
    e.  How can my story be better?
79. Freedom
    a.  When do my players have freedom of action? Do they feel free at these times?
    b.  When are they constrained? Do they feel constrained at these times?
    c.  Are there any places I can let them feel more free than they do now?
    d.  Are there any places where they are overwhelmed by too much freedom?
80. Help
    a.  Within the context of the game, who is the player helping?
    b.  Can I make the player feel more connected to the characters who need help?
    c.  Can I better tell the story of how meeting game goals helps someone?
    d.  How can the helped characters show their appreciation?
81. Indirect Control
    a.  Ideally, what would I like the players to do?
    b.  Can constraints get players to do it?
    c.  Can goals get players to do it?
    d.  Can interface get players to do it?
    e.  Can visual design get players to do it?
    f.  Can game characters get players to do it?
    g.  Can music or sound get players to do it?
    h.  Is there some other method I can use to coerce players toward ideal behavior without impinging on their feeling of freedom?
    i.  Is my design inducing desires I’d rather the player not have?
82. Collusion
    a.  What do I want the player to experience?
    b.  How can the characters help fulfill this experience, without compromising their goals in the game world?
83. Fantasy
    a.  What fantasy does my world fulfill?
    b.  Who does the player fantasize about being?
    c.  What does my player fantasize about doing there?
84. World
    a.  How is my world better than the real world?
    b.  Can there be multiple gateways to my world? How do they differ? How do they support each other?
    c.  Is my world centered on a single story, or could many stories happen here?
85. Avatar
    a.  Is my avatar an ideal form likely to resonate with my players?
    b.  Does my avatar have iconic qualities that let a player project themselves into the character?
86. Character Function
    a.  What are the roles I need the characters to fill?
    b.  What characters have I already imagined?
    c.  Which characters map well to which roles?
    d.  Can any characters fill more than one role?
    e.  Do I need to change the characters to better fit the roles?
    f.  Do I need any new characters?
87. Character Traits
    a.  What traits define my character?
    b.  How do these traits manifest themselves in the words, actions, and appearance of my character?
88. Interpersonal Circumplex
    a.  Are there any gaps in the chart? Why are they there? Would it be better if the gaps were filled?
    b.  Are there “extreme characters” on the graph? If not, would it be better if there were?
    c.  Are the character’s friends in the same quadrant, or different quadrants? What if that were different?
89. Character Web
    a.  How, specifically, does each character feel about each of the others?
    b.  Are there any connections unaccounted for? How can I use those?
    c.  Are there too many similar connections? How can they be more different?
90. Status
    a.  What are the relative status levels of the characters in my game?
    b.  How can they show appropriate status behaviors?
    c.  Conflicts of status are interesting—how are my characters vying for status?
    d.  Changes of status are interesting—where do they happen in my game?
    e.  How am I giving the player a chance to express status?
91. Character Transformation
    a.  How does each of my characters change throughout the game?
    b.  How am I communicating those changes to the player? Can I communicate them more clearly, or more strongly?
    c.  Is there enough change?
    d.  Are the changes surprising and interesting?
    e.  Are the changes believable?
92. Inner Contradiction
    a.  What is the purpose of my game?
    b.  What are the purposes of each subsystem in my game?
    c.  Is there anything at all in my game that contradicts these purposes?
    d.  If so, how can I change that?
93. Nameless Quality
    a.  Does my design have a special feeling of life, or do parts of my design feel dead? What would make my design feel more alive?
    b.  Which of Alexander’s fifteen qualities does my design have?
    c.  Could it have more of them, somehow?
    d.  Where does my design feel like myself?
94. Atmosphere
    a.  Without using words, how can I describe the atmosphere of my game?
    b.  How can I use artistic content (both visual and audible) to deepen that atmosphere?
95. Spectation
    a.  Is my game interesting to watch? Why or why not?
    b.  How can I make it more interesting to watch?
96. Friendships
    a.  What kind of friendships are my players looking for?
    b.  How do my players break the ice?
    c.  Do my players have enough chance to talk to each other? Do they have enough to talk about?
    d.  When is the moment they become friends?
    e.  What tools do I give the players to maintain their friendships?
97. Expression
    a.  How am I letting players express themselves?
    b.  What ways am I forgetting?
    c.  Are players proud of their identity? Why or why not?
98. Community
    a.  What conflict is at the heart of my community?
    b.  How does architecture shape my community?
    c.  Does my game support three levels of experience?
    d.  Are there community events?
    e.  Why do players need each other?
99. Griefing
    a.  What systems in my game are easy to grief?
    b.  How can I make my game boring to grief?
    c.  Am I ignoring any loopholes?
100. Love
     -   Do I love my project? If not, how can I change that?
     -   Does everyone on the team love the project? If not, how can that be changed?
101. Team
     -   Is this the right team for this project? Why?
     -   Is the team communicating objectively?
     -   Is the team communicating clearly?
     -   Is the team comfortable with each other?
     -   Is there an air of trust and respect among the team?
     -   Is the team ultimately able to unify around decisions?
102. Documenting
     -   What do we need to remember while making this game?
     -   What needs to be communicated while making this game?
103. Playtesting
     -   Why are we doing a playtest?
     -   Who should be there?
     -   Where should we hold it?
     -   What will we look for?
     -   How will we get the information we need?
104. Technology
     -   What technologies will help deliver the experience I want to create?
     -   Am I using these technologies in ways that are foundational or decorational?
     -   If I’m not using them foundationally, should I be using them at all?
     -   Is this technology as cool as I think it is?
     -   Is there a “disruptive technology” I should consider instead?
105. Crystal Ball
     -   What will \_\_\_\_ be like two years from now? Why?
     -   What will \_\_\_\_ be like four years from now? Why?
     -   What will \_\_\_\_ be like ten years from now? Why?
106. Utopia
     -   Am I creating something that feels magical?
     -   Do people get excited just hearing about what I am making? Why or why not?
     -   Does my game advance the state of the art in a meaningful way?
     -   Does my game make the world a better place?
107. Client
     -   What does the client say he wants?
     -   What does the client think he wants?
     -   What does the client really want, deep down in his heart?
108. Pitch
     -   Why are you pitching this game to this client?
     -   What will you consider “a successful pitch”?
     -   What’s in it for the people you are pitching to?
     -   What do the people you are pitching to need to know about your game?
109. Profit
     -   Where does the money go in my game’s business model? Why?
     -   How much will it cost to produce, market, distribute, and maintain this game? Why?
     -   How much money will this game make? Why do I think that?
     -   What are the barriers to entry in the market for this game?
110. Transformation
     -   How can my game change players for the better?
     -   How can my game change players for the worse?
111. Responsibility
     -   Does my game help people? How?
112. Raven
     -   Is making this game worth my time?
113. Purpose
     -   Why am I doing this?

## Game Design Document

## Gameplay

## Mechanics

## Levels
