---
title: 'Health and Wellness Wiki'
author: 'Amanda Park'
date: '2024-07-20'
slug: health
categories: ['wiki']
featured_image: ''
description: 'My synthesized notes of all the health and wellness strategies I have learned and read about in the past few years.'
---

*Currently a WIP*

# Difficult Emotions

## 😡 Anger

Anger is what we feel when something gets in the way of what we want or disrupts the way we think things are supposed to be. It's evolution's alarm bell, so listen to what it's telling you.

Anger helps you:

* Identify needs and set boundaries
* Drives you towards your goals
* Strengthens relationships
* Discharge tension from body
* Motivates you to solve problems and injustices
* Increases optimism and creativity

Common triggers:

* Cognitive distortions like overgeneralizing, catastrophizing, and mind-reading
* Feeling like you aren't being heard
* Feeling like decisions are made unfairly
* Being anxious
* Being told to calm down
* Being interrupted mid-sentence
* Being impacted by actions without having permission
* When you're about to do something and someone tells you to do it

Managing:

* Be aware of your anger triggers and review on a regular basis. Avoid triggers when it makes sense
* Take a time-out and remove yourself from the situation; plan a time-out strategy in advance
* Know the warning signs for anger
  * Raised voice
  * Verbal insults and becoming argumentative
  * Feeling sick to stomach
  * Headaches
  * Sweating and feeling hot
  * Clenched fists or jaw
  * Pacing
  * Aggressive body language
  * Shutting down
  * Not being able to get past problem
* Use breathing techniques, diversions and distractions to mitigate hitting boiling point
  * Go for a walk
  * Take a shower or bath
  * Clean up clutter
  * Listen to calming music
  * Play a game
  * Call a friend
  * Draw or paint
* Release anger if it has come to the forefront:
  * Write or draw about situation
  * Rip paper
  * Punch a pillow
  * Scream in a car or into a pillow
  * Throw ice cubes in shower
  * Go to a rage room
  * Exercise or dance
* Keep an anger journal and reflect on emotional state prior to anger outburst, facts of the situation, what you were feeling when expressing anger
  * Pinpoint the needs underlying the emotion
* "Anger is a blocked wish."
* “How was anger expressed in your household growing up? Were you allowed to show anger?”
* Anger is the brain reacting to fear. If you’re feeling anger, take a quick pause to ask what you’re afraid of.

### ⛏️ Repressed Anger

*"People diagnosed with cancer or autoimmune disease, with chronic fatigue or fibromyalgia, or with potentially debilitating neurological conditions, are often enjoined to relax, to think positively, to lower their stress levels. All that is good advice, but impossible to carry out if one of the major sources is not clearly identified and dealt with: the internalization of anger." – from ‘When The Body Says No – The Cost of Hidden Stress’*

Repressed anger is often internalized emotional responses that were never expressed properly. It's dependent on cultural norms, but girls generally learn it is unacceptable to express anger at a young age.

Causes and triggers of repressed anger

* Having perfectionistic, people pleasing, intellectualizing, or neurotic tendencies
* Having a mental health condition or traumatic brain injury
* Using drugs or alcohol
* Being rejected for expressing anger in the past
* Low emotional intelligence
* High levels of shame

Signs of Repressed Anger

* Not feeling angry, but often feeling sad or depressed
* Overuse of sarcasm or cynicism
* Discomfort with conflict and confrontation
* Dependence on avoidance to cope
* Becoming defensive when accused of becoming angry
* Need to control many things in life
* Chronic muscle tension or headaches
* Discomfort when others share intimate emotions
* Passive-aggressiveness
* Difficulty setting boundaries, standing up for yourself, saying no
* Shutting down, avoiding people, or isolating when upset or in pain
* Being explosive when you are angry
* Complaining often when things don't go your way
* High levels of chronic stress or anxiety
* Frequent negative or self-critical thoughts
* Ignoring things that upset you rather than addressing them
* Feeling bitter, envious, resentful of others
* Feeling guilty, ashamed, or bad when you are angry

Consequences:

* Health issues (insomnia, high blood pressure, heart problems, etc)
* Mental health issues (anxiety, depression, addiction, etc)
* Poor relationships
* Numbness or apathy

Managing:

* Understand where anger is coming from
* Track anger in your body via physical sensations
* Journal
* Interrupt angry thoughts
* Find physical outlet for anger
* Meditate
* Use I-statements "I feel ___ when you ___."
* Feel your feelings

## 😰 Anxiety

Note - I'm not considering feeling anxious as the same as something like Generalized Anxiety Disorder (GAD). This is meant for more day to day anxiety people experience.

*"When you get anxious, your amygdala is activated. You can tell yourself that you're okay and even logically understand you are okay, but your amygdala isn't catching up yet. Just remember that you are okay, and it's just your amygdala needing time to adjust (10-15 minutes)."*

*“You’ll stop worrying what others think about you when you realize how seldom they do.” - David Foster Wallace*

Anxiety, simply put, is concern about the unknown and/or future. It's feeling like we’re not in control — we don’t know what’s going to happen, so we imagine the worst.

* The opposite of anxiety is not relaxation, but prosocial behavior.
* Extreme anxiety, such as a panic attack, are not physically dangerous to experience, just deeply unpleasant

Types of anxiety:

* Functional anxiety - gives important information to the brain
* Death anxiety - fear of death and dying
  * Fear of both the known and unknown
  * Coming close to death brings about growth and positive life transformation
  * Acceptance of death is not the same as giving up on life, but allows for meaning to be brought to life
* Performance anxiety - fear of faltering in front of others
* Social anxiety - fear of disapproval in social situations
  * Don't excessively monitor yourself as that gives the wrong impression to others; how you feel inside is not how you look to others
  * Remember spotlight effect - people are too self-absorbed to think about you
  * Don't tell yourself you have to perform perfectly, creates impossible standards
  * Don't use alcohol to treat social anxiety
  * Perceived inadequacies are not tied to a fundamental lack of social skills
  * For fear of missing out (FOMO):
    * Do a digital detox
    * Get more quality time in loved ones
    * Practice meditation and mindfulness
    * Journal

Manage:

* Is worrying *actually* helpful? If so, do it.
  * Will this matter in 10 minutes? 10 weeks? 10 years?
* 25% of the people you meet won’t like you, and you won’t like 25% of the people you meet. They may not be the same people. Similarly, imagine you're an orange, and some people don't like oranges. It doesn't mean the orange is flawed in any way, just means that it's not everyone's preference.
  * Similarly, “Some people are like cacti, strong and hardy. Others are like daffodils, bright and can bend in the wind. And some are like orchids. Delicate and need to be looked after but are beautiful and awe inspiring. What matters most is the environment they are grown in."
* You're not special; people are too worried about themselves to be thinking of you. Besides, it's not your business what other people think of you
  * People are gossiping about you? Let them. Your boyfriend wants to break up? Let them. Your friend doesn’t heed your advice that you think is best? Let them. People don’t agree with you? LET THEM.
  * Just because you've always needed a reason to dislike someone, that's why it hurts when someone dislikes you, but not everyone else has a reason
* Anxiety lives really well in the past and in the future. But has no place in the present. Bring yourself back to the present.
* Exposure therapy to reduce anxious feelings; don't avoid what you're afraid of. Escape and avoidance only offer short-term relief and feed anxiety in the long run
* Slower, deeper breaths
* Reframe cognitive distortions to be more realistic, threats as challenges to overcome, and treat anxiety as excitement
* Self-compassion
* Act in line with your values
* Schedule worry time, and dump out all the thoughts in your brain during this time
* A lot of anxiety can trigger depression, so taking steps to manage anxiety first (taking time off, crying, etc) can reduce the depressive episodes
* Be mindful of "anxious fixing", where you tackle small things on your to-do list as a way to avoid tackling the root cause of your anxiety.

## 🥱 Bored
 
Wanting to do something fulfilling and not being able to. Feeling understimulated, tasks (if you have any) seeming meaningless and unsatisfying, and time seems to stretch out.

* Need to embrace and work through boredom. Digital stimulation is used to numb unpleasant emotions, so reducing external stimulation is key.
* Reach the end of thought (many are born of external stimulus, then a period of extreme boredom as your mind struggles for stimulation and seeks dopamine). Then will be hypersensitive to internal drivers and it'll be clear based on values what you want to do.

## 😞 Disappointment

Disappointment is the negative state that you feel when your expectations aren’t met. 
Hope counteracts disappointment and regret — it leads you from, “Things didn’t work out” to, “I’ll make sure things work out next time.” Growth mindset also offers hope things can change next time

Regret is disappointment plus guilt - Things didn’t play out the way you wanted, and it feels like it’s your own fault. People tend to regret things they didn't do rather than the things they did.

* Hindsight regrets: you made the best decision that you could then, but you know more now 
* Alternate-self regrets: you have a vague sense of regret that comes from wanting to live different lives 
* Rushing-in regrets: you made a decision that you weren’t sure about or weren’t ready to make at the time 
* Dragging-out regrets: you waffled about a decision for a long time, even though you sort of knew what you needed to do 
* Ignoring-your-instincts regrets: you had a gut feeling that you weren’t making the right decision but acquiesced to others’ needs or opinions 
* Self-sabotage regrets: you made a decision that you knew wasn’t good for you, but you did it to protect yourself from feeling another emotion (rejection, loneliness, vulnerability)

## 👀 Envy

Envy is not jealousy - they result from different situations, generate distinct appraisals, and produce distinctive emotional experiences. Envy typically involves two people and occurs when one lacks something enjoyed by the other. Envy occurs when we want something another person has and we don't feel like we can have it.

Envy helps you identify what you want in life.

* **Plain Envy** - don't want to take it away from someone
* **Malicious Envy** - want to take it away from someone

Reasons it happens:

* Poor self-efficacy (they don't believe that they can or they haven't proven to themselves that they can)
* Pessimistic messaging from others
* Lack of resources
* Social comparison leading to "compare and despair"

Managing:

* If you envy something you truly cannot have, practice radical acceptance
* If you envy someone else, are you willing to give up your whole life, memories, experiences, and relationships, to be in that person’s shoes? Remember this quote from Naval Ravikant:
  * *"One day, I realized with all these people I was envious of, I couldn’t just choose little aspects of their life. I couldn’t say I want his body, I want her money, I want his personality. You have to be that person. Do you want to actually be that person with all of their reactions, their desires, their family, their happiness level, their outlook on life, their self-image? If you’re not willing to do a wholesale, 24/7, 100 percent swap with who that person is, then there is no point in being envious."*


## 😢 Feeling Depressed

Note - I'm not considering feeling depressed as the same as something like Major Depression Disorder (MDD). This is meant more for mild cases, though I am distinguishing this from regular sadness.

*"People in the depressive position are often stigmatized as 'failures' or 'losers'. Of course nothing could be further from the truth. If these people are in the depressive position it is because they tried too hard or taken on too much. So hard and so much that they have made themselves ill with depression. In other words, if these people are in the depressive position, it was simply because their world was not good enough for them. They wanted more. They wanted better. They wanted different, not just for themselves, but for all those around them. So if they are failures and losers, this is only because they set the bar far too high. They could have swept everything under the carpet and pretended as so many people do, that all is for the best and the best of possible worlds. However, unlike most people, they had the strength and the honesty to admit that something was amiss; to admit that something wasn't quite right. So rather than being failures or losers they are all the opposite. They are ambitious, they are truthful, they are courageous, and that is precisely why they became ill. To make them believe that they are suffering from some mental disorder, or some chemical imbalance in the brain, and that their recovery depends entirely or even mostly on popping pills is to do them and to do us an immense disfavor. It is to deny them the opportunity, not only to identify and address important life problems, but also to deny them the opportunity to develop a more refined perspective and a deeper understanding of themselves and of the world around them; and therefore, to deny them the opportunity to develop their highest potential as human beings."- Dr. Neel Burton*

Depression is all consuming, ongoing, and an exhausting response to a loss of some sort.

Depression, though on the surface doesn't make sense from an evolutionary perspective, potentially was adaptive for these reasons (I'm not sure I buy this though tbh...):

* Allows for staying safe after an injury
* Offers either enhanced immune responses from infections, or during plagues, depressed people who didn't go outside were less likely to, you know, get infected and die
* Introspection from depression allows for evaluating one's place and importance in a group

Signs of depression: 

* Inability to abandon negative beliefs about self, and typically dismiss positive information
* Social withdrawal
* Anhedonia
* Disrupted sleep
* Weight loss or gain
* Fatigue or loss of energy
* Poor concentration or indecisiveness
* Extreme irritability or chronic anger
* Watching the same shows over and over again because of already knowing the outcome and not needing to worry about the emotional investment

Managing:

* Healthy habits (eat right, stay hydrated, exercise, meditate, 8 hours of sleep, be in nature, journal, etc)
* Cognitive Behavioral Therapy can be used to manage thought biases that are common when depressed - how we feel is not evidence that these thoughts are true
  * “It’s only a thought, it’s not any more powerful than a thought about how the milk is running low.”
* Develop promotion goals (making good things happen) over prevention goals (avoiding bad things)
* Build strong social ties through volunteering or clubs if your social circle is weak
* Understand the beliefs associated with the Ideal Self (who you want to be), Actual Self (who you are), and the "Should Be" Self (what you feel you must do)
* See depression as separate from yourself, not who you inherently are
  * “You can be happy and sad. You can be an individual while still being a part of a community. You can feel grateful and displeased.”
* Set realistic expectations - aim for content and not happy
  * “You don’t have to be hopeful about the future. It’s enough to just be curious about what will happen next.”
* Address demoralization and helplessness in therapy
* Know that hating or loving yourself is a choice
* With anhedonia, continue doing things even if the "want" isn't there
* "There's a very fine line between being in a groove and being in a rut."

## 😭 Grief

*As my grieving and recovery work progressed, I discovered why I was so intimacy-phobic: becoming intimate with another would (and eventually did) unlock the prodigious hunger of all my unmet needs for love. I was unconsciously terrified that if anyone began to meet those needs, I would begin to depend on them and end up needing them.*

Grief is love with nowhere to go. The depth of your grief is the depth of your love. Combines painful feelings of loss with a desire to get back what we lost, even if that’s impossible. Often triggered by endings of life, relationships, jobs. It's a normal and natural part of being human, and the pain can be both physical and emotional. Trying to block out or repress grief can cause further problems down the line. 

5 stages of grief:

* Denial can help us survive the overwhelming pain of grief. As denial fades, this allows new waves of emotion to surface.
* When we experience anger about something we can’t control, using physical movement helps us to use the physiological arousal and bring the body back down to calm for a while.
* Ruminating over the What ifs can easily lead down a path of self-blame.
* Depression is a normal reaction after a bereavement.
* Acceptance is not the same as liking or agreeing with the situation.

Managing:

* Let the dead be dead - Give 30 minutes each day to experience and feel the grief at 100%, and then give yourself permission to be with the living
* The Spirit Never Dies - Talk to the loved one who has passed; say what you're grateful for and ask what they wish for you
* Practice mourning the loss by working through the pain, accepting the new reality, and not putting an expectation on how the process should go or how quickly you should be "done" with the process
* If grieving a loss in childhood:
  * Feelings of unfairness and resentment can arise, especially if the loss is great and requires many instances of grieving (can feel unending)
  * Practice these components:
    * Angering (Active)
    * Verbal ventilation (Active) - speaking or writing to release painful feelings in uncensored way
    * Crying (Active) - can bring catastrophizing to a halt
    * Feeling emotions throughout body in present moment, not resisting (Passive)
* If [grieving climate change](https://www.goodgriefnetwork.org/resources/):
  1. Accept the Severity of the Predicament
	2. Be with Uncertainty
	3. Honor My Mortality and the Mortality of All
	4. Do Inner Work
	5. Develop Awareness of Biases and Perception
	6. Practice Gratitude, Seek Beauty, and Create Connections
	7. Take Breaks and Rest
	8. Grieve the Harm I Have Caused
	9. Show Up
  10. Reinvest in Meaningful Efforts
* Be mindful of ambiguous grief, where murky losses are confronted (single people longing for a relationship, partner lost to Alzheimer's, woman unable to become pregnant, etc) and are generally unacknowledged by society at large

## 😅 Guilt

*You may feel guilty even when you are doing something healthy. Feeling guilty for making healthy decisions that others don't like was a seed planted by people attempting to control your behaviors. Push through your guilt, and do what's best. The more you practice making healthy choices, the less guilty you will feel.*

Guilt is "I'm doing/did something wrong" while shame is "I am wrong". Guilt allows for desire for positive change.

* Guilt: "I didn't work hard enough."
* Shame: "I'm too lazy."

Managing:

* Learn Recipe for Effective Apology 
  * statement of regret for what happened;
	* a clear “I’m sorry” statement;
	* a request for forgiveness—all of which must be delivered with sincerity;
	* validating the other person’s feelings;
	* offering atonement;
	* acknowledging we violated expectations
* Forgive Yourself
* Reengage in Life

## 😀 Happiness

*Happiness is not a second-order event that is premised on something else occurring first. It is a first order event that happens when you live your truth.*

Happiness is pleasure related to your surroundings or your current circumstances.

Factors:

* Lack of suspicion and resentment
* Not living in the past
* Not wasting time and energy fighting things you cannot change
* Staying involved in the living world
* Refuse to indulge in self-pity
* Cultivate old-fashioned virtues
* Don't expect too much from yourself
* Find something bigger than yourself to believe in

How to think of happiness:

* Pursuing happiness is fine, but concern about happiness leads to negative meta-emotions (feelings about feelings)
  * Example: You set up a birthday party. You can aspire to be happy or overthink it (why am I not happy?), triggering further disappointment that compounds onto itself
  * Don't judge your emotions or intensely monitor your feelings (more likely to judge)
  * Don't treat life/activities as a means to an end - "Happiness is like a butterfly which, when pursued, is always beyond our grasp, but, if you sit down quietly, may alight upon you."
* Think of happiness like a retirement portfolio. Balance it in terms of stocks/bonds/etc, short-term vs long-term, and more. Focusing entirely on purpose means forgoing joy and the small daily moments that make life enjoyable
* Financial security (to a certain extent) can add happiness, as money is a big stressor in people's lives
* Happiest people socialize 6-7 hours a day in person; for every new friend you add to your social network you're 15% more likely to be happy

## 👤 Loneliness

*As I continued to grieve I was shocked to feel how profoundly lonely I was and had always been. I had been so sure that I didn’t need anybody. My tears revealed to me the awful misery of my loneliness. I was daunted by the realization that I had never spent a moment of true interpersonal comfort with anyone.*

Loneliness can be described in different ways; a commonly used measure of loneliness, the UCLA Loneliness Scale, asks individuals about a range of feelings or deficits of connection, including how often they feel: 

* they lack companionship
* left out
* "in tune" with people around them
* outgoing and friendly
* there are people they can turn to

Types of loneliness:

* **New-Situation Loneliness** - change in location, job, etc.
* **I'm Different Loneliness** - feeling fundamentally different from others
* **Intimate Loneliness** - lacking close relationships
* **Pet Loneliness** - lacking a pet
* **No Time for You Loneliness** - people who are friendly but don't want to, have time to, or don't want to prioritizing, becoming or maintaining a friendship
* **Relational (Casual Friends) Loneliness** - lacking depth and ability to confide/trust others
* **Quiet Presence Loneliness** - not having someone to hang out with at home to know they're "there" 

Signs of Loneliness:

* Oversharing when someone is listening
* Feeling disposable in a group
* Putting other people's needs above your own
* Feeling need to be overly helpful or nice
* Feeling isolated and like nobody sees you
* Feeling like you don't belong anywhere
* Becoming obsessive with friendships

Managing:

* Get a hold of it before it gets too bad if possible. The longer it stays intense the more your thinking will be corrupted
* Deepen emotional bonds with others
  * Face to face time with friends or family, ideally every day. If not, try for video or phone calls, with text as the last/worst option
  * Physically touch others
  * Host dinner parties or other social events
  * Become a great listener
* Be vulnerable and talk about loneliness with other people
  * Don't pursue negative relationships to fill the void
* Create opportunities for social connection
  * Join a group... but don't just join a group to "join a group", especially if you hate the content
  * Attend a park, local cafe, church, or other local space where you might come across others
  * If at an event, talk to a stranger for at least seven minutes to know if the conversation will be interesting
  * Trivial conversations help with loneliness
  * Be kind to strangers
  * Diversify your social portfolio, including coworkers, friends, family, and strangers
  * Do not overextend yourself socially, focus on several times a month at most, not every day (not as applicable for extroverts)
    * However, don't find poor excuses to turn down social events, including skipping a spontaneous event due to feeling "unprepared"
  * Be active, not passive online. This means participating in communities, chatting about topics you care about, give advice on forums, have video calls with friends, and share vulnerably online.
  * Respond reasonably when talking with others
    * Don't respond curtly or hog the conversation
    * Ask others about their lives and opinions
    * Don't confess your faults and insecurities to those you just met
* Practice healthy habits
  * Determine specific discomfort with being alone
  * Remember observability bias - you encounter solitude frequently, but never encounter other people's.
  * Give others benefit of the doubt, and don't take friendly ribbings too personally
  * Don't compare yourself to someone's highlight reel
  * Share good things when they happen in the present moment
  * Spend more time in nature and away from screens
  * Don't use defensive body language (folding arms over chest, hands in pocket, looking at phone)
* Adopt a pet
* Enjoy being alone
  * Pursue hobbies and things only you want to do
  * Take yourself out on a date and focus on things that your best days consisted of, what you stopped doing for no reason, and made hours fly by
    * "I need to find a partner, I don't want to be alone". She rephrased that at the end of one session, "I want to find a partner, I don't need to be alone." 
  * Differentiate taking time for yourself (conscious choice) and self-isolation (driven by fear)
    * "There is a difference between being lonely and being alone. Learn to embrace and enjoy the latter and the former will fade away."
* Use nostalgia to give your life meaning again
  * Lonely people often feel like side characters in their own lives with a lack of meaning or direction; nostalgia can help to recenter the narrative

## 👎 Rejection

We are wired for connection. Rejection, perceived or real, hits on primal buttons related to belonging and survival. As babies, rejection by a parent can be fatal. We carry this longing for connection with us into adulthood, and the possibility of rejection often feels intolerable.

Even though rejection is painful, it's survivable.

* Acknowledge and accept your feelings
* Reflect on the situation
* Seek support from others
* Keep things in perspective

## 😳 Shame

*There is no person that does not have a past version of themselves that is not pleasant to think about.*

*We can’t remove shame by improving either. By doing more things, becoming better incarnations of the humans we are. We can only remove shame with empathy, love, acceptance, and connection. *

*“What happened to you was wrong, but there is nothing wrong with you.”*

Shame is the feeling that you’re an inherently bad or flawed person. and thus unworthy of love/belonging and/or incapable of change. When we feel shame, we might believe that we’re unworthy of love or incapable of change. Effectively, shame is the gap between who we are (current self) and what we want and/or believe we should be (ideal self), and needs shame, secrecy, and judgment to thrive.

Signs it's present include thinking you're never good enough, not worthy of love and belonging, questioning why you feel you deserve these things in arrogance, and having emotional flashbacks. 

Managing:

* Be aware of shame and name it when it occurs for you
* Understand the origins of shame and how it happened to you as a young child
* Practice self-compassion
* Acknowledge the different parts of yourself
* Share in the context of safe relationships
* The fact that you are high functioning doesn't mean that you are easier for you to deal with, it means it's easier for others to deal with you.
* Be mindful of "leaky feelings", where there is incongruence between your inner state, awareness, and behavior. This can be addressed through shadow work and understanding what you're most shameful of, as that is what is most likely to "leak" out

### 🌆 Systemic Shame

There is also the shame that is built into society, coined by Dr. Devon Price as Systemic Shame. The core values of Systemic Shame include:

* Perfectionism: Only endless, flawless work and accomplishment matters. 
* Individualism: Everything that we do we do completely alone. 
* Consumerism: Who we are is what we buy and own. 
Wealth: The only power that matters is economic power over others. 
Personal responsibility: Change only happens through personal willpower and strength.

There are three levels:

* **Personal Shame** - feelings of self-loathing over identity, limitations, or perceived failings. Leads to hiding yourself from others/avoidant tendencies, leading to interpersonal shame. Heal personal shame by practicing radical acceptance, including:
  * Telling others what you're feeling
  * Admitting when hard work and struggle is going nowhere
  * Indulge in desires that have always been there but are considered socially taboo
  * Live as a person that others might dislike, and not caring what they think
* **Interpersonal Shame** - believing other people are unsafe/untrustworthy, and people are generally immoral. Leads to harshly judging the actions of others, being hyperindependent, focusing only on self-preservation/safety, and not accepting help from others. Heal interpersonal shame by practicing expansive recognition:
  * Noticing when you view someone's actions in the worst possible light and asking why.
  * Speaking up when needs are in conflict of those of a loved one, so the bond can be repaired.
  * Thinking a lot about other people's positions (economic, cultural, legal, etc.) make their lives different than your own.
  * Surround yourself with people that make being "you" feel natural and safe.
* **Global Shame** - believing humanity is filled with selfish, apathetic, or morally "bad" people, feeling humanity isn't even worth saving. Leads to being cynical and not trying to improve relationships or the community. Heal global shame by having hope for humanity:
  * Trust in the inner voice/conscience that tells you what is right.
  * Abandon pursuits that you were trained to value but don't really believe in.
  * Appreciate the potential of where you are and finding opportunity to make a difference right where you are.
  * Build connection in the local neighborhood/community to feel a part of something greater.

# Maladaptive Mindsets

## 🎮 Control

*I realized that I felt more comfortable with productivity because it provided the illusion of control. Letting myself venture off from my to-do list was risky — it meant I had to allow myself to feel, to recognize when my body and mind needed rest, and also to trust that I would be able to recharge and come back to my schedule.*

Can show up in a variety of ways across all the domains of life and is generally done out of fear in order to feel safe. Examples of the control being maladaptive:

* Eating disorders
  * In less severe situations, orthorexia
* Financial rigidity through movement like FIRE
* Excessive tidiness and cleanliness
* Psychological orthorexia
* Disapproval avoiding - creating an inoffensive persona by sanding down all the bits that make you authentic and becoming like white bread (which in turn, makes people not like you)
* Unending personal development and growth
  * *Why do we have to grow and excel all the time? Why does failure require constant rehabilitation? Why can’t we just let it be exactly what it is – a normal and natural part of our mortal existence? To put it bluntly, the growth mindset purports to celebrate failure when in actual fact it does completely the opposite.*

This level of control can be a means to reduce feelings of inferiority and shame. Sometimes, when we procrastinate, it's because we need to feel control, even when the only thing we can control is choosing not to do something - even when it contributes to making our situation worse. 

## 👌 Perfectionism

*May I have the strength to change that which I can change, the patience to endure that which I cannot, and the wisdom to know the difference between them.*

*Who knows how many of us are playing a similarly important role in the lives of those around us, completely unaware of how much our little efforts are appreciated, because we’re still locked behind unrealistic expectations and the shame of not meeting them.*

Defense mechanism to cope with emotional neglect and also is about safety. 

Three main types of perfectionism:

* **Self-Oriented Perfectionism** - I must be perfect (or meet an exceptionally high standard) in order to be worthy of love and respect
* **Socially Prescribed Perfectionism** - Others expect me to be perfect (or meet an exceptionally high standard) in order to be worthy of love and respect
* **Other-Oriented Perfectionism** - Other people must be perfect (or meet exceptionally high standards) in order to be worthy of love and respect

Examples:

* Treating benign statements as jabs at perceived imperfections
* Intensely critical and an absence of self-compassion
* Working without enjoyment and never feeling like you've done "enough"
* Fearing failure in various forms (feedback and performance appraisals, competitions, etc)

Treatment:

* Remember both/and - two seemingly contradictory beliefs (especially if you are a black and white thinker) can be true at the same time
* Recognize perfectionism is a self-defense against shame and does not serve you
  * Understand where the belief of perfectionism originated from in your past
* Name your inner critic / perfectionist
* Practice healthy striving, setting reasonable goals based on your wants and needs rather than external validation
* Challenge inner negative thoughts with CBT
* Accept when good enough is good enough
  * 'I'm not really a perfectionist. I don't need to achieve 100%. 80% is good enough.' My psychologist: 'Have you considered that your 80% might be someone else's 100% or even 120%?'
* Describe yourself in germs not associated with success in career, appearance, or how others think of you
* You have to choose what you suck at. Nobody has time to do it all. Everyone puts a priority on their health and lots of people don't realize they're prioritizing it dead last.

## 🚫 Procrastination

Procrastination is often avoidance of stress and discomfort, driven by some fear.

Downsides:

* Worsened health due to stress
* Feelings of regret

Do not:

* Say you're procrastinating when you're simply not prioritizing something
* Beating yourself up for procrastinating, it makes sense from an evolutionary perspective for short-term gains
* Press the "try harder" button to get things done, this will just lead to burnout.
* Treat yourself as a machine, you can't just go 2x as fast without changing the code/process in some way. Instead think in systems and how you can set yourself up for success.
Don't treat the task as an uphill boulder that's boring or meaningless; try to think of how to make the task more energizing.

Manage:

* Don't wait for motivation - do it anyway
* Sit quietly (free from distraction) and think for 15 minutes about what you're going to do (prevents avoidance behaviors, gives anxiety chance to abate)
* Break down tasks into tiny, bite sized pieces, and mark progress with smaller tasks
* Do low effort, crappy versions of task as often as you can to "lower the stakes"
* Make distractions the primary task and the primary task as the side task

## 🤠 Low Self-Worth

*"You can't logic yourself into having self-worth. Using high intelligence to solve emotional issues is like a black mage trying to cast healing spells."*

*In therapy, my therapist and I were talking about my own feelings of self-worth in relationships. And she asked me to say qualities about myself that someone else would be attracted to, on a romantic and platonic level. So I mentioned some things like compassionate, empathetic and she said, "You named things that you can give someone; ways you can serve, rather than ways that you are."  And my mind was blown. That's going to stick with me forever. She then proceeded to tell me actual innate qualities about myself that she liked and thought anyone else would like as well and I hadn't even considered those because, like she said, I was focused on things I could do outwardly to attract and maintain connections rather than who I was as a person.*

Can be conflated with self-esteem, which is a more transient version. Instead of focusing on specific traits, skills, circumstances, or achievements, self-worth describes the core beliefs you have about your worth and value. 

People with high self-worth:

* Believe that they are good, worthy, and lovable regardless of what's happening in life
* Feel deserving of love and respect from others
* Accept and love yourself now with no conditions or exceptions
* Practice self-compassion and treat yourself with kindness, care, and respect
* Believe in your potential to grow, learn, change, and improve
* Have flaws and make mistakes that don’t threaten your identity or worth

Signs of low self-worth:

* Conditional self-worth; only being worthy if your relationships, appearance, net worth, career, or achievements are X.
  * Job/career can just be a way to make money, not your life or identity
* Feeling inherently undeserving of love and belonging and deserving suffering
* Fear that developing self-worth will stop motivation to grow/change, lead to arrogance, or that it's just impossible to cultivate
* When you use the words “I should...”, you’re silently finishing the sentence with “...in order to be worthy of love and respect.”

Causes:

* Negative experiences in early childhood (including repeated little t traumas)
* Negative core beliefs
* Stressful life events

Treatment:

* Understand where the low self-worth criteria comes from. What makes a person worthy, what does worthiness mean, and worthy of what?
  * If there are specific criteria, like "you have to be financially independent and be married," ask "Does this apply to everybody, or just to you?" 
    * If this criteria represents your core beliefs, develop a realistic strategy to meet those goals and become worthy. 
    * Instead, if you realize you're clinging to a rigidity that you don't actually believe in, remember brains can confuse feelings for facts. So feeling undeserving can lead to your brain justifying your low self-worth, even if it doesn't align with your beliefs. Approach the issue on a metacognitive level. 
* Remember that everyone has flaws and imperfections, flaws connect us and make us interesting, and *if someone had been through what you've been through, they'd likely have the same flaws.*
* As uncomfortable as it might be, what if, that is just how and who you are?
  * ”What is the constant point of your life? I am a doctor but I am also a mother, the former can change at any time but the latter will never change. So who are you and what is the never-changing point of your life? What is it that will never change even if the worst comes to happen?”


## 🤡 Self-Sabotage

Chronically doing something that undermines your own goals or values, typically to get your needs met. Self-sabotagers are generally wired for perfectionism disappointment, self-shaming, shutting down, and needing a reward for basic lifestyle tasks

Examples:

* Taking whoever will take you in friendships and relationships
* Attracting emotionally unavailable people
* People pleasing 
* Excessive caretaking
* Being overly judgmental
* Being impatient
* Partaking in general self-destructive tendencies

How to manage:

* Understand the need your self-sabotage fills
* Identify alternative healthy behaviors that fill that need
* Anticipate and plan for obstacles
* Boost your tolerance for uncomfortable feelings
* Clarify your values



# Maladaptive Strategies

These are typically triggered by the following:

* Problems with health, finances, relationships
* Conflicts
* Stress
* Transitions
* Travel
* Insecurities and feelings of inferiority
* Loneliness
* Boredom
* Depression
* Frustration
* Resentment
* Fatigue

## 🍷 Addiction

*“Addiction is a progressive narrowing of the things that bring you pleasure. Enlightenment is an expansion of the things that bring you pleasure.”*

Addiction can show in a variety of ways:

* Alcohol
* Overworking
* Pornography

Addiction chases hedonic happiness (self-enhancing; fame, fortune, beauty, etc) rather than eudainomic happiness (self-transcending; love, community, gratitude, empathy)

## 🛡️ Defense Mechanisms

Defense mechanisms come from:

* Mammalian brain - need to be safe
* Reptile brain - need to attach; let go of attachments that no longer serve you and overcome fear of missing out (FOMO)
* Rational brain - all-pervasive dissatisfaction; appreciate what you have

Types of defense mechanisms

* Acting out
* Avoidance
* Conversion (emotional pain becomes physical pain)
* Denial
* Displacement (repressing emotions)
* Dissociation
* Fantasy
* Idealization
* Identification
* Intellectualization
  * Cognitive Bypassing - talk about distressing experiences intellectually in a narrative way, and stay detached from emotions within the story
* Introjection (take stimuli from own environment and adopt as own ideas)
* Isolation
* Passive Aggressiveness
* Projection 
* Rationalization
* Repression
* Regression
* Splitting (understand in black and white terms)
* Somatization
* Suppression
* Wishful Thinking

## 🍩 Emotional Eating

While emotional hunger feels the same as physical hunger, these are the signs it's happening:

* Eating outside standard meal times
* It's urgent, sudden, and unstoppable
* Want to eat a lot more than you normally would
* Craving junk food specifically
* Feeling guilty afterwards

Why it happens:

* Feel psychologically safe
* Dull/numb painful emotions
* Connection between being fed and loved
* Chewing rids energy of negative surplus
* Sugars release dopamine

Treating:

* Name and track emotions and body sensations
* Surf the urge (pay attention without trying to change it)
* Remember you can't control your thoughts, but you can control if you act on them
* Practice self-validation
* Reinforce and offer love, support, and comfort
* Clarify your needs
* Catch and reframe self-defeating thoughts
* Highlight resources to manage situation and provide hope
* Address needs and set nurturing limits


## ✈️ Escapism

To cope with unstable times, Soviet citizens enduring the daily stresses of a failing state turned inward. They called it “internal emigration,” a metaphor for the imagined inner world to which ordinary people could retreat to find solace. This mental relocation took many forms, but for most Soviets, cultivating a fierce spiritual autonomy—through music, literature, poetry, art, foreign language learning, private gardening, or immersing themselves in nature—provided the only respite from the grinding indignities of an aging political bureaucracy insensitive to the needs of the populace.

But internal emigration can cultivate the habit of apathy. The very real desire to protect oneself from the pressures of an unjust system promotes disengagement and undermines our cognitive capacities for hope. More importantly, when the system unexpectedly changes, we may be unprepared to fight for a new world. 

## 🦺 Safety Behaviors

*To have any hope of experiencing a deeper, lasting shift, we must recognise that as much as we want change, a part of us is terrified of it, and will fight against it, because we also want things to stay the same. Part of us is choosing a safer life over a better life.*

Safety behaviors are things that we do to with the intention of keeping us safe.  They can include forms of avoidance, distraction, preparing, and checking. While safety behaviors may offer immediate relief from anxiety, they actually trap you in a long-term cycle of fear. 

Signs of safety behaviors:

* Sitting only in the back row of the classroom to avoid being noticed.
* Avoiding eye contact while grocery shopping and while going through the check-out.
* Wearing sunglasses while using public transportation (even on gloomy days).
* Over-preparing for presentations or meetings.
* Mentally rehearsing conversations before they happen.
* Carrying a bottle of anti-anxiety medication whenever outside of the home.
* Leaving the house only if accompanied by a trusted loved one.
* Creating an escape plan from any building entered.
* Checking the locks on the house or car door multiple times.
* Frequently checking or going on electronics during social interactions.
* Consuming alcohol, recreational drugs, or other substances to curb anxiety.
* Engaging in superstitious rituals before, during, or after situation that elicits anxiety.
* Avoidance of locations or situations that tend to increase anxiety.
* Having to carry a certain object in situations that tend to increase anxiety.
* Frequent visits to the doctor for slight changes in physical symptoms or sensations.
* Frequent checking of heart rate, blood pressure, or other vital recordings.
* Staying awake for long periods of time to ensure safety of home.
* Wearing excessive amounts of clothing when in public to avoid attention.
* Re-reading a text or e-mail multiple times before sending.
* Calling a loved one several times throughout the day to check on their safety or well-being.

CBT aims to break this cycle by replacing these behaviors with exposure therapy. Through facing anxiety-provoking situations without safety crutches, you teach your brain new ways to handle them, leading to reduced anxiety and a life aligned with your values. It's like experiencing discomfort now for long-term peace, instead of the other way around.

## 📚 Self-Help Addiction

Trying to become a machine and always striving for the fantasy future where we achieve an idealized self, rather than appreciate who we are in the current moment.

* Self-improvement means self-acceptance is conditional on "fixing" yourself, only getting a respite when you do an A+ job, meaning it's everlasting
* We think if we punish ourselves enough, we'll change. 
* Believe that we're giving up control by choosing self-acceptance, specifically, we're exerting some sort of meaningful control when we fight against something

Signs:

* Willing to root for the future version of you, but feel contempt and disgust when you think of the person you are now
* Use self-improvement as an excuse to isolate and hide from other people ("disappear for 6 months and return a changed person" trope)
* Use self-improvement to hide in plain sight (you refuse to relate to people as the person you really are, only talk about plans of the future, "sell" them a better version of you, never the present version)
* Go through cycles through extreme work on yourself then burnout / collapse (grindset, high goals, "I'll be happy once I get there", no joy in the present)
* Try to stay in control of which feelings you're having when (terrified of spontaneous feelings / natural state of living; keeping shame out)
* Experiencing psychological orthorexia
  * Self-improvement is a project that never ends and robs the joy from leisure activities that have nothing to improvement, as well as general community-focus
  * Proving your self-worth through overachieving at personal growth (workaholics shift towards this to show value)
    * Ex: stressing out about not being "perfect" at a relaxation class
  * Doing a little bit of everything in recovery can be a way to meaningfully avoid engaging in any specific method (avoidance/neurosis)
  * Feeling as if there's a finish line to personal development and if you reach it you can tap into creativity and productivity whenever you wish

Recovery:

* Develop dignity and respect for all parts of yourself
  * *"Dignity is your inner parent saying to your inner child: 'It's OK that you have ended up where you have ended up in life. It makes sense, based on what has happened to you, that you have ended up here. So let's look at where we're at, together, with compassion. And let's figure out what we need to change as a team, so that we can end up somewhere better -- where we feel less defended, and more open to the world around us. I'm going to stay present with you, and I'm going to help you get there. I am not going to abuse you along the way.'"*
* Reality check your shame beliefs

## 🤳 Tech Addiction

Spending too much time on addictive electronic devices (computer, phone, etc), the internet, and/or social media.

Why it happens:

* Technology and devices are designed to make people get addicted; it is not a personal failing to be exploited by the technology
* Can be an educational avenue
* Desire to be informed and know what's going on
  * You'll never learn enough to get to feel you know everything that's going on; the desire just leads to endless consumption without context 
  * You will never do all your hobbies, read all the books, play all the video games, etc; you will have to pick and choose (treat hobbies like a river, where if something passes it's okay)
  * We are hard-wired to chase novel information, are in a world where novel information is readily accessible, and bad actors and AI exploit this

Manage:

* Seek higher quality and less addictive learning resources
* Make phone less appealing to use
  * Disable browser
  * No email (especially no work email)
  * Essential apps only, and with offline use when possible
  * Turn off notifications
  * Turn off data and wifi
  * Grayscale phone
* Practice mindfulness
* Find enjoyable offline activities to supplement spending time on technology
* Rely less on technology
  * Scrolling is not resting
  * Focus on single tasking
  * Don't rely on GPS to tell you where to go
  * Cook without a cookbook
  * Write in physical journals
  * Read physical books
  * Put phone away when talking to others
  
## 💼 Workaholism

Whether it’s your career, community projects, or personal to-do lists that consume your everyday life, your addiction to activity is problematic for many reasons. Once you get a dose of completing a job, an impulsive urge to drown yourself in more activity immediately creeps in. Without it, you experience a profound sense of worthlessness.

This kind of “improvement” workaholism is about self-worth and a felt sense of safety. Because idleness feels unsafe in the body of a workaholic, non-activity is misconstrued as uselessness, which feels like a gaping hole in your beingness. The wisdom of a workaholic’s body knows that not creating, producing, or improving oneself or the environment is on par with being an unlovable sack of garbage. So your body keeps you busy.

A work-oriented perfectionist unconsciously harbors a belief that they’re unworthy unless they’re busy fixing themselves or the world. Learn to be in touch with what you’re feeling in your body, known as interoception. This alone is a practice that will pay you back tenfold in overall well-being, decision-making, and trusting your inner guidance.

# Adaptive Mindsets

Brene Brown's 10 Guideposts for Wholehearted Living:

* Authenticity (show up and be real/honest) will lead to letting go of what other people think
* Self-compassion will lead to letting go of perfectionism
* Resilience (resourceful, problem-solving skills, willing to ask for help, proactive, build support system for selves and invest into being connected with others, and are hopeful and aware of emotions) will lead to letting go of numbing and powerlessness
* Intuition and Trust will lead to letting go of certainty
* Creativity (expressing self in unique way) will lead to letting go of comparison
* Play and Rest (playing to enjoy life, not for any purpose; doing tihngs that make one feel alive like rest, play, fulfilling connections, and creativity) will lead to letting go of exhaustion
* Calm and Stillness (having healthy perspective on situation while managing emotional reactivity) will lead to letting go of anxiety
* Meaningful Work (not squandering personal gifts) will lead to letting go of self-doubt
* Laughter, Song, and Dance (can't fight shame if not allowed to be vulnerable in these realms) will lead to letting go of always being in control

[Simple rules of self-help books](https://mashable.com/article/best-self-help-book-advice):

* Aim to be 1% better and take small steps towards goals (ie, make them too small to fail)
* Change your mental maps to be successful
* Don't be afraid of struggling or scary things (Stoic approach)
* Don't rush to judgements
* Memento mori - be willing to take a risk so you don't regret it at the end of your life
* Don't give a crap what others think of you; be yourself
* Be useful to others
* Perfection is the enemy of good enough and leads to procrastination
* Eat healthy, exercise, sleep for 8 hours, meditate, and know how to relax
* Write things down and prioritize them accordingly to their importance
* Do the work, don't just read about it

## 🖼️ Cognitive Reframing

* Once identified, begin acknowledging when and where maladaptive thoughts arise. * When these automatic thoughts pop up, start thinking about the why behind them. 
* Start questioning your assumptions and gather evidence against your biases.
* Start performing a cost-benefit analysis of your negative thoughts.
* Switch negative thoughts for positive ones.

## 🪥 Develop Healthy Habits

List of healthy habits: 

* Meditation & Mindfulness
* Eat Mediterranean diet
* Sleep 8 hours every night and have a consistent sleep schedule
* Exercise moderately for 150 minutes every week
  * Yoga, tai chi, qigong, etc to maintain flexibility
  * Include both cardio and weightlifting
* Set goals on a macro and micro level
  * Visualize success
  * Monitor how you spend your time
* Set boundaries
  * Take breaks to recover when needed
* Journal to process emotions and understand better
  * Find your why
* Read regularly to learn new things

How to do:

* Make your habits and cues obvious
  * Track what you do for a week by half-hour increments (use an automated tool if possible)
  * Plan in advance when and where you’ll perform a new behavior: Use the formula, “When X occurs, I will do Y.” 
  * Habit chaining: “After I do X, I will do Y” Be specific and realistic with this
  * Don't let perfect be the enemy of good enough
  * Make undesired habits harder to do (ie, don't buy junk food rule)
* Make your habits appealing
  * Temptation bundling: Connect "should dos" with things you want to do: “After X [current habit], I will do Y [new habit]. After I do Y, I get to do Z [craved habit].”
  * Join a culture where desired behavior is normal and believe you're the type of person that does the habit you want
			§ Ex: I am a person that exercises, etc
			§ However, don't assume you'll be a different person overnight - change is gradual
  * Do something you enjoy immediately before a difficult habit
  * Reframe obligations as opportunities (not helpful for creativity based tasks)
* Make your habits easier
  * Automate tasks when possible to reduce cognitive load
  * Pareto principle: focus on the 20% that really matters
  * Design your environment to reduce friction (ie, keep RFA easy to see)
  * 5 minute rule
  * Use commitment device to hold you accountable to not breaking habits (ex: Freedom)
* Make your habits fulfilling
  * Reward yourself for succeeding at new habit, ideally instant reward
  * Keep track of habit and "don't break the chain".
  * Get accountability partner
Financially penalize and/or shame yourself if you fail to achieve your habit

## ⚙️ Emotional Regulation

Emotions give us data about ourselves and other people; us expressing our emotions also displays that data to other people. Generally, emotions signal something that we need to ourselves or others. 

There are no "bad" or "good" emotions, despite how society may label them. While emotions are not always fact, pushing the emotion away can cause more problems than letting it run its course. In a mentally healthy state, emotions can validate and reward us for practicing healthy behaviors that help us thrive.

Types of Regulation:

* Auto-Regulation (it just happens automatically)
  * Thumb-sucking
  * averting eye contact
  * Reading
  * doing art
  * watching TV
  * Alcohol & drugs
  * Masturbating
  * Daydreaming
  * Overeating
  * Swiping or scrolling on your phone
* External Regulation (You do it)
  *	Being held and soothed by a caregiver
	* Talking with a friend about your problems
	* Listening to a live talk or music
	* Getting a massage
* Interactive Regulation (We do it)
  * Dancing with a partner
	* Sex
	* Having a mutual dialogue
	* Musicians playing together
  * Cooking together
* Self-Regulation (I do it)
  * Breath control
	* Mental techniques like cognitive reframing
	* Muscle relaxation
  * Vocal control
  
Nervous system responses:

* Safe (parasympathetic & ventral vagal)
* Fight (sympathetic)
* Flight (sympathetic)
* Freeze (parasympathetic & dorsal vagal)
  * Shutdown/Collapse (extreme hypoarousal)
* Fawn (blended sympathetic and parasympathetic)
  * Attach
  * Submit
  
How to regulate:  

* Remember you are not your feelings and your feelings are not who you are. You can't control your emotions, but you can control what you do with them
* Ideally teakettle emotions - let emotions out somehow before hitting a breaking point
* Beware intellectualizing your feelings
  * You've used humor your whole life to compartmentalize your trauma and keep it at arm's length. This is the first moment where you acknowledge that it's real, and it happened, and it's a part of who you are.
* Acknowledge and name emotion; use emotions wheel if necessary
* Pause and notice physical sensations - don't avoid emotion or use distractions
* Sit in silence for a few minutes
* Don't rationalize or justify your feeling, you can ask "What story are you telling yourself about this emotion, and is it true?"
* Accept feeling may come up again but will be less intense each consecutive time

## 🫴 Forgiveness

*Forgiveness isn’t something you give someone else. It’s how you release yourself.*

*Many of us are ruthlessly unforgiving of ourselves when we discover we have inadvertently hurt another. Our hurtfulness seems so unforgivable that we are too ashamed to attempt an apology – or we go to the other extreme and apologize for every subsequent breath we take. Both positions are so entrenched in self-disgust that we cannot accept genuine forgiveness even when it is offered to us.*

Psychologists generally define forgiveness as a conscious, deliberate decision to release feelings of resentment or vengeance toward a person or group who has harmed you, regardless of whether they actually deserve your forgiveness.

Forgiveness requires acknowledging the hurt the person caused us. 

* You can continue to talk about it once you've forgiven
* Forgiveness does not equal reconciliation
* Forgiving once doesn't mean you must always forgive
* Forgiveness doesn't mean you can't be angry or upset
* You can forgive and not forget

Premature forgiveness can lead to **fossilized forgiveness**, a false sense of permanent forgiveness that arises from a desire to move on from the past triggered by shame and guilt

Practice:

* Acknowledge and accept feelings without judgment; determine if you are ready to let go and forgive
* Try to understand why you did what you did and factors that influence that
* Practice self-compassion
* Make amends, if possible, and try to see things from the other person's perspective
* Write a letter saying how you were hurt, write their response, and repeat aloud until you find peace and can let go of anger 
* Give yourself a daily permission slip to release unreasonable standards and other lingering burdens 

Ho'oponopono method of forgiveness:

* Remorse
* Forgiveness
* Gratitude
* Love

## 🙏 Gratitude

Gratitude is related to happiness, but it’s an active process: It means taking time and energy to appreciate what you have and what brings meaning to your life.

* **Forced gratitude** - using the concept of gratitude to stifle a negative emotion. You can't pretend to be grateful for something you know is wrong for you - you'll neither feel good about it nor get the positive effects of actual gratitude. Example: “I guess I’m glad I have a little money in the bank.” 
* **Tragic gratitude** - recognizing there are many things to be grateful for, but also recognizing things could be a lot better.  You don’t have to pretend things are better than they are, because true gratitude isn’t fake it ’til you make it. Example: “I’m grateful I’ve saved a little money, I need to come up with a plan to start saving more.”

Practice:

* Say thank you or write a thank-you note
* Give a gift
* Verbalize appreciation
* Do something thoughtful
* If writing down what you're grateful for is tough, find things you approve of and write about them that way. Example: "I approve of chocolate cake" vs "I'm grateful for chocolate cake"

## 🙋‍♀️ Identify Needs

### Basic Human Needs

* Love & Connection
  * Acceptance, Affection, Appreciation, Belonging, Cooperation, Communication, Closeness, Companionship, Compassion, Consideration, Consistency, Equality, Empathy, Inclusion, Harmony, 
Intimacy, Love, Mutuality, Nurturing, Respect/self-respect, Touch, Warmth, Sex
* Growth
  * Self-Development, Self-Realization, Progress, Opportunity, Expansiveness, Integration, Awareness, Challenge, To Understand
* Contribution
  * To give, To create (all forms), To write, To nurture, To assist, To be present, To support, Presence
* Significance
  * Empowerment, Competence, Belief, Meaning, Effectiveness, To feel known, To see and be seen, To be understood, Admiration, Participation, Infatuation, Purpose, Validation, To matter, Authenticity, Integrity
* Uncertainty
  * Movement, Change, Stimulation, Spontaneity, Sexual Expression, Experience, Travel, Discovery, Inspiration, Beauty, Joy, Playfulness, Humor, Flow
* Certainty
  * Choice, Autonomy, Independence, Space/Boundaries, Safety, Structure/Routine, Order, Stability, Support, Food, Movement/exercise, 
Rest/sleep, Trust, Peace

### Core Subconscious Personality Needs

* Approval 👏
	* Validating wins
	* Correcting critical self-talk
	* Practicing daily words of affirmation to self
* Spirituality 🙏
	* Meditating daily
	* Reading about different philosophies
	* Creating rituals that resonate with you (journaling, prayer, etc)
* Health 👩‍⚕️
	* Healthy plans with sleep, diet, exercise, mental health, socializing
	* Intermittent fasting
	* Taking proper vitamins and supplements
* Romantic Relationships 💒
	* Connection, affection, intimacy with self, safety
	* Taking time out to really process if you're feeling off
	* Checking in regularly with your feelings and needs
	* Taking yourself into consideration when making decisions (seeing and being present with self
* Adventure ✈️
	* Going on a nature hike
	* Trying a new sport
	* Taking a vacation at a new location
* Community 👨‍👩‍👧‍👦
	* Attending workshops or classes
	* Developing new relationships in your area
	* Volunteering
	* Joining group activities/exercise
* Exploration 🛣️
	* Traveling to new destinations
	* Taking road trips
	* Trying one new thing daily
* Social Justice 🏳️‍🌈
	* Attending protests/advocating
	* Joining a social change network
	* Writing articles or publishing content
* Education 🏫
	* Taking courses
	* Getting certified in new methods or processes
	* Going back to school
	* Reading books
* Comfort 🍿
	* Creating a cozy environment in your home
	* Wearing comfy pajamas
	* Watching a movie in your bed
	* Weighted blanket
* Learning 🧠
	* Listening to audiobooks
	* Book summary apps
	* Workshops at local library
	* YouTube videos
* Family 👪
	* Defining what your family values are
	* Defining your ideal conversations and creating strategies to connect with family differently
	* Doing forgiveness work on your family
* Status ⭐
	* Validating yourself and why you matter
	* Building a life for yourself that brings significance
	* Introducing yourself to new people
* Entertainment 🎮
	* Watching your favorite movies
	* Going to a comedy show
	* Playing a video game
* Wealth 💰
	* Creating a budget
	* Reading finance books
	* Creating financial goals
* Financial Growth 📈
	* Investing
	* Creating a second/third stream of income
	* Hiring a financial coach/planner
* Philanthropy 🫴
	* Starting a charity
	* Giving your time to others
	* Making financial or time donations to causes you care about
* Attention 👀
	* Giving attention to your feelings and needs
	* Taking time to truly see, hear, and understand what's happening inside of you
	* Giving attention to your boundaries and making room to express them
* Service 🐕‍🦺
	* Volunteer in local community
	* Showing up for friends or family
	* Donating to charitable causes you believe in
* Personal Growth ⬆️
	* Meditation
	* Journaling
	* Self-help/personal development resources
* Emotional Connection 💫
	* Cooking yourself your favorite healthy meal and practicing mindful eating
	* Doing introspective work and journaling
	* Having a date night with yourself and your thoughts
* Autonomy 1️⃣
	* Setting and communicating boundaries
	* Take a vacation alone
	* Meet your own needs regularly
* Teaching 🧑‍🏫
	* Creating classes or courses
	* Sharing online
	* Creating literature
	* Lecturing, speaking
* Control 
	* Building structure and routines
	* Organizing your environment
	* Regulating your emotions
* Communication 💬
	* Expressing your needs to loved ones
	* Sharing your boundaries with others
	* Sharing your fears and vulnerabilities
* Religion ⛪
	* Attending church
	* Prayer
	* Reading scripture and studying
* Freedom 🆓
	* Daily meditation
	* Trying new hobbies and activities
	* Traveling, exploring your neighborhood and community
	* Spending time alone
* Career Growth 💼
	* 10 year vision for your career
	* Ask for a promotion or raise
	* Trying new things and volunteering in different positions to grow
* Security 🔒
	* Creating order and structure in your life
	* Budgeting and saving your money
	* Taking care of your health and planning your future
* Expression 🎭
	* Speaking up for yourself
	* Painting
	* Singing
	* Publishing thoughts and ideas
* Creativity 🎨
	* Painting/drawing
	* Coming up with innovative ideas
	* Creative writing
* Fun 🎈
	* Picking up a new sport
	* Going to the beach by yourself
	* Attending a cooking or painting class
* Novelty 🆕
	* Changing your routine
	* Keeping a "weekly bucket list"
	* Trying new restaurants or food
* Nature 🏞️
	* Going on nature hikes
	* Spending time at the beach or outdoors
	* Playing outdoor sports
* Fitness 🏋️
	* Defining and setting fitness goals
	* Exercising regularly and tracking progress
	* Hiring a trainer or participating in fitness competitions
* Achievement 💯
	* Creating a to-do list and checking it off daily
	* Taking a daily action step towards your dreams
	* Pushing yourself outside of your comfort zone
* Materialism 💅
	* Organizing your closet
	* Sharing your fashion or furniture tips with others
	* Saving for a new car
* Discovery 🧭
	* Reading about topics you are fascinated by
	* Trying a new activity
	* Taking a new class with others
* Power 💪
	* Creating routines that empower you
	* Building abundance
	* Speaking up and finding your voice
* Leadership 🕴️
	* Working to grow and take on a leadership role in your new place
	* Taking leadership courses
	* Leading by example
* Beauty 👠
	* Trying new hairstyles
	* New makeup routines
	* Putting efforts together
* Knowledge 📚
	* Reading new books
	* Reading articles
	* Watching documentaries
* Impact 🌠
	* Creating a vision for your life that empowers you
	* Sharing your ideas and inventions with the world
	* Working on your vision daily
* Politics ❎
	* Taking poli sci courses
	* Staying updated on current political climate
	* Reading articles
	* Publishing your ideas
	* Getting politically involved
* Competition 🤼
* Connection 🧲
* Recognition 🏆
* Social 💃
* Helpfulness 🤝

### Tertiary (Moment to Moment) Needs

* Infancy
  * Comfort, Consistency, Echoing, Holding, Kindness, Love / care, 
Mirroring, Patience, Regulation of emotional arousal, Relief of distress, 
Safety, Soothing, Tenderness, Touching, Trust 
* Toddlerhood
  * Acceptance, Attention, Autonomy, Boundaries / limits, Empathy, 
Encouragement, Exploration, Fantasy / play, Free expression, Idealization, Listening, Mobility, Nurturance, Protection, Reassurance, Support, Understanding 
* Preschool
  * Acknowledgment, Approval, Celebration, Clarification, Companionship, 
Creativity, Fairness, Fun, Growth, Guidance, Hope, Purpose, Respect, 
Structure / order, Validation, Wonder, Worthiness 
* Elementary school
  * Adventure, Affiliation, Awareness, Choice, Competency, Connection, Cooperation, Counsel, Honesty, Industry, Information, Mastery, Mystery, Order, Role models, Separation, Stimulation 
* Adolescence
  * Authenticity, Experimentation, Fidelity, Freedom, Independence, Inspiration, Justice, Sexual exploration, Space, Spirituality, Variety 
* Young Adulthood
  * Commitment, Community, Efficacy, Humor, Integrity, Intimacy, Joy, Meaning, 
Passion, Peace, Productivity, Recreation
* Adulthood 
  * Appreciation, Beauty / aesthetics, 
Consciousness, Contribution, Expansion, 
Extension, Forgiveness, Generativity, 
Harmony, Significance, Silence 
* Old Age
  * Completion, Consideration, Contentment, Ease, Wholeness 

## 🧙‍♂️ Philosophical Approaches

* Absurdism - a search for meaning is inherently in conflict with the actual lack of meaning, but that one should both accept this and simultaneously rebel against it by embracing what life has to offer
  * Live in constant revolution, reject hope after death, live with a sense of passion for life
* Existentialism - through a combination of awareness, free will, and personal responsibility, one can construct their own meaning within a world that intrinsically has none of its own
  * Nihilism - not only is there no intrinsic meaning in the universe, but that it’s pointless to try to construct our own as a substitute.
* Stoicism - live according to virtue; important tenets:
  * Thoughts, not events, cause pain
  * Don't struggle with what you don't have control over
  * Life is short, don't waste your time with people you don't like or tasks you don't enjoy
  * Keep only valuable people in your social circle
  * Everyone has flaws and don't amplify one person's opinion about you to the detriment of yourself
  * Measure accomplishments against yourself and not others
  * Set reasonable expectations, and don't cherry-pick emotions
    * "Only a madman goes out to look for figs in winter"
    * Heightened expectations can create a lot of shame and guilt about experiencing negative emotions. In ACT this is called "dirty pain": we don't just experience anger or sadness, but we add to it an additional layer of suffering.

### 🪷 Buddhism

* Carpet Shoes Analogy - If you want to walk on a carpet all day, it’s harder to cover the world in carpet than it is to wear carpet shoes. (ie, reduce needs you have to fulfill to increase likelihood they get met)
* Kintsugi - bowls that shattered, but are repaired by golden glue to be made whole again. (ie, don't assume because something is broken that it's useless)
* Oubaitori - imagine there are four different flowers: cherry, apricot, peach, and plum. Which one is "better" and which one is "falling behind"? (ie, comparisons with others are pointless because each flower has its own journey, focus on your individual growth journey)
* Ukeireru - accepting the realities that surround you, too – your relationships, your roles in the communities you’re a part of, and the situations you face – rather than fighting them
* Vasana - Imagine your mind is like a big library, and every book in it is a memory or experience you’ve had. Now, Vasana is like a bookmark that keeps track of certain books you’ve read a lot. These books are your habits or tendencies. Just like you might automatically reach for your favorite snack without thinking, Vasana is the automatic way you might react to things because you’ve done it that way before. It’s like a mental shortcut your brain takes based on past experiences.


Other Reflections:

1. You cannot practice non-attachment. You can only show your mind the suffering that attachment creates. When it sees this clearly, it will let go.
2. Finding your true self is an act of love. Expressing it is an act of rebellion.
3. A sign of growth is having more tolerance for discomfort. But it’s also having less tolerance for bullshit.
4. Who you are is not your fault, but it is your responsibility.
5. Procrastination is the refusal or inability to be with difficult emotions.
6. Desires that arise in agitation are more aligned with your ego. Desires that arise in stillness are more aligned with your soul.
7. The moment before letting go is often when we grip the hardest.
8. You don’t find your ground by looking for stability. You find your ground by relaxing into instability.
9. What you hate most in others is usually what you hate most in yourself.
10. The biggest life hack is to become your own best friend. Everything is easier when you do.
11. The more comfortable you become in your own skin, the less you need to manufacture the world around you for comfort.
12. An interesting thing happens when you start to like yourself. You no longer need all the things you thought you needed to be happy.
13. If you don’t train your mind to appreciate what is good, you’ll continue to look for something better in the future, even when things are great.
14. The belief that there is some future moment more worth our presence than the one we’re in right now is why we miss our lives.
15. There is no set of conditions that leads to lasting happiness. Lasting happiness doesn’t come from conditions; it comes from learning to flow with conditions.
16. Spend more time cultivating a mind that is not attached to material things than time spent accumulating them.
17. Sometimes we need to get out of alignment with the rest of the world to get back into alignment with ourselves.
18. Real confidence looks like humility. You no longer need to advertise your value because it comes from a place that does not require the validation of others.
19. High pain tolerance is a double-edged sword. It’s key for self-control, but can cause us to override the pain of being out of alignment.
20. Negative thoughts will not manifest a negative life. But unconscious negative thoughts will.
21. To feel more joy, open to your pain.
22. Bullying yourself into enlightenment does not work. Befriending yourself is how you transcend yourself.
23. Peak experiences are fun, but you always have to come back. Learning to appreciate ordinary moments is the key to a fulfilling life.
24. Meditation is not about feeling good. It’s about feeling what you’re feeling with good awareness. Plot twist: Eventually that makes you feel good.
25. If you are able to watch your mind think, it means who you are is bigger than your thoughts.
26. Practicing stillness is not about privileging stillness over movement. It’s about the CAPACITY to be still amidst your impulses. It’s about choice.
27. The issue is not that we get distracted. It's that we're so distracted by distractions we don't even know we're distracted.
28. There are 3 layers to a moment: Your experience, your awareness of the experience, and your story about the experience. Be mindful of the story.
29. Life is always happening in just one moment. That's all you're responsible for.
30. Your mind doesn’t wander. It moves toward what it finds most interesting. If you want to focus better, become more curious about what's in front of you.
31. Life continues whether you’re paying attention to it or not. I think that is why the passage of time is scary.
32. Meditation can quickly become spiritualized suppression. Be careful not to use concentration to avoid what is uncomfortable.
33. One of the deepest forms of peace we can experience is living in integrity. You can lie to other people about who you are, but you can’t lie to your heart.
34. Be careful not to let the noise of your mind overpower the whispers of your heart.
35. Monks love to fart while they meditate. The wisdom of letting go expresses itself in many forms.
36. You can't life-hack wisdom. Do the work.

## 🆗 Radical Acceptance

Acceptance is acknowledging a particular situation is indeed happening, and making space for any part that screams "no" at the situation. The goal is to keep pain from turning into suffering. Myths:

* Acceptance does not mean we're OK with a situation or agree with it
* Acceptance does not mean we stop trying to change it, or lead to laziness, complacency, or lack of drive
* Acceptance is not failure

Mantras:

* My present moment is the only one I have any control over. 
* Fighting this emotion won’t help. It’s just something I’m experiencing right now. 
* The reality I’m facing is a fact I will have to deal with, even if I don’t like it. * I wish things were different, but I cannot change what happened in the past. 
* I can’t control everything that will happen. 
* A million variables outside of my control have led to this moment. 
* The thoughts I’m currently having will not hurt me. 
* I struggle with certain things more than other people do, and that might not ever change.

Practice:

* Observe that you are questioning or fighting reality
* Remind yourself reality is what it is and cannot be changed
* Remind yourself there are causes for the reality
* Use self-talk, relaxation, mindfulness, and/or imagery to accept with your whole self
* List behvaviors you would do if you accepted the facts and do them anyway
* Imagine in your mind's eye what you would do if you accepted what seemed unacceptable
* Attend to body sensations as you think about what you need to accept
* Allow disappointment, sadness, or grief
* Acknowledge life is worth living despite and even when there is pain
* Do pros and cons if you find yourself resisting practicing acceptance

## 😊 Self-Compassion

Self-compassion is being kind and understanding when confronted with personal failings. It means that you act the same way toward yourself when you are going through a tough time that you would act towards a dear friend. Generally used to let go of perfectionism.

Involves the following:
	
* Self-kindness and practicing non-judgment: being kind and understanding toward yourself. 
  * Ex: It’s okay that you failed that test. It was really hard; Emotions and thoughts are morally neutral, and it's okay to just let them be.
* Mindfulness and avoiding over-identification: having a balanced reaction to painful thoughts and feelings, not underreacting or overreacting. 
  * Ex: I notice I’m feeling sad right now; I am stuck in a difficult situation and doing my best to make it through; My "worst" impulses do not define me as a person.
* Common humanity and avoiding isolation: seeing one’s experience as part of the larger human experience. 
  * Ex: Everyone fails from time to time; Other people are found COVID lockdowns difficult to follow; If you find safe people to confide in, you'd feel less alone


Challenges:

* **Backdraft** - when you try to be compassionate to yourself but end up feeling worse (this is a normal thing to have happen)
* Insecure attachment styles cause fear/aversion to self-compassion
  * Contentment system is weaker (can't rely on past memories of support to self-soothe)
  * Highly active threat detection systems cause children to see need for compassion as a sign they are weak, so they resist any expression of compassion due to concerns of being rejected, harshly criticized, or feeling undeserving.
* Practice **behavioral self-compassion** when the fear of self-compassion is high. This means focusing on what is needed in the moment, like taking a break from work when stressed, rather than mental exercises.
  * What do I need to feel safe? To be comforted, soothed, validated? To protect, provide for, motivate myself?
* Low self-worth; not believing you are worthy of love as you are, or deserving of any nice things

Practice:

* Awareness of emotions and self-criticism
* Reframe judgmental thoughts as factual ones
* Offer comfort, love, and support
* Say the following mantras:
  * "You were just a child. You did the best you could using the tools you'd learned. You had to shoulder things that most adults would struggle with. Things were out of your control. You weren't selfish for choosing to protect yourself." 
  * "You didn't deserve that."

### 💗 Self-Love

Self-love is a more stable construct than self-compassion; while you can choose to be compassionate towards yourself in any moment, self-love is probably something that you will need to build up.

* Find what you enjoy doing
  * "What do I want to do?" vs "What should I do?"; if unsure, follow your envy
  * Schedule fun into your calendar (else you'll end up mindlessly scrolling)
  * Be a satisficer (want what you have) and not a maximizer (trying to have what you want)
* Be aware of all of your emotions (can't mute sadness and also feel joy)
* Pursue connections with others
  * Beware relational bypassing - where relationships are overlooked in the pursuit of self-love
* Increase expressed delight
  * Take yourself out on dates
  * Listen to self-hypnosis tracks
  * Write self a love letter
  * Start gratitude practice
  * Work on your inner critic
  * Identify parts of you that function in secure ways
  * Let yourself laugh and seek out humor
* Manage internal conflicts and triggers
  * Engage in dialogue with inner critic
  * Seek support through books, programs, training, etc
  * Mindful deep belly breathing to change your arousal system
  * Cognitive reframing

## ✨ Values-Driven Living

Values are enduring beliefs upon which a person acts.

Types of values:

* Résumé virtues - valued in the contemporary marketplace (the high test scores achieved by a student, the professional accomplishments pulled off by an adult, etc). They are the skills that are met with bigger paychecks and public approbation. They require comparison with others.
* Eulogy virtues - the aspects of character that others praise when a person isn’t around to hear it: humility, kindness, bravery. Eulogy virtues are ethical and spiritual, and require no comparison. Our society exalts the résumé virtues, but it overlooks the humbler eulogy virtues. Still, he writes, we know at our core that this second category of values is what matters more. 

Determine values (top 15 and top 2) from list below:

* Accountability
* Achievement
* Adaptability
* Adventure
* Altruism
* Ambition
* Authenticity
* Balance
* Beauty
* Being the best
* Belonging
* Career
* Caring
* Collaboration
* Commitment
* Community
* Compassion
* Competence
* Confidence
* Connection
* Contentment
* Contribution
* Cooperation
* Courage
* Creativity
* Curiosity
* Dignity
* Diversity
* Environment
* Efficiency
* Equality
* Ethics
* Excellence
* Fairness
* Faith
* Family
* Financial stability
* Forgiveness
* Freedom
* Friendship
* Fun
* Future generations
* Generosity
* Giving back
* Grace
* Gratitude
* Growth
* Harmony
* Health
* Home
* Honesty
* Hope
* Humility
* Humor
* Inclusion
* Independence
* Initiative
* Integrity
* Intuition
* Job security
* Joy
* Justice
* Kindness
* Knowledge
* Leadership
* Learning
* Legacy
* Leisure
* Love
* Loyalty
* Making a difference
* Nature
* Openness
* Optimism
* Order
* Parenting
* Patience
* Patriotism
* Peace
* Perseverance
* Personal fulfillment
* Power
* Pride
* Recognition
* Reliability
* Resourcefulness
* Respect
* Responsibility
* Risk-taking
* Safety
* Security
* Self-discipline
* Self-expression
* Self-respect
* Serenity
* Service
* Simplicity
* Spirituality
* Sportsmanship
* Stewardship
* Success
* Teamwork
* Thrift
* Time
* Tradition
* Travel
* Trust
* Truth
* Understanding
* Uniqueness
* Usefulness
* Vision
* Vulnerability
* Wealth
* Well-being
* Wholeheartedness
* Wisdom


## 📖 Vulnerability

*Until I was almost thirty my conversation seldom included anything but joke-telling and sports-talk. This superficiality made me feel perpetually lonely, even though I was popular whenever I stayed anywhere long enough to make acquaintances.*

*I was laconic because my family life convinced me it was unwise to talk about the vulnerable subjects that allow intimacy to grow between people. Talk about feelings, needs, weaknesses, or disappointments was routinely ridiculed in my house. So too was talk about hopes, dreams, and accomplishments.*

Vulnerability is what you experience when you take a risk, or leave yourself open to emotional harm. It’s what you might feel when you confess your feelings for someone or ask for feedback on a deeply personal issue—it’s the knowledge that you’ve exposed an emotional weak spot and that someone could use it to hurt you.

Challenges:

* **Faux Vulnerability** - revealing facts about yourself that sound vulnerable to those on the outside but doesn't leave yourself open to emotional harm. Common with those with an avoidant attachment style.
* Don't keep being vulnerable with people who have hurt you when you're vulnerable

Practice:

* Find when it's safe to be vulnerable
  * The other person is curious about you
  * They're vulnerable with you
  * When they listen you feel heard
  * They affirm in the moment
  * They demonstrate integrity when they share other people's business
  * They consistently show up for you
* Recognize barriers to vulnerability   
  * Foreboding joy - always imagining worst-case scenario
  * Perfectionism
  * Numbing
  * Emotional dumping and oversharing
* Be willing to be vulnerable first
  * Show vulnerability through demeanor, not just words (cry, shake, etc)
  * Others won't judge you for your vulnerability, may help you be perceived more positively as authentic and honest
  * Being invulnerable doesn't abolish weaknesses, just also hides strengths
  * Watch out for beautiful mess effect, where we worry we will be judged harshly when we're vulnerable with others
  * Don’t keep being vulnerable with people who have hurt you when you’re vulnerable.
* Turn to friends for support when needed
  * You will need help in order to recover from deeply troubling emotional situations; you cannot heal in a vacuum on your own
* Scaffolding vulnerability by disclosing to someone you trust, and then being vulnerable with someone who you’re less sure of.
* Be willing to show off your work to others:
  * Do not feel like you need to be a genius; being in a community with people that do what you want to do, even if you're a total amateur, is fine. Everyone has to start somewhere
  * Share something small every day, preferably with your real name
  * Be willing to share what you're interested in with others
  * Teach what you know and be willing to share your trade secrets, and learn to do so in a compelling way
  * Stick around and continue sharing, don't let burnout/low points stop you

# Adaptive Activities

1. Be proactive - focus on what you CAN control, not complaining about what you can't.
2. Begin with the end in mind - what will you be able to say about yourself once you are dead? Focus on that when you are figuring out your life's goals.
3. Put the first thing first - focus on relationships and fitness, less on TV and mindless internet browsing.
4. Think win-win - collaborate with others together in a mutually beneficial way, rather than be spiteful towards others for whatever reason.
5. Seek first to understand, then to be understood - Nobody cares if you work hard; they care about what value you can provide to them. Frame tasks/accomplishments in those terms rather than egoistic ones.
6. Synergize - Work together with others when the situation arises; the whole is greater than the sum of its parts in many situations.
7. Sharpen the Saw - Spend time on healthy activities such as exercising, meditating, eating healthy, and more, as these are essential towards being the best you can be and providing a strong foundation for you mentally, physically, and emotionally.

## 🗣️ Affirmations

A reflection on personally relevant values.

* Try and use affirmations that are believable and don't feel fake.
* Write down your chosen affirmations on a sticky note or scrap of paper, and hang it somewhere you will see it often, like your bathroom mirror. Each time you pass the sticky note, recite the affirmation(s) out loud

## 🫁 Breathing

Methods:

* **Downregulating** - use when highly anxious. Make out breaths longer than in breaths.
  * When inhaling, take a small second breath to inhale slightly extra before breathing out through the mouth to slow your heartbeat and ground you quicker.
* **Upregulating** - use when in a freeze response. Make in breaths longer than out breaths.

## 😭 Crying

How to most effectively cry:

* open throat 
* let sound come from belly 
* relax face 
* relax chest and belly 
* go into feeling of pain discomfort in chest and belly with attention 
* allow recall of painful memory to arise 
* allow emotional pain to arise 
* imagine blowhole in top of head to allow excess energy tension buildup to release 
* relax jaw 
* stay with sensations 
feel the pain 

## ✍ Journaling 

Strategies:

* **Morning Pages** - Write by hand three pages of an A5 notebook words that nobody will ever see. Just do stream of consciousness; the words can be whatever you want.

Note:

* Beware ‘dataism’ - in case where people are shown the data, people might ‘edit their experiences and negotiate with the data’ she says. Yes, they might say: I remember now, I was feeling stressed out that day I had the higher heart rate. They are persuaded to ‘retell the narratives of their life to fit the data’, instead of trusting themselves. 

### Prompts

#### Social

* What type of people do I enjoy spending time with?
* Why do I enjoy those specific qualities in people?
* Do I seek out people similar as I, or different from me? Why is that?
* Do I have many friends as I just described? Why or why not?
* How many close friends do I want based on the amount of time I have?
* What would those close relationships look like? What would be the biggest aspects? (talking, shared activities, working on projects together, laughter, storytelling, playing games, etc.)
* What are two of the most favorite things I enjoy doing with others?
* Where have I met most of the friends I currently have? (family, work, community, childhood, online, etc.)
* What does where I met these friends tell me about myself?
* Why am I still friends with those people?
* What is the single biggest attitudinal change I’d like to make when with people? (be more myself, be more out-going, be more honest, initiate more conversations, be more comfortable, be more open, be funnier, interrupt less, initiate more activities, etc.)

#### Emotional

* List three situations and/or times when you were the most happy in your life. Specific instances... What elements were present when I felt that way? How was I feeling about myself during those times?
* What do I fear most in my life right now? Why? What would it mean if that happened?
* When do I feel the most angry or frustrated? What is it about those situations that I feel that way?
* What is my definition of love? (not a dictionary’s)
* What are my primary beliefs about love? (it’s easy, scary, short-lived, feels good, not possible, difficult, etc.) Where/when did I acquire those beliefs? Do I still believe them? Why or why not?
* Do I have much control over my emotions? Why or why not?
* What emotions do I want to feel most of the time?

#### Financial

* What beliefs did I “take on” from my parents in regards to money? (it’s difficult to get, it’s scarce, you
should only have so much, it’s easy to make, having it /not having it says something about me, live for the moment, give it away, I’ll never have enough, it’s a secret, saving is important, etc)
* What does money mean/represent to me? (security, aliveness, freedom, love, peace of mind, etc)
* Do I feel peaceful or anxiety in regards to money? Why do I feel that way about it?
* How much money do I feel I deserve to make a year? Why that amount?
* What would it mean to me if I made more or less than that amount? Why do I believe that?

#### Career

* What types of things did I enjoy doing as a child? (building things, drawing, sports, writing, solving puzzles, being with animals, my chemistry set, organizing games, talking, anything physical, playing
house, cowboys and Indians, etc) Do I do anything today that has similar qualities to it?
* If you are currently working, what about you work do you love? What do you dislike?
* What do you see as your ideal job? Why?
* What is my definition of success? (not the dictionary’s)

#### Personal

* What skills have I acquired that I’m proud of?
* What accomplishments am I proud of?
* Beginning when I was a child, what are the 5 most significant events in my life? Why did I make them significant?
* What are five of my greatest strengths?
* If I was to receive an award, what would I want that award to be for? Why that?
* If I was to pick out a general theme that showed up often while answering these questions, what would that theme be? What does it mean? How do I feel about that?

## ⛳ Leisure 

Two types of leisure:

* **Terminal Leisure** – leisure that takes place purely for enjoyment. 
* **Instrumental Leisure** – leisure that might serve a larger purpose, like making friends or staying healthy, and therefore feels more productive. 

The ability to enjoy terminal leisure is a stronger predictor of wellbeing than enjoyment of instrumental leisure, the study showed. 

## 🧘‍♀️ Mindfulness 

Mindfulness can harm if done recklessly. Practice in moderation as you slowly build tolerance. Hindrances include Desire, Aversion, Sleepiness, Restlessness, and Doubt.

Strategies:

* Detachment - experiencing our feelings without allowing them to control us
* Radical acceptance - see above
* Embodiment - being fully in your body and its experiences; note that is different than hyperawareness of the body
  * Disembodiment - imagine your head being a balloon, with the knot of the balloon being at the base of the head/neck, keeping the "self" trapped in your balloon head and out of her body.
  * Embodiment - imagine untying the balloon knot and letting all the air (self) from the balloon flow down from the neck and into the chest, arms, hips, etc."
* Window of Tolerance - describes an optimal range of emotional arousal within which an individual can effectively cope with stressors and engage in adaptive behaviors. Think of it as a “comfort zone” where you can manage challenges without feeling overwhelmed or shutting down.
  * Hypoarousal
    * Freezing during an exam
    * Feeling numb after a breakup
  * Hyperarousal
    * Panic during a presentation
    * Angry outburst during group project

Types of Meditation:

* Presence / Mindfulness - improves attention, gray matter in prefrontal cortex, and body awareness (after 6 months of training regularly)
  * Body scans
  * Breathwork
  * Pay attention to present moment
  * Walking meditation
* Affect - improves attention, compassion, gray matter related to supramarginal gyrus (improved empathy), social stress and connection
  * Loving-kindness meditation
  * Compassion
  * Gratitude
  * Accept difficult emotions and increase motivation to be kind towards others
* Perspective - improves theory of mind, gray matter in temporo-parietal junction, social stress and connection,
  * Become aware of own thinking
  * Gain perspective on personality
  * Taking perspective of others

## ☺️ Self-Soothing

*"People need a reasonable amount of comfort every single day."*

Method to reduce the intensity of negative emotions, using each of the senses.

### Sight

* Low lighting
* Soothing colors
* Sleeping masks
* Coloring books
* Collages

### Sound

* Calming noise
* ASMR
* Nature sounds
* Guided meditations
* Binaural beats

### Smell

* Aromatherapy
* Fresh air
* Candles
* Comforting smells

### Taste

* Strong flavors
* Warm drinks 
* Eating slowly
* Nostalgic flavors

### Touch

* Soft things
* Cuddling
* Massage
* Hot shower
* Weighted blanket

### Vestibular

Processes balance and movement

* Yoga
* Rocking (on swing, chair, hammock, etc)
* Walking
* Running
* Spinning

### Proprioception

Processes balance and coordination

* Push/Pull/Lift activities
* Chewing
* Dance
* Kneading/Squeezing

### Interoception

Processes internal body and emotional states

* Hot and cold sensations
* Body scans
* Breathwork
* Mindfulness
* Send messages of safety and love

## 1️⃣ Solitude

Benefits:

* Improved self-awareness
* Enhanced creativity and productivity
* Rest, recovery, and reflection

## 💤 Sleep 

Sleep Hygiene:

* Get into bed only when sleepy, not tired.
* Make room dark, cool (65F), and quiet (besides white noise/fan)
* Use bed only for sleep
* Don't check time
* Don't lay in bed for more than 20 minutes
* Keep relaxing activities nearby if you can't sleep 
* Set sleep and wake time
* Get sunlight exposure after waking up
* Limit/eliminate naps
* Have pre-bedtime routine
* Don't take problems to bed
* Exercise earlier than 4 hours before bedtime
* No food within 3 hours of bedtime
* No liquids within 2 hours of bedtime
* No work within 2 hours of bedtime
* Caffeine before noon, alcohol never
* Don't sleep in more than 2 hours on weekends
* Limit screen time an hour before bedtime
* Don’t sleep in after tough night
* Don’t rearrange life around sleep

Fall asleep quickly:

* Cognitive Shuffling: start with a word like ocean and think of all words you can that start with O; then go to C and think of all letters that start with C, and so on. This works because it's mundane and mimics the first stage of sleep


## 🛋️ Therapy

* Cognitive Behavioral Therapy (CBT)
* Eye Movement Desensitization Reprocessing (EMDR)
* Ideal Parent Figure
* Mindfulness-Based Stress Reduction (MBSR)

### 🤝 Acceptance and Commitment Therapy (ACT)

* Cognitive Defusion
  * Relating to your thoughts in a new way, so they have much less impact and influence on you
  * Think of the brain as similar to a sushi conveyor belt: it presents a constant stream of dishes that travel past us. Some of them look attractive and some do not. We do not have to pick every single one up and eat it. The acceptance part in ACT is to learn to let the less nourishing dishes float past us without engaging.
* Expansion
  * Make room for unpleasant feelings and sensations instead of trying to suppress them or push them away
* Notice Yourself Noticing Situations (The Observing Self)
  * ie, you are not your thoughts
* Connect with the Present Moment
* Clarify your Values 
* Make Values-Driven Decisions

Strategies:

* I’m Having the Thought That - awareness between having the thought and getting caught up in the narrative
* Musical Thinking - sing-song in head for negative thoughts
* Naming Stories - label stories when your brain begins to tell them; benefits are like labeling emotions
* Thank Mind - when brain continues to retell/rehash narratives
* Silly Voices Technique - Hear thoughts in a silly character's voice, like a cartoon character
* TV Screen - imagine thoughts are like a TV show. Make it a specific genre, with specific music and acting, to help detach self from thought.
  * Distort image by flipping upside down, spinning it around, stretch image beyond bounds of screen, make black and white, etc.
  * If thoughts are more like a movie clip, play in slow motion, play backwards, play forward in double speed
  * Apply silly subtitles or voiceovers to the movie
  * Add a ridiculous musical soundtrack
  * Shift the location and the genre
* Demons on the Boat - imagine demons are around you and allowed to be around all the ship. Don't try and keep them below deck in repression. 
* Clouds in the sky –  see your mind as a sky and thoughts are just clouds passing you by.
* River stream – Everything is in a constant state of flux – and your thoughts, feelings, and experiences flow through consciousness in the same way water flows through a stream. Your mind is the river and your thoughts are just things flowing down it. Give it time and it will pass.
* Suggestion box – Your mind is genuinely trying to help and serve your best interests, but it doesn’t always suggest the best ideas, and you have the power to veto any thought you have
* Feeding the wolves - if one wolf represents light and hope and the other represents darkness and despair, the wolf you feed will win
* Burning your thoughts – One fun exercise for overcoming negative thoughts and stripping them of their power is to burn away negative thoughts. Just get a piece of paper and a pen, then write down 5-7 negative thoughts that have been occupying your mind lately. Then get a lighter and find a safe place to burn the piece of paper
* Passengers on a bus - you visualize yourself as a bus driver, and every thought you have is a passenger that gets on (and off) the bus.
* Brain Drain - Give yourself 5-10 minutes to write whatever comes to your mind, without any self-filtering or self-editing. This completely “stream of consciousness” writing can often help to purge thoughts that have been hanging around in your head (even ones that you may not be aware of). 

### 🧠 Brainspotting

In a nutshell, through some quirk of the brain, stuck trauma can actually be accessed through the visual cortex. Brainspotting takes advantage of this to help process trauma. By identifying eye positions correlating with emotional activation, healing and release through the mind-body connection can occur.

### 🔎 Cognitive Behavioral Therapy (CBT)

Focuses on modifying dysfunctional emotions, behaviors, and thoughts by interrogating and uprooting negative or irrational beliefs.

Common negative beliefs (also known as core wounds):

* I am worthless / unworthy
* I deserve pain / suffering / misery / punishment / disrespect
* I am stupid
* I am weak / helpless / unsafe / powerless / stuck
* I am inadequate / not good enough / not doing enough
* I am a failure
* I am broken / defective
* I am a bad person
* I can't trust others
* I am unwanted / unlovable / disliked / don't belong
* I don't deserve to be happy
* I am abandoned / alone / disconnected / excluded / rejeected
* I am weak and helpless
* I am unseen and unheard
* I don't matter and am unimportant
* My life will always be like this, nothing will ever help, my life sucks, I'll never get better
* Everyone has moved on without me
* I am a burden

Signs these beliefs negatively impact you:

* Entering relationships in the hopes of finding what you lack inside in the other person
* Feeling inadequate
* Feel a sense of abandonment, resentment, or betrayal from others regularly
* A perfectionistic attitude towards life (i.e., you gain your self-esteem from the outcome of your actions instead of the intention behind your actions)
* Have chronic anxiety that comes as a result of anticipating the emotional pain of being found unworthy, which deep down you think is true
* Repeating the same old mistakes in relationships because you’re stuck in negative unconscious programming, and you don’t feel courageous enough to make a change.
* Finding happiness in your misery because it’s a source of attention in the form of sympathy from other people.
* Having a large, unexplored Shadow Self.
* Behaving in dishonest and inauthentic ways that are not true to the person you really are to gain the acceptance of others.
* Emotional numbness, a sense of meaninglessness and disconnection from the world around you. In a sense, this is the ultimate defense mechanism: to feel nothing.
* Strong inner critic
* Feeling like an outcast, and you can never quite fit in with anyone. Instead of appreciating your uniqueness and seeing it as an opportunity, you see it as a curse.

Ways to change beliefs:

* Understand all your beliefs. Which support growth and which don't?
  * Notice unhealthy patterns in your life and recurrent challenges. Could a limiting belief be the root cause?
  * When a negative belief shows up, ask "according to whom?" to narrow down where the standard originally came from
* Catch thoughts when they occur
* Question the thought when it comes in. Is it true, harmful, or exaggerated?
* Change it - use evidence gathered to replace the belief with a more compassionate message
* 5 Whys - write down what your problem is, ask "why?" 5 times to get to the root of the issue, and find reasonable solution to what you find
* Beware Approval Addiction - your worth cannot be determined by whether other approve of you or not; needs to come from within. Remember rejection is not your fault, rewrite your silent assumptions about yourself and the world, use cost-benefit analysis on if it's worth maintaining current behavior, and develop a blueprint of self-respect
* Practice emotional accounting - recognize negative thoughts, what emotions are associated, what cognitive distortion they fall under, give a rational response to the toxic thought (self-defense), and develop realistic self-evaluation system to tackle the system

Positive beliefs to develop instead:

1. I want to develop a more consistently loving and accepting relationship with myself. I want an increasing capacity for self-acceptance.
2. I want to become the best possible friend to myself.
3. I want my relationships to be based on love, respect, fairness, and mutual support.
4. I want to expand into full, uninhibited self-expression.
5. I want to attain the best possible physical health.
6. I want to cultivate a balance of exuberance and peace.
7. I want to attract to myself loving friends and loving community.
8. I want increasing freedom from toxic shame.
9. I want increasing freedom from unnecessary fear.
10. I want rewarding and fulfilling work.
11. I want a healthy amount of peace of mind, spirit, soul, and body.
12. I want to increase my capacity to play and have fun.
13. I want to make plenty of room for beauty and nature in my life.
14. I want sufficient physical and monetary resources.
15. I want a fair amount of help (self, human, or divine) to get what I need.
16. I want divine love, grace, and blessing.
17. I want a balance of work, play, and rest.
18. I want a balance of stability and change.
19. I want a balance of loving interaction and healthy self-sufficiency.
20. I want full emotional expression with a balance of laughter and tears.
21. I want sexual satisfaction.
22. I want to express my anger in effective and nonabusive ways.
23. I want all this for each and every other human being as well as myself.


### Dialectical Behavioral Therapy (DBT)

Meant for people who struggle with undercontrol and people with anxious attachment styles. A bit over-obsessed with acronyms, but there are 4 main components to treatment:

* Distress Tolerance
* Mindfulness
* Interpersonal Effectiveness
* Emotional Regulation

DBT Legitimate Rights:

	1. You have a right to need things from others
	2. You have a right to put yourself first sometimes
	3. You have a right to feel and express your emotions and pain
	4. You have a right to be the final judge of your beliefs and accept them as legitimate
	5. You have a right to your opinions and convictions
	6. You have a right to your experience, even if it's different from other people
	7. You have a right to protest any treatment or criticism that feels bad to you
	8. You have a right to negotiate for change
	9. You have a right to ask for help, emotional support, or anything else you may need (though you may not always get it)
	10. You have a right to say no; it doesn't make you bad or selfish
	11. You have a right not to justify yourself to others
	12. You have a right to choose not to respond to a situation
You have a right to occasionally disappoint or inconvenience others

DBT suggests using distraction in times of distress

* Radical Acceptance
* Distraction, Self Destructive (fling hairtie into wrist, etc)
* Distraction, Pleasurable Activity (walk, journal, etc)
* Distraction, Focus on someone else (help a friend with something)
* Distract with thoughts (recall happier times)
* Distract and leave situation
* Distract with tasks and chores
* Distract by counting (breathing, brain teasers, etc)

Dialectical behavioral therapists often distinguish between willfulness (trying to fight reality, common with systemic shame) and willingness (acknowledging and working with reality on its own terms). 

Willfulness includes bitterness, obsession, rumination, frustration, feeling "stuck", why a situation "should not be", sticking rigidly to a plan, and thinking a great deal about the past. Identify willfulness with the following questions:

* What are some unspoken “rules” that I still let guide my life? 
* Which of these rules no longer serve me? 
* What can I do less of? 
* What facts of my life am I still trying to make not be true? 
* What can I give up on for now? 
* What unpleasant truths can I decide to just live with? 
* What can I stop trying to make work?

Willingness includes lightness, acceptance, adaptation, mourning, feeling relaxed, asking "what's next?", improvising based on current information, and paying attention to the present. 

### 👁️ EMDR

*There is a difference between knowing and understanding. I had known that this wasn’t my fault. EMDR unlocked the gate to the next realm, toward understanding. The difference is one between rote memorization and true learning. Between hypothesis and belief. Between prayer and faith. It seems obvious now—how can there be love without faith?*

* Floatback Technique - Bring to mind a negative cognition and recent event. Where do you feel it in your body? As you think of the recent incident and the negative cognition, notice the feelings in your body, and let your mind float back to childhood. What memory comes to mind when you felt that way? If something automatically comes to mind, then write it down in your Memory column along with your age and the SUD level. Using cue words, list the earliest memories and the ones with the highest SUD level.
* Butterfly Hug - Cross your arms in front of you with your right hand on your left shoulder and your left hand on your right. Then you tap your hands alternately on each shoulder slowly four to six times. To try it, bring up the image of the safe or calm place along with that positive word that you’ve connected with it and allow yourself to go into that state of safety or calm. And when you have that sense, tap alternately on your thighs or with the Butterfly Hug four to six times, then stop and take a breath and see how it feels.

### ☠️ Existential Therapy

When it comes to finding (or creating) meaning in life, existential therapists look to what they call the four realms of human experience:

* The **physical realm**, which guides how we view our physical surroundings, our bodies, and how we think about our own deaths. 
  * How can I live my life fully, knowing I may die at any moment?
  * What helps you feel real, in touch with your body and surroundings?
    * Ex: Learning, hands-on skills, self-care
* The **social realm**, which guides how we think and feel about other people, as well as the culture(s) to which we belong. 
  * What are other people there for?
  * What helps you feel recognized and appreciated as you really are?
    * Ex: Shared passions, challenges, vulnerability.
* The **personal realm**, which guides our understanding of ourselves, including the life stories we tell about our past experiences, our present situation, and what we hope for our futures. 
  * How can I be me?
  * Which ways of spending time do I never regret?
    * Ex: Hobbies, creative endeavors, childlike wonder, etc.
* The **spiritual realm**, which guides how we feel about the unknown and uncertain, as well as our core values and how we think the world ought to be. 
  * How should I live?
  * What helps me see that I am a part of something larger than myself?
    * Ex: Mentorship, creative work, volunteering

### 👶 Inner Child Work

*"No parent does a perfect job, so no parent does a complete job. Every adult needs to finish the job of parenting themselves."*

Generally done through reparenting yourself. A common method is the Ideal Parent Figure Protocol, where you release negative introjects (parental figures and values) you internalized as a child.

* Recognize you are separate from your parents, and can live life according to your values, not theirs
* Forgive your parents. Doesn't mean condoning their actions or forgetting, but letting go of anger and resentment towards them.
* Build a relationship with yourself (learning who you are, what you want out of life, accepting and loving yourself despite flaws)
* Develop a new internal parent to provide love and guidance you need (based on either real or fictional character)

Pillars of reparenting:

* Emotional regulation
* Loving discipline - setting boundaries, saying no, stating needs, following routines
* Self-care - healthy diet, sleep, meditation, journaling, nature, etc
* Child-like wonder - creativity + imagination; joy + spontaneity + playfulness. 
  * Play more often; the opposite of play is depression (childhood movies, TV shows, video games, books, hobbies, treating yourself)
  
Exercises:

* Reparenting journal exercise
  * How does you show up in the world as a child? Who were you at your best? How did you interact with others and the world around you? Write down 5-20 traits describing how you were as a child.
  * How do you show up in the world today? Who are you at your best? How do you interact with others and the world around you? Write down 5-20 traits describing your ideal inner adult.
  * Allow these two parts to have a conversation with each other to better understand one another. Let the inner child take the lead on the conversation and make sure they're heard first and foremost

#### Self-Mothering

Heals the wounds of self-neglect.

* I want you.
* I love you.
* I’ll take care of you.
* You can trust me.
* I’ll be there for you; I’ll be there even when you die.
* It is not what you do but who you are that I love.
* You are special to me.
* I love you, and I give you permission to be different from me.
* Sometimes I will tell you “no” and that’s because I love you.
* My love will make you well.
* I see you and I hear you.
* You can trust your inner voice.
You don’t have to be afraid anymore.

#### Self-Fathering

Heals the wounds of abuse. Self-fathering gestates assertiveness and self-protection. It includes confronting external or internal abuse, and standing up for the adult child’s rights.

* I love you.
* I have confidence in you. I am sure you can do it.
* I will set limits and I will enforce them. (“You do have to go to school.”)
* If you fall down, I will pick you up. (Learning to ride a bicycle is a common example of this experience with father.”
* You are special to me. I am proud of you.
* (Especially for women) You are beautiful, and I give you permission to be a sexual being.
* (Especially for men) I give you permission to be the same as I am AND permission to be more than I am AND permission to be less than I am.


### 👨‍👩‍👧‍👦 Internal Family Systems (IFS)

IFS believes that a person's personality is made up of various parts:

* Core Self / Wise Adult
  * Purpose: Creative, Curious, Compassionate, Confident. In more polarized systems, parts generally don't trust the Core Self's leadership and wisdom
  * Goal: differentiate the core self from other blended parts, improve self-leadership across your parts, improve inner harmony and reduce polarization between parts
* Exiles
  * Purpose: Hold disowned and painful feelings and traumatic memories. They are most commonly child and teenaged parts.
  * Goal: be acknowledged, unburdened, reassured, and nurtured by the self. Stop hijacking the system in times of distress.
* Managers
  * Purpose: Suppress and contain exiled parts, Protect the system and focus on daily living tasks
  * Goal: Let go of extreme roles, adapt role to present day needs, and work under Core Self leadership, be more trusting of Core Self
* Firefighters
  * Purpose: Use extreme measures to distract, dissociate, and numb the system when the Exiles are triggered
  * Goal: No longer needed to perform their extreme roles

Goals of IFS:

* Liberate parts from the roles they’ve been forced into, so they can be who they’re designed to be.
* Restore trust in the Self and Self-leadership.
* Reharmonize the inner system.
* Become more Self-led in your interactions with the world.

### 📔 Narrative Therapy

People are made up of many narratives.  Narrative therapy begins with investigating your narrative and bringing it to your awareness.

* Externalizing
  * Viewing a problem as separate from yourself
* Deconstructing
  * Be curious and investigative as you break the story down into smaller parts
* Reauthoring
  * Taking what you learned from deconstructing and putting back together to understand the stories in a different way
* Remembering
  * Explore the impact of figures in your life - link people with values, commitments, and preferences that contribute to a positive narrative

### 🤕 Pain Reprocessing Therapy

*"It's so hard to make people feel anything other than pain." - the consequence of people interacting with each other relative to AI systems.*

A modality for treating chronic pain that is driven by the mind-body connection. This modality purports that the causes of chronic pain are tied to childhood trauma and major life events (serious illness or injury, death of a loved one, loss of a relationship, etc), and neural pathways become wired to encourage further pain, leading to a self-perpetuating cycle.

Pain comes from the brain and nervous system; it is not a purely physical experience, and thus can be changed. It is designed to protect you, and part of the recovery process is learning just what it's trying to protect you from.

Personality traits associated with chronic pain include:

* Hypersensitivity (can be more of a physiological trait)
* Perfectionism
* Strong Inner Critic
* People-Pleasing
* Negative Thinking and Pessimism
	* Tackle with Cognitive Behavioral Techniques
* Lack of Joy and Play
* Lack of Self-Compassion and Gratitude
* Difficulty Setting Boundaries with Others
* Pain Catastrophizing
	* Do you magnify pain in mind?
	* Do you ruminate about pain?
  * Do you feel helpless; convinced it'll never get better?

Signs of not coping well:

* Regular doctor and healthcare visits
* Clinging to ambiguous diagnoses as your identity
* Spending more time on bed or couch
* Staying in pajamas all day
* Dropping old hobbies without warning; fewer hobbies or pleasurable activities in general (less socializing, exercise, etc)
* Missing work and sleeping during the day
* Needing pain medication
* Fewer chores done
* Self-soothing with food

Signs of heightened health anxiety (related due the symptom imperative, though validate with a doctor if symptom is new):

* Muscle twitching all over body
* Numbness
* Blurry vision
* Dizziness
* Yellow shits
* Stomachaches, spasming stomach, bloating, acid reflux
* White covered tongue
* Brain fog, inability to concentrate
* heart jumps and scares
* Bloodshot eyes
* chest tightness and pain
* headaches
* migraines with aura
* ear ache
* ringing in my ear
* crawling sensation in my ear
* ulcers like all the time
* felt weak (e.g. In the gym)
* Nausea
* Back pain
* Joint pain
* jittery jaw/ involuntary jaw moving
* swollen lymph nodes
* numbness and tingling down one side of face

Recovery from chronic pain is not a linear process; relapses will happen and that is NORMAL! Steps to recovery are as follows:

* Understand Pain Triggers
  * Emotions: Anger, Sadness, Shame, Loneliness, Fear, Numbness, etc
  * Situations: Conflict, job loss, missing out on activities due to illness, etc 
  * Biological: Poor sleep, poor diet, dehydration, bright lights and loud noises, lack of exercise, etc
  * Mental: Negative self-talk, pressure to fix yourself and/or be perfect, 
* Understand Conditioned Responses
  * Brains can make unfortunate connections and associations, even if they aren't true or helpful, in an attempt to keep you safe
  * Not pain specific; can be "standing in a crowd causes a panic attack" or "standing causes pain"
* Reinforce Evidence of Pain Being Neuroplastic / Triggered by Fear
  * Pain moves around entire body
  * Becomes more intense (or disappears) when emotions run high
  * Search for general exceptions to rule you have noticed in the past
  * If feeling really stuck, imagine a miracle - what would your life be like if the pain all disappeared tomorrow? What would you do?
  * Allow for hope for the future by saying "yet" at the end of negative thoughts
  * In general, give the pain voice less airtime and/or don't take it as seriously
* Somatic Tracking
  * Mindfulness of sensations within the body with no agenda or judgment
    * What do you notice happening to the sensation as you focus on it? Does it intensify or subside? Does it spread out or contract? Does it move around or stay exactly the same? Does the quality of the sensation change at all?
    * If that doesn't work: Visualize the pain as toxic black ooze and envision it leaving the body
  * Cognitive Soothing - Send messages of safety to the brain
    * “It’s going to be okay either way” is a type of safety reappraisal that can be really effective in the face of uncertainty
    * When fear thoughts arise notice them, don't buy into them, and send a message of safety anyways
  * Positive Affect Induction - approach sensations with lightness and curiosity; turn down the intensity and watching it like a hawk
  * Outcome Independence - feeling successful regardless of the result (do not do somatic tracking with the goal of eradicating your pain)
* Develop Corrective Experiences
  * Feeling safe during exposure to the source of your fear; requires repeated events to rewire your brain to accept that an experience/emotion/sensation/etc is safe
  * Beware Extinction Bursts - where symptoms intensify as the brain makes a last-ditch effort to maintain the current behavior. Ride the wave and do not give into the fear
* Minimize Use of Avoidance Behaviors
  * Beware Vampire Mode - what we do affects how we think and feel. Withdrawing from pleasant experiences (leaving the house, seeing friends, working, hobbies, exercising, sunlight and fresh air, etc) will cause a crash in mood and make you feel worse as you feel more excluded socially and professionally
* Reduce Hypervigilance and Allow for Pleasant Sensations
* Understand Relapses
  * Stages are Panic, Forcing It (doing the same recovery steps with desperation), Stabilization (doing recovery steps with the right intentions)
  * Digging into weeds on childhood trauma and constantly revisiting isn't always the answer to reducing pain
* Don't Google your symptoms lest you think you have a stroke, tumor, heart attack, cancer, lyme disease, etc

### Radically Open Dialectical Behavior Therapy (RO DBT)

*We don’t feel connected because we feel safe. We feel safe because we feel connected.*

Radically Open DBT is meant for disorders of overcontrol (OC) and people with avoidant attachment styles. The core problem with OC clients include social signaling deficits, low openness, and aloofness. OC is a combination of nature, nurture, and risk-averse coping mechanisms [Difference between DBT vs RO DBT](https://www.newharbinger.com/blog/professional/how-is-ro-dbt-different-from-dbt/)

Overall, clients need to let go of always striving to perform better or try harder.

Signs of OC:

* Inhibited and disingenuous emotional expression
  * Fear of expressing a different opinion
  * Hiding how you're feeling
    * Saying you're fine when you're not
    * Never wanting others to know when you're upset, in distress
    * Avoiding and deflecting answering questions
* Hyper detailed, focused, and overly cautious behavior
* Rigid and rule-governed behavior
  * Constantly seeing mistakes everywhere, especially yourself
  * Foreboding joy - always expecting the other shoe to drop
  * Need to plan and prepare for everything
  * Compulsive fixers
* Aloof and distant style of relating
  * Avoiding eye contact
  * Keeping self physically small, closed off body language
  * Leaving when uncomfortable, especially during conflicts
  * Pride in extreme self-control abilities
  * Only laughing/smiling when a joke is truly funny
  * Delay or avoid returning calls and texts
* High social comparison, envy, and bitterness

Skills:

* Self-enquiry
  * Mindfulness practice that patients can use to better understand themselves and why they interact with the world in the way they do
  * "What is it that I might need to learn from the experience?"
  * Keep self-enquiry practices <5 mins and don't always trust the quick answers/urges you receive
* Use social signaling to attract others and feel safe by activating your social safety system
* Practice urge surfing when unwanted impulses occur
* Practice compassion when in a fixed and fatalistic mindset; aim to adapt a flexible mindset
* Cultivate healthy self-doubt
  * We don’t see things as they are but rather as we are.
* Big 3 + 1 Exercise
  * Take a deep breath by slowly inhaling and exhaling, and simultaneously:
  * Engage in a closed-mouth smile (turn up the ends of your lips and stretch your lips over your teeth). Note that this type of smile activates the muscles around your eyes (where you typically see wrinkles). If you try this smile and only the bottom half of your face is moving, you may be practising what’s referred to as a half-smile. Ensure that you activate the muscles around your eyes.
  * Raise your eyebrows for a moment.
  * Additionally, if you are sitting in a chair with a back, then lean back.


### Schema Therapy

List of Maladaptive Schemas

* Abandonment & Instability
* Mistrust & Abuse
* Emotional Deprivation
  * Signs: Emotionally feeling flat, disliking emotions, avoiding emotional situations, being "robotic" or otherwise detached, hiding emotions, only feeling emotion in nonpersonal ways
  * Treatment: Consider your past, use a third-person narrative to describe your feelings, read fiction, pay attention to fictional character's needs and feelings, use feelings wheel, learn about boundaries, practice sharing emotions with people who care, attending to emotions with care, validation, nurturing, and security
* Defectiveness & Shame
* Social Isolation & Alienation
  * Signs: Find social activities exhausting, hiding who you really are, believe if people see the real you they'll reject you, compare self unfavorably to others, strong inner critic, and often feel lonely 
  * Treatment: Review the past, change your POV, take stock, take a sober look at the situation, take action against the inner critic, start repairing your self-esteem
* Dependence & Incompetence
* Vulnerability to Harm or Illness
* Enmeshment & Undeveloped Self
* Failure to Achieve
* Entitlement & Grandiosity
* Insufficient Self-Control & Self-Discipline
* Subjugation
  * Excessive surrendering of control (needs, emotions) to others out of coercion
* Self-Sacrifice
* Approval & Recognition Seeking
* Negativity & Pessimism
* Emotional Inhibition
* Unrelenting Standards & Hypercriticalness
* Punitiveness
  * People, including oneself, should be harshly punished for making mistakes

Maladaptive Coping Responses

* Overcompensation
  * Aggression & Hostility
  * Dominance
  * Recognition Seeking
  * Manipulation & Exploitation
  * Passive-Aggressiveness & Rebellion
  * Excessive Orderliness & Obsessionality
* Surrender
  * Compliance & Dependence
* Avoidance
  * Social Withdrawal & Excessive Autonomy
  * Compulsive Stimulation Seeking
  * Addictive Self-Soothing
  * Psychological Withdrawal

Schema Modes:

* Innate child modes
  * Vulnerable child
  * Angry child
  * Impulsive child
  * Contented child
* Maladaptive coping modes
  * Compliant surrenderer
  * Detached protector
  * Overcompensator
* Maladaptive parent modes
  * Punitive parent
  * Demanding parent
* Healthy adult mode

## 🧎‍♀️ Yoga

### Shoulder

* Bow Pose
* Clasp Hands Behind Back
* Cow Face
* Cross-Body Reach
* Eagle Arms
* Finger Walk up Wall
* Forward Fold with Clasp
* Overhead shoulder stretch
* Thread the Needle
* Towel Stretch
* Wall Chest Stretch
* Wall Downward Dog
* Wall Prayer Stretch

### Back

* Cat-Camel
* Child's Pose
* Cobra
* Downward Dog
* Forward Fold
* Head to Knee
* Plow
* Puppy's Pose
* Rabbit Pose
* Revolved Head to Knee
* Side Angle
* Twists

### PSOAS and Hip Flexors

Hips are a storing ground for trauma, stress, and anxiety.

* Butterfly
* Cow-Face
* Double pigeon
* Eye of the needle
* Forward fold
* Frog pose
* Happy baby
* Indian Pose
* Pigeon
* Runner's lunge (support back leg on bed to get a more targeted stretch)
* Seated twist